package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BusinessOwner generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_OWNER", catalog = "HOUSE_OWNER_RECORD")
public class BusinessOwner implements java.io.Serializable {

	private String id;
	private BusinessHouse businessHouse;
	private String name;
	private String idType;
	private String idNo;
	private String phone;
	private String rootAddress;
	private String type;

	public BusinessOwner() {
	}

	public BusinessOwner(String id, BusinessHouse businessHouse, String name,
			String idType, String idNo, String phone, String type) {
		this.id = id;
		this.businessHouse = businessHouse;
		this.name = name;
		this.idType = idType;
		this.idNo = idNo;
		this.phone = phone;
		this.type = type;
	}
	public BusinessOwner(String id, BusinessHouse businessHouse, String name,
			String idType, String idNo, String phone, String rootAddress,
			String type) {
		this.id = id;
		this.businessHouse = businessHouse;
		this.name = name;
		this.idType = idType;
		this.idNo = idNo;
		this.phone = phone;
		this.rootAddress = rootAddress;
		this.type = type;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_ID", nullable = false)
	@NotNull
	public BusinessHouse getBusinessHouse() {
		return this.businessHouse;
	}

	public void setBusinessHouse(BusinessHouse businessHouse) {
		this.businessHouse = businessHouse;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ID_TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "ID_NO", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "PHONE", nullable = false, length = 15)
	@NotNull
	@Size(max = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "ROOT_ADDRESS", length = 50)
	@Size(max = 50)
	public String getRootAddress() {
		return this.rootAddress;
	}

	public void setRootAddress(String rootAddress) {
		this.rootAddress = rootAddress;
	}

	@Column(name = "TYPE", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
