package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseState generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_STATE", catalog = "HOUSE_OWNER_RECORD")
public class BusinessHouseState implements java.io.Serializable {

	private String id;
	private BusinessHouse businessHouse;
	private String state;

	public BusinessHouseState() {
	}

	public BusinessHouseState(String id, BusinessHouse businessHouse, String state) {
		this.id = id;
		this.businessHouse = businessHouse;
		this.state = state;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_ID", nullable = false)
	@NotNull
	public BusinessHouse getBusinessHouse() {
		return this.businessHouse;
	}

	public void setBusinessHouse(BusinessHouse businessHouse) {
		this.businessHouse = businessHouse;
	}

	@Column(name = "STATE", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
