package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import com.dgsoft.common.OrderBeanComparator;
import com.dgsoft.common.OrderModel;
import org.hibernate.annotations.GenericGenerator;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BusinessMoney generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_MONEY", catalog = "HOUSE_OWNER_RECORD")
public class BusinessMoney implements java.io.Serializable , OrderModel {

	public enum PreferentialType{
        HALF_RECEIVE, FREE_MONEY
    }



	private String id;
    private String typeName;
	private OwnerBusiness ownerBusiness;
	private String moneyTypeId;
	private BigDecimal checkMoney;
	private BigDecimal shouldMoney;
	private BigDecimal factMoney;
	private String chargeDetails;
    private FactMoneyInfo factMoneyInfo;
    private int pri;
    private PreferentialType preferential;




	public BusinessMoney() {
	}


	public BusinessMoney(OwnerBusiness ownerBusiness,
                         String moneyTypeId,String typeName,
						 String chargeDetails,int pri) {
        this.typeName = typeName;
		this.ownerBusiness = ownerBusiness;
		this.moneyTypeId = moneyTypeId;
		this.chargeDetails = chargeDetails;
		this.checkMoney = new BigDecimal(0);
		this.factMoney = new BigDecimal(0);
		this.shouldMoney = new BigDecimal(0);
        this.pri = pri;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}


	public void setId(String id) {
		this.id = id;
	}


    @Column(name = "TYPE_NAME", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS", nullable = false)
	@NotNull
	public OwnerBusiness getOwnerBusiness() {
		return this.ownerBusiness;
	}

	public void setOwnerBusiness(OwnerBusiness ownerBusiness) {
		this.ownerBusiness = ownerBusiness;
	}

	@Column(name = "MONEY_TYPE_ID", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)

	public String getMoneyTypeId() {
		return this.moneyTypeId;
	}

	public void setMoneyTypeId(String moneyTypeId) {
		this.moneyTypeId = moneyTypeId;
	}

	@Column(name="CHECK_MONEY", nullable = false, precision = 19, scale = 4)
	@NotNull
	public BigDecimal getCheckMoney() {
		return checkMoney;
	}

	public void setCheckMoney(BigDecimal checkMoney) {
		this.checkMoney = checkMoney;
	}

	@Column(name = "SHOULD_MONEY", nullable = false, precision = 19, scale = 4)
	@NotNull
	public BigDecimal getShouldMoney() {
		return this.shouldMoney;
	}

	public void setShouldMoney(BigDecimal shouldMoney) {
		this.shouldMoney = shouldMoney;
	}

	@Column(name = "FACT_MONEY", nullable = false, precision = 19, scale = 4)
	@NotNull
	public BigDecimal getFactMoney() {
		return this.factMoney;
	}

	public void setFactMoney(BigDecimal factMoney) {
		this.factMoney = factMoney;
	}

	@Column(name = "CHARGE_DETAILS", length = 200)
	@Size(max = 200)
	public String getChargeDetails() {
		return this.chargeDetails;
	}

	public void setChargeDetails(String chargeDetails) {
		this.chargeDetails = chargeDetails;
	}


    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "FEE",nullable = true)
    public FactMoneyInfo getFactMoneyInfo() {
        return factMoneyInfo;
    }

    public void setFactMoneyInfo(FactMoneyInfo factMoneyInfo) {
        this.factMoneyInfo = factMoneyInfo;
    }

    @Override
    @Column(name = "PRI" , nullable = false )
    public int getPriority() {
        return pri;
    }

    @Override
    public void setPriority(int priority) {
        this.pri = priority;
    }


    @Enumerated(EnumType.STRING)
    @Column(name = "PREFERENTIAL", nullable = true, length = 21)
    public PreferentialType getPreferential() {
        return preferential;
    }

    public void setPreferential(PreferentialType preferential) {
        this.preferential = preferential;
    }
}
