package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import com.dgsoft.common.system.PersonEntity;
import org.hibernate.annotations.GenericGenerator;

import java.math.BigDecimal;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BusinessPool generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_POOL", catalog = "HOUSE_OWNER_RECORD")
public class BusinessPool implements java.io.Serializable {

    public enum BusinessPoolType{
        NOW_POOL,NEW_POOL;
    }

	private String id;
    private BusinessHouse businessHouse;
	private BusinessPoolType type;
	private String name;
    private PersonEntity.CredentialsType credentialsType;
    private String cerdentialsNumber;
	private String relation;
	private BigDecimal poolArea;
	private String perc;
	private String memo;
    private String phone;

	public BusinessPool() {
	}

    public BusinessPool(BusinessHouse businessHouse, BusinessPoolType type, String name,
                        PersonEntity.CredentialsType credentialsType, String cerdentialsNumber,
                        String relation, BigDecimal poolArea, String perc, String memo,String phone) {
        this.businessHouse = businessHouse;
        this.type = type;
        this.name = name;
        this.credentialsType = credentialsType;
        this.cerdentialsNumber = cerdentialsNumber;
        this.relation = relation;
        this.poolArea = poolArea;
        this.perc = perc;
        this.memo = memo;
    }

    @Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "HOUSE_ID", nullable = false)
    @NotNull
    public BusinessHouse getBusinessHouse() {
        return businessHouse;
    }

    public void setBusinessHouse(BusinessHouse businessHouse) {
        this.businessHouse = businessHouse;
    }

    @Enumerated(EnumType.STRING)
    @Column(name = "TYPE", nullable = false, length = 20)
	@NotNull
	public BusinessPoolType getType() {
		return this.type;
	}

	public void setType(BusinessPoolType type) {
		this.type = type;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


    @Enumerated(EnumType.STRING)
    @Column(name = "ID_TYPE", nullable = false, length = 32)
    @NotNull
    public PersonEntity.CredentialsType getCredentialsType() {
        return credentialsType;
    }

    public void setCredentialsType(PersonEntity.CredentialsType credentialsType) {
        this.credentialsType = credentialsType;
    }

    @Column(name = "ID_NO", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getCerdentialsNumber() {
        return cerdentialsNumber;
    }

    public void setCerdentialsNumber(String cerdentialsNumber) {
        this.cerdentialsNumber = cerdentialsNumber;
    }

	@Column(name = "RELATION", length = 32)
	@Size(max = 32)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	@Column(name = "POOL_AREA", scale = 4)
	public BigDecimal getPoolArea() {
		return this.poolArea;
	}

	public void setPoolArea(BigDecimal poolArea) {
		this.poolArea = poolArea;
	}

	@Column(name = "PERC", length = 10)
	@Size(max = 10)
	public String getPerc() {
		return this.perc;
	}

	public void setPerc(String perc) {
		this.perc = perc;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

    @Column(name = "PHONE", nullable = true, length = 15)
    @Size(max = 15)
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

}
