package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import com.dgsoft.common.system.PersonEntity;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BusinessOwner generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_OWNER", catalog = "HOUSE_OWNER_RECORD")
public class BusinessHouseOwner implements java.io.Serializable,PersonEntity {

    public enum HouseOwnerType{
        NOW_HOUSE_OWNER
        ,NEW_HOUSE_OWNER;

    }

	private String id;
	private HouseBusiness houseBusiness;
	private String personName;
	private CredentialsType credentialsType;
	private String credentialsNumber;
	private String phone;
	private String rootAddress;
	private HouseOwnerType type;
    private String memo;

	public BusinessHouseOwner() {
	}

    public BusinessHouseOwner(HouseOwnerType type) {
        this.type = type;
    }

    public BusinessHouseOwner(HouseBusiness houseBusiness, String personName, CredentialsType credentialsType,
                              String credentialsNumber, String phone, String rootAddress, HouseOwnerType type,String memo) {
        this.houseBusiness = houseBusiness;
        this.personName = personName;
        this.credentialsType = credentialsType;
        this.credentialsNumber = credentialsNumber;
        this.phone = phone;
        this.rootAddress = rootAddress;
        this.type = type;
        this.memo = memo;
    }

    @Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "HOUSE_ID", nullable = false)
    @NotNull
    public HouseBusiness getHouseBusiness() {
        return houseBusiness;
    }

    public void setHouseBusiness(HouseBusiness houseBusiness) {
        this.houseBusiness = houseBusiness;
    }

    @Override
	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String name) {
		this.personName = name;
	}

    @Override
    @Enumerated(EnumType.STRING)
	@Column(name = "ID_TYPE", nullable = false, length = 32)
	@NotNull
	public CredentialsType getCredentialsType() {
		return this.credentialsType;
	}

	public void setCredentialsType(CredentialsType idType) {
		this.credentialsType = idType;
	}

    @Override
	@Column(name = "ID_NO", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getCredentialsNumber() {
		return this.credentialsNumber;
	}

	public void setCredentialsNumber(String idNo) {
		this.credentialsNumber = idNo;
	}

	@Column(name = "PHONE", nullable = false, length = 15)
	@NotNull
	@Size(max = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "ROOT_ADDRESS", length = 50)
	@Size(max = 50)
	public String getRootAddress() {
		return this.rootAddress;
	}

	public void setRootAddress(String rootAddress) {
		this.rootAddress = rootAddress;
	}

    @Enumerated(EnumType.STRING)
	@Column(name = "TYPE", nullable = false, length = 20)
	@NotNull
	public HouseOwnerType getType() {
		return this.type;
	}

	public void setType(HouseOwnerType type) {
		this.type = type;
	}

    @Column(name="MEMO",nullable = true,length = 200)
    @Size(max = 200)
    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }
}
