package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import com.dgsoft.house.model.Build;
import org.hibernate.annotations.GenericGenerator;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Build generated by hbm2java
 */
@Entity
@Table(name = "BUILD", catalog = "HOUSE_OWNER_RECORD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MAP_NUMBER", "BLOCK_NO", "BUILD_NO"}))
public class BusinessBuild implements java.io.Serializable {

	private String id;
	private BusinessProject businessProject;
	private String landBlockCode;
	private String mapNumber;
	private String blockNo;
	private String buildNo;
	private String streetCode;
	private String completeDate;
	private String name;
	private String doorNo;
	private Integer unintCount;
	private int floorCount;
	private String address;
	private Integer houseCount;
	private BigDecimal area;
	private BigDecimal lng;
	private BigDecimal lat;
	private String buildType;
	private String structure;
	private Integer homeCount;
	private BigDecimal homeArea;
	private Integer unhomeCount;
	private BigDecimal unhomeArea;
	private Integer shopCount;
	private BigDecimal shopArea;
	private int upFloorCount;
	private int downFloorCount;
	private boolean haveDownRoom;
	private String buildCode;
	private Set<BusinessHouse> businessHouses = new HashSet<BusinessHouse>(0);

	public BusinessBuild() {
	}

	public BusinessBuild(Build build){
        this.landBlockCode = build.getLandBlockCode();
        this.mapNumber = build.getMapNumber();
        this.blockNo = build.getBlockNo();
        this.buildNo = build.getBuildNo();
        this.streetCode = build.getStreetCode();
        this.completeDate = build.getCompleteDate();
        this.name = build.getName();
        this.doorNo = build.getDoorNo();
        this.unintCount = build.getUnintCount();
        this.floorCount = build.getFloorCount();
        this.address = build.getAddress();
        this.houseCount = build.getHouseCount();
        this.area = build.getArea();
        this.lng = build.getLng();
        this.lat = build.getLat();
        this.buildType = build.getBuildType();
        this.structure = build.getStructure();
        this.homeCount = build.getHomeCount();
        this.homeArea = build.getHomeArea();
        this.unhomeArea = build.getUnhomeArea();
        this.unhomeCount = build.getUnhomeCount();
        this.shopCount = build.getShopCount();
        this.shopArea = build.getShopArea();
        this.upFloorCount = build.getUpFloorCount();
        this.downFloorCount = build.getDownFloorCount();
        this.haveDownRoom = build.isHaveDownRoom();
        this.buildCode = build.getId();
        this.businessProject = new BusinessProject(build.getProject());

    }

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.ALL},optional = false)
	@JoinColumn(name = "PROJECT",nullable = false)
    @NotNull
	public BusinessProject getBusinessProject() {
		return this.businessProject;
	}

	public void setBusinessProject(BusinessProject businessProject) {
		this.businessProject = businessProject;
	}

	@Column(name = "LAND_BLOCK_CODE", length = 4)
	@Size(max = 4)
	public String getLandBlockCode() {
		return this.landBlockCode;
	}

	public void setLandBlockCode(String landBlockCode) {
		this.landBlockCode = landBlockCode;
	}

	@Column(name = "MAP_NUMBER", length = 4)
	@Size(max = 4)
	public String getMapNumber() {
		return this.mapNumber;
	}

	public void setMapNumber(String mapNumber) {
		this.mapNumber = mapNumber;
	}

	@Column(name = "BLOCK_NO", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getBlockNo() {
		return this.blockNo;
	}

	public void setBlockNo(String blockNo) {
		this.blockNo = blockNo;
	}

	@Column(name = "BUILD_NO", nullable = false, length = 4)
	@NotNull
	@Size(max = 4)
	public String getBuildNo() {
		return this.buildNo;
	}

	public void setBuildNo(String buildNo) {
		this.buildNo = buildNo;
	}

	@Column(name = "STREET_CODE", length = 4)
	@Size(max = 4)
	public String getStreetCode() {
		return this.streetCode;
	}

	public void setStreetCode(String streetCode) {
		this.streetCode = streetCode;
	}

	@Column(name = "COMPLETE_DATE", length = 6)
	@Size(max = 6)
	public String getCompleteDate() {
		return this.completeDate;
	}

	public void setCompleteDate(String completeDate) {
		this.completeDate = completeDate;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DOOR_NO", length = 10)
	@Size(max = 10)
	public String getDoorNo() {
		return this.doorNo;
	}

	public void setDoorNo(String doorNo) {
		this.doorNo = doorNo;
	}

	@Column(name = "UNINT_COUNT")
	public Integer getUnintCount() {
		return this.unintCount;
	}

	public void setUnintCount(Integer unintCount) {
		this.unintCount = unintCount;
	}

	@Column(name = "FLOOR_COUNT", nullable = false)
	public int getFloorCount() {
		return this.floorCount;
	}

	public void setFloorCount(int floorCount) {
		this.floorCount = floorCount;
	}

	@Column(name = "ADDRESS", length = 50)
	@Size(max = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "HOUSE_COUNT")
	public Integer getHouseCount() {
		return this.houseCount;
	}

	public void setHouseCount(Integer houseCount) {
		this.houseCount = houseCount;
	}

	@Column(name = "AREA", precision = 18, scale = 3)
	public BigDecimal getArea() {
		return this.area;
	}

	public void setArea(BigDecimal area) {
		this.area = area;
	}

	@Column(name = "LNG", precision = 18, scale = 14)
	public BigDecimal getLng() {
		return this.lng;
	}

	public void setLng(BigDecimal lng) {
		this.lng = lng;
	}

	@Column(name = "LAT", precision = 18, scale = 14)
	public BigDecimal getLat() {
		return this.lat;
	}

	public void setLat(BigDecimal lat) {
		this.lat = lat;
	}

	@Column(name = "BUILD_TYPE", length = 32)
	@Size(max = 32)
	public String getBuildType() {
		return this.buildType;
	}

	public void setBuildType(String buildType) {
		this.buildType = buildType;
	}

	@Column(name = "STRUCTURE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getStructure() {
		return this.structure;
	}

	public void setStructure(String structure) {
		this.structure = structure;
	}

	@Column(name = "HOME_COUNT")
	public Integer getHomeCount() {
		return this.homeCount;
	}

	public void setHomeCount(Integer homeCount) {
		this.homeCount = homeCount;
	}

	@Column(name = "HOME_AREA", precision = 18, scale = 3)
	public BigDecimal getHomeArea() {
		return this.homeArea;
	}

	public void setHomeArea(BigDecimal homeArea) {
		this.homeArea = homeArea;
	}

	@Column(name = "UNHOME_COUNT")
	public Integer getUnhomeCount() {
		return this.unhomeCount;
	}

	public void setUnhomeCount(Integer unhomeCount) {
		this.unhomeCount = unhomeCount;
	}

	@Column(name = "UNHOME_AREA", precision = 18, scale = 3)
	public BigDecimal getUnhomeArea() {
		return this.unhomeArea;
	}

	public void setUnhomeArea(BigDecimal unhomeArea) {
		this.unhomeArea = unhomeArea;
	}

	@Column(name = "SHOP_COUNT")
	public Integer getShopCount() {
		return this.shopCount;
	}

	public void setShopCount(Integer shopCount) {
		this.shopCount = shopCount;
	}

	@Column(name = "SHOP_AREA", precision = 18, scale = 3)
	public BigDecimal getShopArea() {
		return this.shopArea;
	}

	public void setShopArea(BigDecimal shopArea) {
		this.shopArea = shopArea;
	}

	@Column(name = "UP_FLOOR_COUNT", nullable = false)
	public int getUpFloorCount() {
		return this.upFloorCount;
	}

	public void setUpFloorCount(int upFloorCount) {
		this.upFloorCount = upFloorCount;
	}

	@Column(name = "DOWN_FLOOR_COUNT", nullable = false)
	public int getDownFloorCount() {
		return this.downFloorCount;
	}

	public void setDownFloorCount(int downFloorCount) {
		this.downFloorCount = downFloorCount;
	}

	@Column(name = "HAVE_DOWN_ROOM", nullable = false)
	public boolean isHaveDownRoom() {
		return this.haveDownRoom;
	}

	public void setHaveDownRoom(boolean haveDownRoom) {
		this.haveDownRoom = haveDownRoom;
	}

	@Column(name = "BUILD_CODE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getBuildCode() {
		return this.buildCode;
	}

	public void setBuildCode(String buildCode) {
		this.buildCode = buildCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessBuild")
	public Set<BusinessHouse> getBusinessHouses() {
		return this.businessHouses;
	}

	public void setBusinessHouses(Set<BusinessHouse> businessHouses) {
		this.businessHouses = businessHouses;
	}

}
