package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import com.dgsoft.house.HouseInState;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseState generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_STATE", catalog = "HOUSE_OWNER_RECORD")
public class BusinessHouseState implements java.io.Serializable {

	private String id;
	private BusinessHouse businessHouse;
	private HouseInState state;

	public BusinessHouseState() {
	}

	public BusinessHouseState(BusinessHouse businessHouse, HouseInState state) {
		this.businessHouse = businessHouse;
		this.state = state;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_ID", nullable = false)
	@NotNull
	public BusinessHouse getBusinessHouse() {
		return this.businessHouse;
	}

	public void setBusinessHouse(BusinessHouse businessHouse) {
		this.businessHouse = businessHouse;
	}

    @Enumerated(EnumType.STRING)
	@Column(name = "STATE", nullable = false, length = 20)
	@NotNull
	public HouseInState getState() {
		return this.state;
	}

	public void setState(HouseInState state) {
		this.state = state;
	}

}
