package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import org.hibernate.annotations.GenericGenerator;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BusinessMoney generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_MONEY", catalog = "HOUSE_OWNER_RECORD")
public class BusinessMoney implements java.io.Serializable {
    // 登记费,变更登记费（半价登记费）,工本费,继承赠与手续费,交易手续费,回迁手续费,商品房交易手续费,备案手续费,测绘费
//    public enum  MoneyType{
//       REGISTER,REGISTER_CHANGE,CARD,DEAL_INHERIT_GIFT,DEAL,DEAL_BACK,DEAL_COMMERCIAL,DEAL_RECORD,MAPPING
//    }

	private String id;
    private String typeName;
	private OwnerBusiness ownerBusiness;
	private String moneyTypeId;
	private BigDecimal shouldMoney;
	private BigDecimal factMoney;
	private String chargeDetails;
	private String memo;
    private FactMoneyInfo factMoneyInfo;




	public BusinessMoney() {
	}


	public BusinessMoney(OwnerBusiness ownerBusiness,
                         String moneyTypeId,String typeName, BigDecimal shouldMoney,String chargeDetails) {
        this.typeName = typeName;
		this.ownerBusiness = ownerBusiness;
		this.moneyTypeId = moneyTypeId;
		this.shouldMoney = shouldMoney;
        this.factMoney = shouldMoney;
		this.chargeDetails = chargeDetails;

	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}





	public void setId(String id) {
		this.id = id;
	}


    @Column(name = "TYPE_NAME", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS", nullable = false)
	@NotNull
	public OwnerBusiness getOwnerBusiness() {
		return this.ownerBusiness;
	}

	public void setOwnerBusiness(OwnerBusiness ownerBusiness) {
		this.ownerBusiness = ownerBusiness;
	}

	@Column(name = "MONEY_TYPE_ID", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)

	public String getMoneyTypeId() {
		return this.moneyTypeId;
	}

	public void setMoneyTypeId(String moneyTypeId) {
		this.moneyTypeId = moneyTypeId;
	}

	@Column(name = "SHOULD_MONEY", precision = 18, scale = 3)
	public BigDecimal getShouldMoney() {
		return this.shouldMoney;
	}

	public void setShouldMoney(BigDecimal shouldMoney) {
		this.shouldMoney = shouldMoney;
	}

	@Column(name = "FACT_MONEY", precision = 18, scale = 3)
	public BigDecimal getFactMoney() {
		return this.factMoney;
	}

	public void setFactMoney(BigDecimal factMoney) {
		this.factMoney = factMoney;
	}

	@Column(name = "CHARGE_DETAILS", length = 200)
	@Size(max = 200)
	public String getChargeDetails() {
		return this.chargeDetails;
	}

	public void setChargeDetails(String chargeDetails) {
		this.chargeDetails = chargeDetails;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FEE",nullable = true)
    public FactMoneyInfo getFactMoneyInfo() {
        return factMoneyInfo;
    }

    public void setFactMoneyInfo(FactMoneyInfo factMoneyInfo) {
        this.factMoneyInfo = factMoneyInfo;
    }
}
