package com.dgsoft.house.owner.model;
// Generated Aug 18, 2014 5:12:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Business generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS", catalog = "HOUSE_OWNER_RECORD")
public class Business implements java.io.Serializable {

	private String id;
	private Integer version;
	private Business business;
	private String source;
	private Date recordTime;
	private String processMessage;
	private String mappingCorpCode;
	private String mappingCorp;
	private String memo;
	private String status;
	private Date applyTime;
	private Date createTime;
	private Set<Reason> reasons = new HashSet<Reason>(0);
	private Set<Business> businesses = new HashSet<Business>(0);
	private Set<BusinessHouse> businessHouses = new HashSet<BusinessHouse>(0);
	private Set<OtherRegiste> otherRegistes = new HashSet<OtherRegiste>(0);
	private Set<BusinessMoney> businessMoneys = new HashSet<BusinessMoney>(
			0);
	private Set<MappingCorp> mappingCorps = new HashSet<MappingCorp>(0);
	private Set<BusinessEmp> businessEmps = new HashSet<BusinessEmp>(0);
	private Set<Card> cards = new HashSet<Card>(0);
	private Set<BusinessPersion> businessPersions = new HashSet<BusinessPersion>(
			0);
	private Set<ProjectSellCard> projectSellCards = new HashSet<ProjectSellCard>(
			0);

	public Business() {
	}

	public Business(String id, String source, Date recordTime, String status,
			Date applyTime, Date createTime) {
		this.id = id;
		this.source = source;
		this.recordTime = recordTime;
		this.status = status;
		this.applyTime = applyTime;
		this.createTime = createTime;
	}
	public Business(String id, Business business, String source,
			Date recordTime, String processMessage, String mappingCorpCode,
			String mappingCorp, String memo, String status, Date applyTime,
			Date createTime, Set<Reason> reasons, Set<Business> businesses,
			Set<BusinessHouse> businessHouses, Set<OtherRegiste> otherRegistes,
			Set<BusinessMoney> businessMoneys,
			Set<MappingCorp> mappingCorps, Set<BusinessEmp> businessEmps,
			Set<Card> cards, Set<BusinessPersion> businessPersions,
			Set<ProjectSellCard> projectSellCards) {
		this.id = id;
		this.business = business;
		this.source = source;
		this.recordTime = recordTime;
		this.processMessage = processMessage;
		this.mappingCorpCode = mappingCorpCode;
		this.mappingCorp = mappingCorp;
		this.memo = memo;
		this.status = status;
		this.applyTime = applyTime;
		this.createTime = createTime;
		this.reasons = reasons;
		this.businesses = businesses;
		this.businessHouses = businessHouses;
		this.otherRegistes = otherRegistes;
		this.businessMoneys = businessMoneys;
		this.mappingCorps = mappingCorps;
		this.businessEmps = businessEmps;
		this.cards = cards;
		this.businessPersions = businessPersions;
		this.projectSellCards = projectSellCards;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BEFORE_BUSINESS_ID")
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@Column(name = "SOURCE", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORD_TIME", nullable = false, length = 19)
	@NotNull
	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	@Column(name = "PROCESS_MESSAGE", length = 400)
	@Size(max = 400)
	public String getProcessMessage() {
		return this.processMessage;
	}

	public void setProcessMessage(String processMessage) {
		this.processMessage = processMessage;
	}

	@Column(name = "MAPPING_CORP_CODE", length = 32)
	@Size(max = 32)
	public String getMappingCorpCode() {
		return this.mappingCorpCode;
	}

	public void setMappingCorpCode(String mappingCorpCode) {
		this.mappingCorpCode = mappingCorpCode;
	}

	@Column(name = "MAPPING_CORP", length = 100)
	@Size(max = 100)
	public String getMappingCorp() {
		return this.mappingCorp;
	}

	public void setMappingCorp(String mappingCorp) {
		this.mappingCorp = mappingCorp;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "STATUS", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPLY_TIME", nullable = false, length = 19)
	@NotNull
	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	@NotNull
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<Reason> getReasons() {
		return this.reasons;
	}

	public void setReasons(Set<Reason> reasons) {
		this.reasons = reasons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<Business> getBusinesses() {
		return this.businesses;
	}

	public void setBusinesses(Set<Business> businesses) {
		this.businesses = businesses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<BusinessHouse> getBusinessHouses() {
		return this.businessHouses;
	}

	public void setBusinessHouses(Set<BusinessHouse> businessHouses) {
		this.businessHouses = businessHouses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<OtherRegiste> getOtherRegistes() {
		return this.otherRegistes;
	}

	public void setOtherRegistes(Set<OtherRegiste> otherRegistes) {
		this.otherRegistes = otherRegistes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<BusinessMoney> getBusinessMoneys() {
		return this.businessMoneys;
	}

	public void setBusinessMoneys(
            Set<BusinessMoney> businessMoneys) {
		this.businessMoneys = businessMoneys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<MappingCorp> getMappingCorps() {
		return this.mappingCorps;
	}

	public void setMappingCorps(Set<MappingCorp> mappingCorps) {
		this.mappingCorps = mappingCorps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<BusinessEmp> getBusinessEmps() {
		return this.businessEmps;
	}

	public void setBusinessEmps(Set<BusinessEmp> businessEmps) {
		this.businessEmps = businessEmps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<Card> getCards() {
		return this.cards;
	}

	public void setCards(Set<Card> cards) {
		this.cards = cards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<BusinessPersion> getBusinessPersions() {
		return this.businessPersions;
	}

	public void setBusinessPersions(Set<BusinessPersion> businessPersions) {
		this.businessPersions = businessPersions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "business")
	public Set<ProjectSellCard> getProjectSellCards() {
		return this.projectSellCards;
	}

	public void setProjectSellCards(Set<ProjectSellCard> projectSellCards) {
		this.projectSellCards = projectSellCards;
	}

}
