package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BusinessPool generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_POOL", catalog = "HOUSE_OWNER_RECORD")
public class BusinessPool implements java.io.Serializable {

	private String id;
	private HouseBusiness houseBusiness;
	private String type;
	private String name;
	private String idType;
	private String idNo;
	private String relation;
	private BigDecimal poolArea;
	private String perc;
	private String memo;

	public BusinessPool() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_ID", nullable = false)
	@NotNull
    public HouseBusiness getHouseBusiness() {
        return houseBusiness;
    }

    public void setHouseBusiness(HouseBusiness houseBusiness) {
        this.houseBusiness = houseBusiness;
    }

    @Column(name = "TYPE", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ID_TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "ID_NO", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "RELATION", length = 32)
	@Size(max = 32)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	@Column(name = "POOL_AREA", scale = 4)
	public BigDecimal getPoolArea() {
		return this.poolArea;
	}

	public void setPoolArea(BigDecimal poolArea) {
		this.poolArea = poolArea;
	}

	@Column(name = "PERC", length = 10)
	@Size(max = 10)
	public String getPerc() {
		return this.perc;
	}

	public void setPerc(String perc) {
		this.perc = perc;
	}

	@Column(name = "MEMO", length = 100)
	@Size(max = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
