package com.dgsoft.house.owner.model;
// Generated Oct 11, 2014 3:13:15 PM by Hibernate Tools 4.0.0


import com.dgsoft.house.ProjectInfo;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "PROJECT", catalog = "HOUSE_OWNER_RECORD")
public class BusinessProject implements java.io.Serializable, ProjectInfo {


    private String id;
    private OwnerBusiness ownerBusiness;
    private String name;
    private String address;
    private Date mapTime;
    private String completeDate;
    private String developerName;
    private String developerCode;
    private String sectionName;
    private String sectionCode;
    private String districtCode;
    private String districtName;
    private String projectCode;
    private Set<ProjectRecordStore> projectRecordStores = new HashSet<ProjectRecordStore>(0);
    private Set<BusinessBuild> businessBuilds = new HashSet<BusinessBuild>(0);
    private ProjectSellInfo projectSellInfo;

    public BusinessProject() {
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 32)
    @NotNull
    @Size(max = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BUSINESS", nullable = false)
    @NotNull
    public OwnerBusiness getOwnerBusiness() {
        return this.ownerBusiness;
    }

    public void setOwnerBusiness(OwnerBusiness ownerBusiness) {
        this.ownerBusiness = ownerBusiness;
    }


    @Column(name = "NAME", nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name = "ADDRESS", length = 200)
    @Size(max = 200)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MAP_TIME", nullable = false, length = 19)
    @NotNull
    public Date getMapTime() {
        return this.mapTime;
    }

    public void setMapTime(Date mapTime) {
        this.mapTime = mapTime;
    }

    @Column(name = "COMPLETE_DATE", length = 6)
    @Size(max = 6)
    public String getCompleteDate() {
        return this.completeDate;
    }

    public void setCompleteDate(String completeDate) {
        this.completeDate = completeDate;
    }


    @Column(name = "DEVELOPER_NAME", length = 100)
    @Size(max = 100)
    public String getDeveloperName() {
        return this.developerName;
    }

    public void setDeveloperName(String developerName) {
        this.developerName = developerName;
    }


    @Column(name = "DEVELOPER_CODE", length = 32)
    @Size(max = 32)
    public String getDeveloperCode() {
        return this.developerCode;
    }

    @Override
    @Transient
    public String getProjectName() {
        return getName();
    }

    public void setDeveloperCode(String developerCode) {
        this.developerCode = developerCode;
    }


    @Column(name = "SECTION_NAME", nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    public String getSectionName() {
        return this.sectionName;
    }

    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }


    @Column(name = "SECTION_CODE", nullable = false, length = 32)
    @NotNull
    @Size(max = 32)
    public String getSectionCode() {
        return this.sectionCode;
    }

    public void setSectionCode(String sectionCode) {
        this.sectionCode = sectionCode;
    }


    @Column(name = "DISTRICT_CODE", nullable = false, length = 32)
    @NotNull
    @Size(max = 32)
    public String getDistrictCode() {
        return this.districtCode;
    }

    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }


    @Column(name = "DISTRICT_NAME", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getDistrictName() {
        return this.districtName;
    }

    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }


    @Column(name = "PROJECT_CODE", nullable = false, length = 32)
    @NotNull
    @Size(max = 32)
    public String getProjectCode() {
        return this.projectCode;
    }

    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "businessProject")
    public Set<ProjectRecordStore> getProjectRecordStores() {
        return this.projectRecordStores;
    }

    public void setProjectRecordStores(Set<ProjectRecordStore> projectRecordStores) {
        this.projectRecordStores = projectRecordStores;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true, mappedBy = "businessProject")
    public Set<BusinessBuild> getBusinessBuilds() {
        return this.businessBuilds;
    }

    public void setBusinessBuilds(Set<BusinessBuild> businessBuilds) {
        this.businessBuilds = businessBuilds;
    }

    @OneToOne(cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn
    public ProjectSellInfo getProjectSellInfo() {
        return projectSellInfo;
    }

    public void setProjectSellInfo(ProjectSellInfo projectSellInfo) {
        this.projectSellInfo = projectSellInfo;
    }
}


