package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * BusinessEmp generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_EMP", catalog = "HOUSE_OWNER_RECORD")
public class BusinessEmp implements java.io.Serializable {

	private String id;
	private OwnerBusiness ownerBusiness;
	private String type;
	private String taskName;
	private String empCode;
	private String empName;

	public BusinessEmp() {
	}

	public BusinessEmp(String id, OwnerBusiness ownerBusiness, String type,
			String taskName, String empCode, String empName) {
		this.id = id;
		this.ownerBusiness = ownerBusiness;
		this.type = type;
		this.taskName = taskName;
		this.empCode = empCode;
		this.empName = empName;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_ID", nullable = false)
	@NotNull
	public OwnerBusiness getOwnerBusiness() {
		return this.ownerBusiness;
	}

	public void setOwnerBusiness(OwnerBusiness ownerBusiness) {
		this.ownerBusiness = ownerBusiness;
	}

	@Column(name = "TYPE", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "TASK_NAME", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "EMP_CODE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Column(name = "EMP_NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

}
