package com.dgsoft.house.owner.model;
// Generated Aug 24, 2015 1:17:35 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ContractMortgage generated by hbm2java
 */
@Entity
@Table(name = "CONTRACT_MORTGAGE", catalog = "HOUSE_OWNER_RECORD")
public class ContractMortgage implements java.io.Serializable {

	private String id;
	private String commerciId;
	private String isMortgage;
	private String mortgageType;
	private String mortgagePeopre;
	private String mortgageObligee;
	private String mortgageRegister;
	private String mortgageTime;
	private String contract;

	public ContractMortgage() {
	}

	public ContractMortgage(String id, String commerciId, String contract) {
		this.id = id;
		this.commerciId = commerciId;
		this.contract = contract;
	}
	public ContractMortgage(String id, String commerciId, String isMortgage,
			String mortgageType, String mortgagePeopre, String mortgageObligee,
			String mortgageRegister, String mortgageTime, String contract) {
		this.id = id;
		this.commerciId = commerciId;
		this.isMortgage = isMortgage;
		this.mortgageType = mortgageType;
		this.mortgagePeopre = mortgagePeopre;
		this.mortgageObligee = mortgageObligee;
		this.mortgageRegister = mortgageRegister;
		this.mortgageTime = mortgageTime;
		this.contract = contract;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "COMMERCI_ID", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getCommerciId() {
		return this.commerciId;
	}

	public void setCommerciId(String commerciId) {
		this.commerciId = commerciId;
	}

	@Column(name = "IS_MORTGAGE", length = 32)
	@Size(max = 32)
	public String getIsMortgage() {
		return this.isMortgage;
	}

	public void setIsMortgage(String isMortgage) {
		this.isMortgage = isMortgage;
	}

	@Column(name = "MORTGAGE_TYPE", length = 60)
	@Size(max = 60)
	public String getMortgageType() {
		return this.mortgageType;
	}

	public void setMortgageType(String mortgageType) {
		this.mortgageType = mortgageType;
	}

	@Column(name = "MORTGAGE_PEOPRE", length = 60)
	@Size(max = 60)
	public String getMortgagePeopre() {
		return this.mortgagePeopre;
	}

	public void setMortgagePeopre(String mortgagePeopre) {
		this.mortgagePeopre = mortgagePeopre;
	}

	@Column(name = "MORTGAGE_OBLIGEE", length = 100)
	@Size(max = 100)
	public String getMortgageObligee() {
		return this.mortgageObligee;
	}

	public void setMortgageObligee(String mortgageObligee) {
		this.mortgageObligee = mortgageObligee;
	}

	@Column(name = "MORTGAGE_REGISTER", length = 100)
	@Size(max = 100)
	public String getMortgageRegister() {
		return this.mortgageRegister;
	}

	public void setMortgageRegister(String mortgageRegister) {
		this.mortgageRegister = mortgageRegister;
	}

	@Column(name = "MORTGAGE_TIME", length = 100)
	@Size(max = 100)
	public String getMortgageTime() {
		return this.mortgageTime;
	}

	public void setMortgageTime(String mortgageTime) {
		this.mortgageTime = mortgageTime;
	}

	@Column(name = "CONTRACT", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

}
