package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import com.dgsoft.common.TimeArea;
import com.dgsoft.common.system.OwnerPersonEntity;
import com.dgsoft.common.system.PersonEntity;
import com.dgsoft.common.system.PowerPersonEntity;
import com.dgsoft.common.system.ProxyPersonEntity;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;

/**
 * Financial generated by hbm2java
 */
@Entity
@Table(name = "FINANCIAL", catalog = "HOUSE_OWNER_RECORD")
public class Financial implements java.io.Serializable, PersonEntity {

    public enum FinancialType{FINANCE_PERSON,FINANCE_CORP}
	private String id;
	private String name;
	private String code;
    private String phone;
    private FinancialType financialType;
    private CredentialsType credentialsType;
    private String bank;
    private Date createTime;
    private MakeCard makeCard;
    private MortgaegeRegiste mortgaegeForNew;
    private ProxyPerson proxyPerson;


	public Financial() {
	}

    public Financial(Date createTime, FinancialType financialType) {
        this.createTime = createTime;
        this.financialType = financialType;
    }

    public Financial(String name, String code, String phone, String bank) {
        this.name = name;
        this.code = code;
        this.phone = phone;
        this.bank = bank;
    }

    public Financial(Financial financial) {
        createTime = new Date();
        name = financial.getName();
        code = financial.getCode();
        phone = financial.getPhone();
        financialType = financial.getFinancialType();
        credentialsType = financial.getCredentialsType();
        bank = financial.getBank();
    }


    @Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}



	@Column(name = "NAME", nullable = false, length = 120)
	@NotNull
	@Size(max = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", nullable = true, length = 100)
	@Size(max = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

    @Column(name = "PHONE", nullable = true, length = 15)
    @Size(max = 15)
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    @Enumerated(EnumType.STRING)
    @Column(name = "ID_TYPE",nullable = true,length = 32)
    public CredentialsType getCredentialsType() {
        return credentialsType;
    }

    @Override
    public void setCredentialsType(CredentialsType credentialsType) {
        this.credentialsType = credentialsType;
    }

    @Enumerated(EnumType.STRING)
    @Column(name="FINANCIAL_TYPE",nullable = false,length = 20)
    @NotNull
    public FinancialType getFinancialType() {
        return financialType;
    }

    public void setFinancialType(FinancialType financialType) {
        this.financialType = financialType;
    }

    @Column(name = "BANK",nullable = true,length = 32)
    @Size(max = 32)
    public String getBank() {
        return bank;
    }

    public void setBank(String bank) {
        this.bank = bank;
    }


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", nullable = false, length = 19)
    @NotNull
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    @Transient
    public String getCredentialsNumber() {
        return getCode();
    }

    @Override
    @Transient
    public void setCredentialsNumber(String credentialsNumber) {
        setCode(credentialsNumber);
    }

    @Override
    @Transient
    public String getPersonName() {
        return getName();
    }

    @Override
    @Transient
    public void setPersonName(String personName) {
        setName(personName);
    }

    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "CARD",nullable = true)
    public MakeCard getMakeCard() {
        return makeCard;
    }

    public void setMakeCard(MakeCard makeCard) {
        this.makeCard = makeCard;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "financial")
    public MortgaegeRegiste getMortgaegeForNew() {
        return mortgaegeForNew;
    }

    public void setMortgaegeForNew(MortgaegeRegiste mortgaegeForNew) {
        this.mortgaegeForNew = mortgaegeForNew;
    }

    @ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
    @JoinColumn(name = "PROXY_PERSON", nullable = true)
    public ProxyPerson getProxyPerson() {
        return proxyPerson;
    }

    public void setProxyPerson(ProxyPerson proxyPerson) {
        this.proxyPerson = proxyPerson;
    }
}
