package com.dgsoft.house.owner.model;
// Generated Aug 24, 2015 1:17:35 PM by Hibernate Tools 4.0.0

import com.dgsoft.house.SaleType;
import org.hibernate.annotations.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseContract generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_CONTRACT", catalog = "HOUSE_OWNER_RECORD")
public class HouseContract implements java.io.Serializable {


	private String id;

	private String attachEmpId;
	private String attachEmpName;
	private String contractText;
	private int contractVersion;


	private Set<ContractNumber> contractNumbers = new HashSet<ContractNumber>(0);


	private String contractNumber;
	private SaleType type;
	private Date contractDate;
	private String houseCode;

	private HouseBusiness houseBusiness;

	public HouseContract() {
	}

	public HouseContract(String attachEmpId, String attachEmpName, String contractText, int contractVersion) {
		this.attachEmpId = attachEmpId;
		this.attachEmpName = attachEmpName;
		this.contractText = contractText;
		this.contractVersion = contractVersion;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	@GenericGenerator(name = "pkGenerator",
			strategy = "foreign",
			parameters = { @org.hibernate.annotations.Parameter(name = "property", value = "contractOwner") })
	@GeneratedValue(generator = "pkGenerator")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ATTACH_EMP_ID", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getAttachEmpId() {
		return attachEmpId;
	}

	public void setAttachEmpId(String attachEmpId) {
		this.attachEmpId = attachEmpId;
	}


	@Column(name = "ATTACH_EMP_NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getAttachEmpName() {
		return attachEmpName;
	}

	public void setAttachEmpName(String attachEmpName) {
		this.attachEmpName = attachEmpName;
	}

	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "CONTRACT", columnDefinition = "LONGTEXT")
	public String getContractText() {
		return contractText;
	}

	public void setContractText(String contractText) {
		this.contractText = contractText;
	}

	@Column(name = "CONTRACT_VERSION",nullable = false)
	public int getContractVersion() {
		return contractVersion;
	}

	public void setContractVersion(int contractVersion) {
		this.contractVersion = contractVersion;
	}


	@OneToMany(fetch = FetchType.LAZY,mappedBy = "houseContract",cascade = CascadeType.ALL)
	public Set<ContractNumber> getContractNumbers() {
		return contractNumbers;
	}

	public void setContractNumbers(Set<ContractNumber> contractNumbers) {
		this.contractNumbers = contractNumbers;
	}


	@Enumerated(EnumType.STRING)
	@Column(name = "TYPE", nullable = false, length = 32)
	@NotNull
	public SaleType getType() {
		return this.type;
	}

	public void setType(SaleType type) {
		this.type = type;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CONTRACT_DATE", nullable = false, length = 19)
	@NotNull
	public Date getContractDate() {
		return contractDate;
	}

	public void setContractDate(Date contractDate) {
		this.contractDate = contractDate;
	}

	@Column(name = "HOUSE_CODE", length = 32, nullable = false)
	@NotNull
	@Size(max = 32)
	public String getHouseCode() {
		return houseCode;
	}

	public void setHouseCode(String houseCode) {
		this.houseCode = houseCode;
	}

	@OneToOne(fetch = FetchType.LAZY,optional = false)
	@JoinColumn(name = "BUSINESS",nullable = false)
	public HouseBusiness getHouseBusiness() {
		return houseBusiness;
	}

	public void setHouseBusiness(HouseBusiness houseBusiness) {
		this.houseBusiness = houseBusiness;
	}

	@Column(name="CONTRACT_NUMBER", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getContractNumber() {
		return contractNumber;
	}

	public void setContractNumber(String contractNumber) {
		this.contractNumber = contractNumber;
	}
}
