package com.dgsoft.house.owner.model;
// Generated Aug 24, 2015 1:17:35 PM by Hibernate Tools 4.0.0

import com.dgsoft.house.SaleType;
import org.hibernate.annotations.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseContract generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_CONTRACT", catalog = "HOUSE_OWNER_RECORD")
public class HouseContract implements java.io.Serializable {


	private String id;

	private String contractNumber;
	private SaleType type;
	private Date contractDate;
	private String projectSaleCerNumber;
	private OwnerBusiness ownerBusiness;

	private BusinessHouse businessHouse;
	private ContractSubmit contractSubmit;

	public HouseContract() {
	}

	public HouseContract(SaleType type, OwnerBusiness ownerBusiness) {
		this.type = type;
		this.ownerBusiness = ownerBusiness;
	}

	public HouseContract(String contractNumber, SaleType type, Date contractDate, String projectSaleCerNumber, OwnerBusiness ownerBusiness, ContractSubmit contractSubmit) {
		this.contractNumber = contractNumber;
		this.type = type;
		this.contractDate = contractDate;
		this.ownerBusiness = ownerBusiness;
		this.contractSubmit = contractSubmit;
		this.projectSaleCerNumber = projectSaleCerNumber;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}



	@Enumerated(EnumType.STRING)
	@Column(name = "TYPE", nullable = false, length = 32)
	@NotNull
	public SaleType getType() {
		return this.type;
	}

	public void setType(SaleType type) {
		this.type = type;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CONTRACT_DATE", nullable = false, length = 19)
	@NotNull
	public Date getContractDate() {
		return contractDate;
	}

	public void setContractDate(Date contractDate) {
		this.contractDate = contractDate;
	}


	@OneToOne(fetch = FetchType.LAZY, mappedBy = "saleContract")
	public BusinessHouse getBusinessHouse() {
		return businessHouse;
	}

	public void setBusinessHouse(BusinessHouse businessHouse) {
		this.businessHouse = businessHouse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS",nullable = false)
	@NotNull
	public OwnerBusiness getOwnerBusiness() {
		return ownerBusiness;
	}

	public void setOwnerBusiness(OwnerBusiness ownerBusiness) {
		this.ownerBusiness = ownerBusiness;
	}

	@Column(name="CONTRACT_NUMBER", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getContractNumber() {
		return contractNumber;
	}

	public void setContractNumber(String contractNumber) {
		this.contractNumber = contractNumber;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@PrimaryKeyJoinColumn
	public ContractSubmit getContractSubmit() {
		return contractSubmit;
	}

	public void setContractSubmit(ContractSubmit contractSubmit) {
		this.contractSubmit = contractSubmit;
	}

	@Column(name = "PROJECT_RSHIP_NUMBER", length = 50)
	@Size(max = 50)
	public String getProjectSaleCerNumber() {
		return projectSaleCerNumber;
	}

	public void setProjectSaleCerNumber(String projectSaleCerNumber) {
		this.projectSaleCerNumber = projectSaleCerNumber;
	}
}
