package com.dgsoft.house.owner.model;
// Generated Oct 11, 2014 3:13:15 PM by Hibernate Tools 4.0.0

import com.dgsoft.common.system.RunParam;
import com.dgsoft.house.HouseInfo;

import java.math.BigDecimal;
import java.util.*;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseRecord generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_RECORD", catalog = "HOUSE_OWNER_RECORD", uniqueConstraints = {
		@UniqueConstraint(columnNames = "HOUSE_CODE"),
		@UniqueConstraint(columnNames = "HOUSE")})
public class HouseRecord implements java.io.Serializable {

	private BusinessHouse businessHouse;
	private String houseCode;
	private Set<RecordStore> recordStores = new HashSet<RecordStore>(0);

	public HouseRecord() {
	}
    public HouseRecord(BusinessHouse businessHouse){
       this.businessHouse = businessHouse;
       this.houseCode = businessHouse.getHouseCode();
    }


	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HOUSE", unique = true, nullable = false)
	@NotNull
	public BusinessHouse getBusinessHouse() {
		return this.businessHouse;
	}

	public void setBusinessHouse(BusinessHouse businessHouse) {
		this.businessHouse = businessHouse;
	}

    @Id
	@Column(name = "HOUSE_CODE", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getHouseCode() {
		return this.houseCode;
	}

    public void setHouseCode(String houseCode) {
        this.houseCode = houseCode;
    }


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "houseRecord")
	public Set<RecordStore> getRecordStores() {
		return this.recordStores;
	}

	public void setRecordStores(Set<RecordStore> recordStores) {
		this.recordStores = recordStores;
	}



}
