package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import org.hibernate.annotations.GenericGenerator;

import java.util.Date;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseCloseCancel generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_CLOSE_CANCEL", catalog = "HOUSE_OWNER_RECORD")
public class HouseCloseCancel implements java.io.Serializable {

	private String id;
	private HouseBusiness houseBusiness;
	private Date cancelDate;

	public HouseCloseCancel() {
	}

	public HouseCloseCancel(String id, HouseBusiness houseBusiness,
			Date cancelDate) {
		this.id = id;
		this.houseBusiness = houseBusiness;
		this.cancelDate = cancelDate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_ID", nullable = false)
	@NotNull
	public HouseBusiness getHouseBusiness() {
		return this.houseBusiness;
	}

	public void setHouseBusiness(HouseBusiness houseBusiness) {
		this.houseBusiness = houseBusiness;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CANCEL_DATE", nullable = false, length = 19)
	@NotNull
	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}

}
