package com.dgsoft.house.owner.model;
// Generated Oct 11, 2014 3:13:15 PM by Hibernate Tools 4.0.0

import com.dgsoft.house.HouseInfo;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseState generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_STATE", catalog = "HOUSE_OWNER_RECORD")
public class HouseState implements java.io.Serializable {

	private String id;
	private BusinessHouse businessHouse;
	private HouseInfo.HouseStatus state;

	public HouseState() {
	}

	public HouseState(BusinessHouse businessHouse, HouseInfo.HouseStatus state) {
		this.businessHouse = businessHouse;
		this.state = state;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HOUSE", nullable = false)
	@NotNull
	public BusinessHouse getBusinessHouse() {
		return this.businessHouse;
	}

	public void setBusinessHouse(BusinessHouse businessHouse) {
		this.businessHouse = businessHouse;
	}


    @Enumerated(EnumType.STRING)
	@Column(name = "HOUSE_STATUS", nullable = false, length = 32)
	@NotNull
	public HouseInfo.HouseStatus getState() {
		return this.state;
	}

	public void setState(HouseInfo.HouseStatus state) {
		this.state = state;
	}

}
