package com.dgsoft.house.owner.model;
// Generated Aug 24, 2015 1:17:35 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseCommerciContract generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_COMMERCI_CONTRACT", catalog = "HOUSE_OWNER_RECORD", uniqueConstraints = @UniqueConstraint(columnNames = "XMJSYJ_TDQZH"))
public class HouseCommerciContract implements java.io.Serializable {

	private String id;
	private String commerciType;
	private String htdsrCmr;
	private String htdsrCmrDz;
	private String htdsrCmrYb;
	private String htdsrCmrYyzz;
	private String htdsrCmrQyzsh;
	private String htdsrCmrFddbr;
	private String htdsrCmrFddbrdh;
	private String htdsrCmrWtdlr;
	private String htdsrCmrWtdlrdh;
	private String xmjsyjTdqdfs;
	private byte[] xmjsyjTdzl;
	private String xmjsyjTdsqqqlx;
	private String xmjsyjTdqzh;
	private BigDecimal xmjsyjTdmj;
	private String xmjsyjTdyt;
	private Date xmjsyjTdsyqzzsj;
	private String xmjsyjXmmc;
	private String xmjsyjJsgcghxkzh;
	private String xmjsyjJzgcsgxukzh;
	private String spfjbqkFwsjyt;
	private String spfjbqkFwjg;
	private int spfjbqkFwjzzcs;
	private int spfjbqkFwjzdscs;
	private int spfjbqkFwjzdxcs;
	private String spfjbqkZh;
	private String spfjbqkZuohao;
	private String spfjbqkDyh;
	private String spfjbqkCh;
	private String spfjbqkChjg;
	private BigDecimal spfjbqkJzmj;
	private BigDecimal spfjbqkTnmj;
	private BigDecimal spfjbqkFtmj;
	private BigDecimal cgw;
	private int ygyt;
	private int yjgfbyt;
	private int fbytgs;
	private String fwqlzkqn4;
	private String fwqlzkqn5;
	private String az;
	private String fwqlzkcnCffs;
	private Integer djz;
	private String tnmjBz1;
	private BigDecimal tnmjY1;
	private String tnmjZjkbz1;
	private BigDecimal tnmjZjk1;
	private String tnmjZjkdx1;
	private String jzmjBz2;
	private BigDecimal jzmjY2;
	private String jzmjZjkbz2;
	private BigDecimal jzmjZjk2;
	private String zjkdx2;
	private String TBz3;
	private BigDecimal TZjk3;
	private String TZjkdx3;
	private String qtAzjs;
	private String qtBz4;
	private BigDecimal qtZjk4;
	private String qtZjkdx4;
	private String fkfsjqxBz1;
	private String fkfsjqxZjk1;
	private String fkfsjqxDjjffs;
	private String fkfsjqxDyspfjk;
	private Integer djzfkfs;
	private Date ycxfkYcxfksj;
	private Date fqfkFqfksj;
	private Integer fqfkFjq;
	private String fqfkSqfjkbz;
	private BigDecimal fqfkSqfjky;
	private String fqfkSqfjkdx;
	private Date fqfkYdy;
	private String fqfkYdybz;
	private String dkfsDkfs;
	private Date dkfsMsrsfsj;
	private String dkfsDksfbz;
	private BigDecimal dkfsDksfy;
	private String dkfsDksfkdx;
	private String dkfsZqbfkbfb;
	private String dkfsYkbz;
	private BigDecimal dkfsYk;
	private String dkfsYkdx;
	private String dkfsDkjg;
	private String fkqtfs;
	private Integer yqfkzefs;
	private Integer yqjr1;
	private BigDecimal yfkwfzj1;
	private Integer yqfkzrYqcgjr;
	private Integer sdzrq;
	private BigDecimal yfkbfb;
	private BigDecimal yfkwfzj2;
	private String yqfkzrbz2;
	private Integer fhtj3;
	private Integer fhtj4;
	private String fhtjmemo3;
	private String fhtjmemo4;
	private String jcsssb1;
	private String jcsssb2;
	private String jcsssb3;
	private String jcsssb4;
	private Integer azxldjzcl;
	private BigDecimal zfwyj5;
	private BigDecimal zfwyj6;
	private BigDecimal zfwyj7;
	private Integer ydjfrhdjr;
	private String jfsytjmemo2;
	private Date ldlsj;
	private String ldlmemo;
	private Date szdlsj;
	private String szdlsjmemo;
	private Date ghdcwsj;
	private String ghdcwmemo;
	private Date wyfwyf;
	private String wyfwyfmemo;
	private Date ylwsjg;
	private String ylwsjgmemo;
	private Date yey;
	private String yeymemo;
	private Date xx;
	private String xxmemo;
	private String ggfwjpt8;
	private String ggfwjpt9;
	private String xqldpcsm;
	private String fszdlpcsm;
	private String cwckpcsm;
	private String wyfwyfsm;
	private String qtsswddsm;
	private Date cmrjhsh;
	private Integer jmq;
	private String jfsjhsx2;
	private Integer cycrq;
	private String cyfwbz5;
	private String cyfwbz6;
	private String cyfwbz7;
	private String cyfwbz8;
	private Integer yqjfclfs;
	private Integer yqzdjrzn;
	private BigDecimal wfzj1;
	private Integer yqcgjr;
	private BigDecimal yqcgazbfb2;
	private BigDecimal fjkdbfb2;
	private BigDecimal fjkwfzj2;
	private String yqjfzr2bz;
	private BigDecimal spfzljbxzrBfb1;
	private String spfzljbxzrMemo1;
	private String spfzljbxzrMemo2;
	private BigDecimal spfzljbxzrBfb2;
	private String spfzljbxzrQtMemo3;
	private Integer spfzljbxzrZxbz2;
	private Integer spfzljbxzrZxbz3;
	private String spfzljbxzrMemo3;
	private String spfzljbxzrMemo4;
	private String spfzljbxzrKqzlbz;
	private byte[] spfzljbxzrKqbzmc;
	private String spfzljbxzrKqbzwh;
	private String spfzljbxzrGybz;
	private BigDecimal spfzljbxzrAz;
	private String spfzljbxzrMemo5;
	private byte[] spfzljbxzrBxzeMemo6;
	private Integer spfzljbxzrBxzeHmrr;
	private String spfzljbxzrZldbY;
	private String htbayfwdjQqwyglMc;
	private Date htbayfwdjQqwyglFwsjq;
	private Date htbayfwdjQqwyglFwsjz;
	private String htbayfwdjQqwyglWyjffs;
	private BigDecimal htbayfwdjQqwyglMywyf;
	private String qtsxJzwqfsyqMemo1;
	private String qtsxJzwqfsyqCkcw;
	private String qtsxJzwqfsyqHs;
	private String qtsxJzwqfsyqMemo3;
	private String qtsxSxhsyqcnMemo6;
	private String qtsxSxhsyqcnMemo7;
	private String qtsxSdFs;
	private Integer qtsxSdBgzr;
	private Integer qtsxZyjjfsFsjw;
	private String qtsxZyjjfsZcwyhmc;
	private Integer qtsxHtsxBhtys;
	private Integer qtsxHtsxHtfs;
	private Integer qtsxHtsxCmrfs;
	private Integer qtsxHtsxMsrfs;
	private Integer qtsxHtsxMc1;
	private Integer qtsxHtsxFs1;
	private Integer qtsxHtsxMc2;
	private Integer qtsxHtsxFs2;
	private Date qdsj;
	private String qddd;
	private String zszxjxgsbWq;
	private String zszxjxgsbWqbz;
	private String zszxjxgsbQjsNq;
	private String zszxjxgsbQjsDp;
	private String zszxjxgsbQjsDpbz;
	private String zszxjxgsbQjsSndm;
	private String zszxjxgsbQjsSndmbz;
	private String zszxjxgsbCfDm;
	private String zszxjxgsbCfDmbz;
	private String zszxjxgsbCfQm;
	private String zszxjxgsbCfQmbz;
	private String zszxjxgsbCfDp;
	private String zszxjxgsbCfDpbz;
	private String zszxjxgsbCfCj;
	private String zszxjxgsbWsjDm;
	private byte[] zszxjxgsbWsjDmbz;
	private String zszxjxgsbWsjQm;
	private String zszxjxgsbWsjQmbz;
	private String zszxjxgsbWsjDp;
	private String zszxjxgsbWsjDpbz;
	private String zszxjxgsbWsjQj;
	private String zszxjxgsbYt;
	private String zszxjxgsbYtbz;
	private String zszxjxgsbDtPp;
	private String zszxjxgsbDtXh;
	private String zszxjxgsbGd;
	private String zszxjxgsbCh;
	private String zszxjxgsbBz9;
	private String zszxjxgsbBz10;
	private String bxfwqxzrDjjchztjgBxqx;
	private String bxfwqxzrDjjchztjgBxqxbz;
	private String bxfwqxzrFsgcBxqx;
	private String bxfwqxzrFsgcBxqxbz;
	private String bxfwqxzrGlgrBxqx;
	private String bxfwqxzrGlgrBxqxbz;
	private String bxfwqxzrDxgxBxqx;
	private String bxfwqxzrDxgxBxqxbz;
	private String bxfwqxzrZxgcBxqx;
	private String bxfwqxzrZxgcBxqxbz;
	private String bxfwqxzrMemo6;
	private String bxfwqxzrMemo7;
	private String bxfwqxzrMemo8;
	private String bxfwqxzrQtyd;

	public HouseCommerciContract() {
	}

	public HouseCommerciContract(String id, String commerciType,
			String htdsrCmr, String htdsrCmrDz, String htdsrCmrYyzz,
			String htdsrCmrQyzsh, String htdsrCmrFddbr, String htdsrCmrFddbrdh,
			String xmjsyjTdqdfs, byte[] xmjsyjTdzl, String xmjsyjTdsqqqlx,
			String xmjsyjTdqzh, BigDecimal xmjsyjTdmj, String xmjsyjTdyt,
			Date xmjsyjTdsyqzzsj, String xmjsyjXmmc, String xmjsyjJsgcghxkzh,
			String xmjsyjJzgcsgxukzh, String spfjbqkFwsjyt, String spfjbqkFwjg,
			int spfjbqkFwjzzcs, int spfjbqkFwjzdscs, int spfjbqkFwjzdxcs,
			String spfjbqkZh, String spfjbqkDyh, String spfjbqkCh,
			String spfjbqkChjg, BigDecimal spfjbqkJzmj, BigDecimal spfjbqkTnmj,
			BigDecimal spfjbqkFtmj, BigDecimal cgw, int ygyt, int yjgfbyt,
			int fbytgs, Date ycxfkYcxfksj, Date fqfkFqfksj, Date fqfkYdy,
			Date dkfsMsrsfsj, Date ldlsj, Date szdlsj, Date ghdcwsj,
			Date wyfwyf, Date ylwsjg, Date yey, Date xx, Date cmrjhsh,
			Date htbayfwdjQqwyglFwsjq, Date htbayfwdjQqwyglFwsjz, Date qdsj) {
		this.id = id;
		this.commerciType = commerciType;
		this.htdsrCmr = htdsrCmr;
		this.htdsrCmrDz = htdsrCmrDz;
		this.htdsrCmrYyzz = htdsrCmrYyzz;
		this.htdsrCmrQyzsh = htdsrCmrQyzsh;
		this.htdsrCmrFddbr = htdsrCmrFddbr;
		this.htdsrCmrFddbrdh = htdsrCmrFddbrdh;
		this.xmjsyjTdqdfs = xmjsyjTdqdfs;
		this.xmjsyjTdzl = xmjsyjTdzl;
		this.xmjsyjTdsqqqlx = xmjsyjTdsqqqlx;
		this.xmjsyjTdqzh = xmjsyjTdqzh;
		this.xmjsyjTdmj = xmjsyjTdmj;
		this.xmjsyjTdyt = xmjsyjTdyt;
		this.xmjsyjTdsyqzzsj = xmjsyjTdsyqzzsj;
		this.xmjsyjXmmc = xmjsyjXmmc;
		this.xmjsyjJsgcghxkzh = xmjsyjJsgcghxkzh;
		this.xmjsyjJzgcsgxukzh = xmjsyjJzgcsgxukzh;
		this.spfjbqkFwsjyt = spfjbqkFwsjyt;
		this.spfjbqkFwjg = spfjbqkFwjg;
		this.spfjbqkFwjzzcs = spfjbqkFwjzzcs;
		this.spfjbqkFwjzdscs = spfjbqkFwjzdscs;
		this.spfjbqkFwjzdxcs = spfjbqkFwjzdxcs;
		this.spfjbqkZh = spfjbqkZh;
		this.spfjbqkDyh = spfjbqkDyh;
		this.spfjbqkCh = spfjbqkCh;
		this.spfjbqkChjg = spfjbqkChjg;
		this.spfjbqkJzmj = spfjbqkJzmj;
		this.spfjbqkTnmj = spfjbqkTnmj;
		this.spfjbqkFtmj = spfjbqkFtmj;
		this.cgw = cgw;
		this.ygyt = ygyt;
		this.yjgfbyt = yjgfbyt;
		this.fbytgs = fbytgs;
		this.ycxfkYcxfksj = ycxfkYcxfksj;
		this.fqfkFqfksj = fqfkFqfksj;
		this.fqfkYdy = fqfkYdy;
		this.dkfsMsrsfsj = dkfsMsrsfsj;
		this.ldlsj = ldlsj;
		this.szdlsj = szdlsj;
		this.ghdcwsj = ghdcwsj;
		this.wyfwyf = wyfwyf;
		this.ylwsjg = ylwsjg;
		this.yey = yey;
		this.xx = xx;
		this.cmrjhsh = cmrjhsh;
		this.htbayfwdjQqwyglFwsjq = htbayfwdjQqwyglFwsjq;
		this.htbayfwdjQqwyglFwsjz = htbayfwdjQqwyglFwsjz;
		this.qdsj = qdsj;
	}
	public HouseCommerciContract(String id, String commerciType,
			String htdsrCmr, String htdsrCmrDz, String htdsrCmrYb,
			String htdsrCmrYyzz, String htdsrCmrQyzsh, String htdsrCmrFddbr,
			String htdsrCmrFddbrdh, String htdsrCmrWtdlr,
			String htdsrCmrWtdlrdh, String xmjsyjTdqdfs, byte[] xmjsyjTdzl,
			String xmjsyjTdsqqqlx, String xmjsyjTdqzh, BigDecimal xmjsyjTdmj,
			String xmjsyjTdyt, Date xmjsyjTdsyqzzsj, String xmjsyjXmmc,
			String xmjsyjJsgcghxkzh, String xmjsyjJzgcsgxukzh,
			String spfjbqkFwsjyt, String spfjbqkFwjg, int spfjbqkFwjzzcs,
			int spfjbqkFwjzdscs, int spfjbqkFwjzdxcs, String spfjbqkZh,
			String spfjbqkZuohao, String spfjbqkDyh, String spfjbqkCh,
			String spfjbqkChjg, BigDecimal spfjbqkJzmj, BigDecimal spfjbqkTnmj,
			BigDecimal spfjbqkFtmj, BigDecimal cgw, int ygyt, int yjgfbyt,
			int fbytgs, String fwqlzkqn4, String fwqlzkqn5, String az,
			String fwqlzkcnCffs, Integer djz, String tnmjBz1,
			BigDecimal tnmjY1, String tnmjZjkbz1, BigDecimal tnmjZjk1,
			String tnmjZjkdx1, String jzmjBz2, BigDecimal jzmjY2,
			String jzmjZjkbz2, BigDecimal jzmjZjk2, String zjkdx2, String TBz3,
			BigDecimal TZjk3, String TZjkdx3, String qtAzjs, String qtBz4,
			BigDecimal qtZjk4, String qtZjkdx4, String fkfsjqxBz1,
			String fkfsjqxZjk1, String fkfsjqxDjjffs, String fkfsjqxDyspfjk,
			Integer djzfkfs, Date ycxfkYcxfksj, Date fqfkFqfksj,
			Integer fqfkFjq, String fqfkSqfjkbz, BigDecimal fqfkSqfjky,
			String fqfkSqfjkdx, Date fqfkYdy, String fqfkYdybz,
			String dkfsDkfs, Date dkfsMsrsfsj, String dkfsDksfbz,
			BigDecimal dkfsDksfy, String dkfsDksfkdx, String dkfsZqbfkbfb,
			String dkfsYkbz, BigDecimal dkfsYk, String dkfsYkdx,
			String dkfsDkjg, String fkqtfs, Integer yqfkzefs, Integer yqjr1,
			BigDecimal yfkwfzj1, Integer yqfkzrYqcgjr, Integer sdzrq,
			BigDecimal yfkbfb, BigDecimal yfkwfzj2, String yqfkzrbz2,
			Integer fhtj3, Integer fhtj4, String fhtjmemo3, String fhtjmemo4,
			String jcsssb1, String jcsssb2, String jcsssb3, String jcsssb4,
			Integer azxldjzcl, BigDecimal zfwyj5, BigDecimal zfwyj6,
			BigDecimal zfwyj7, Integer ydjfrhdjr, String jfsytjmemo2,
			Date ldlsj, String ldlmemo, Date szdlsj, String szdlsjmemo,
			Date ghdcwsj, String ghdcwmemo, Date wyfwyf, String wyfwyfmemo,
			Date ylwsjg, String ylwsjgmemo, Date yey, String yeymemo, Date xx,
			String xxmemo, String ggfwjpt8, String ggfwjpt9, String xqldpcsm,
			String fszdlpcsm, String cwckpcsm, String wyfwyfsm,
			String qtsswddsm, Date cmrjhsh, Integer jmq, String jfsjhsx2,
			Integer cycrq, String cyfwbz5, String cyfwbz6, String cyfwbz7,
			String cyfwbz8, Integer yqjfclfs, Integer yqzdjrzn,
			BigDecimal wfzj1, Integer yqcgjr, BigDecimal yqcgazbfb2,
			BigDecimal fjkdbfb2, BigDecimal fjkwfzj2, String yqjfzr2bz,
			BigDecimal spfzljbxzrBfb1, String spfzljbxzrMemo1,
			String spfzljbxzrMemo2, BigDecimal spfzljbxzrBfb2,
			String spfzljbxzrQtMemo3, Integer spfzljbxzrZxbz2,
			Integer spfzljbxzrZxbz3, String spfzljbxzrMemo3,
			String spfzljbxzrMemo4, String spfzljbxzrKqzlbz,
			byte[] spfzljbxzrKqbzmc, String spfzljbxzrKqbzwh,
			String spfzljbxzrGybz, BigDecimal spfzljbxzrAz,
			String spfzljbxzrMemo5, byte[] spfzljbxzrBxzeMemo6,
			Integer spfzljbxzrBxzeHmrr, String spfzljbxzrZldbY,
			String htbayfwdjQqwyglMc, Date htbayfwdjQqwyglFwsjq,
			Date htbayfwdjQqwyglFwsjz, String htbayfwdjQqwyglWyjffs,
			BigDecimal htbayfwdjQqwyglMywyf, String qtsxJzwqfsyqMemo1,
			String qtsxJzwqfsyqCkcw, String qtsxJzwqfsyqHs,
			String qtsxJzwqfsyqMemo3, String qtsxSxhsyqcnMemo6,
			String qtsxSxhsyqcnMemo7, String qtsxSdFs, Integer qtsxSdBgzr,
			Integer qtsxZyjjfsFsjw, String qtsxZyjjfsZcwyhmc,
			Integer qtsxHtsxBhtys, Integer qtsxHtsxHtfs, Integer qtsxHtsxCmrfs,
			Integer qtsxHtsxMsrfs, Integer qtsxHtsxMc1, Integer qtsxHtsxFs1,
			Integer qtsxHtsxMc2, Integer qtsxHtsxFs2, Date qdsj, String qddd,
			String zszxjxgsbWq, String zszxjxgsbWqbz, String zszxjxgsbQjsNq,
			String zszxjxgsbQjsDp, String zszxjxgsbQjsDpbz,
			String zszxjxgsbQjsSndm, String zszxjxgsbQjsSndmbz,
			String zszxjxgsbCfDm, String zszxjxgsbCfDmbz, String zszxjxgsbCfQm,
			String zszxjxgsbCfQmbz, String zszxjxgsbCfDp,
			String zszxjxgsbCfDpbz, String zszxjxgsbCfCj,
			String zszxjxgsbWsjDm, byte[] zszxjxgsbWsjDmbz,
			String zszxjxgsbWsjQm, String zszxjxgsbWsjQmbz,
			String zszxjxgsbWsjDp, String zszxjxgsbWsjDpbz,
			String zszxjxgsbWsjQj, String zszxjxgsbYt, String zszxjxgsbYtbz,
			String zszxjxgsbDtPp, String zszxjxgsbDtXh, String zszxjxgsbGd,
			String zszxjxgsbCh, String zszxjxgsbBz9, String zszxjxgsbBz10,
			String bxfwqxzrDjjchztjgBxqx, String bxfwqxzrDjjchztjgBxqxbz,
			String bxfwqxzrFsgcBxqx, String bxfwqxzrFsgcBxqxbz,
			String bxfwqxzrGlgrBxqx, String bxfwqxzrGlgrBxqxbz,
			String bxfwqxzrDxgxBxqx, String bxfwqxzrDxgxBxqxbz,
			String bxfwqxzrZxgcBxqx, String bxfwqxzrZxgcBxqxbz,
			String bxfwqxzrMemo6, String bxfwqxzrMemo7, String bxfwqxzrMemo8,
			String bxfwqxzrQtyd) {
		this.id = id;
		this.commerciType = commerciType;
		this.htdsrCmr = htdsrCmr;
		this.htdsrCmrDz = htdsrCmrDz;
		this.htdsrCmrYb = htdsrCmrYb;
		this.htdsrCmrYyzz = htdsrCmrYyzz;
		this.htdsrCmrQyzsh = htdsrCmrQyzsh;
		this.htdsrCmrFddbr = htdsrCmrFddbr;
		this.htdsrCmrFddbrdh = htdsrCmrFddbrdh;
		this.htdsrCmrWtdlr = htdsrCmrWtdlr;
		this.htdsrCmrWtdlrdh = htdsrCmrWtdlrdh;
		this.xmjsyjTdqdfs = xmjsyjTdqdfs;
		this.xmjsyjTdzl = xmjsyjTdzl;
		this.xmjsyjTdsqqqlx = xmjsyjTdsqqqlx;
		this.xmjsyjTdqzh = xmjsyjTdqzh;
		this.xmjsyjTdmj = xmjsyjTdmj;
		this.xmjsyjTdyt = xmjsyjTdyt;
		this.xmjsyjTdsyqzzsj = xmjsyjTdsyqzzsj;
		this.xmjsyjXmmc = xmjsyjXmmc;
		this.xmjsyjJsgcghxkzh = xmjsyjJsgcghxkzh;
		this.xmjsyjJzgcsgxukzh = xmjsyjJzgcsgxukzh;
		this.spfjbqkFwsjyt = spfjbqkFwsjyt;
		this.spfjbqkFwjg = spfjbqkFwjg;
		this.spfjbqkFwjzzcs = spfjbqkFwjzzcs;
		this.spfjbqkFwjzdscs = spfjbqkFwjzdscs;
		this.spfjbqkFwjzdxcs = spfjbqkFwjzdxcs;
		this.spfjbqkZh = spfjbqkZh;
		this.spfjbqkZuohao = spfjbqkZuohao;
		this.spfjbqkDyh = spfjbqkDyh;
		this.spfjbqkCh = spfjbqkCh;
		this.spfjbqkChjg = spfjbqkChjg;
		this.spfjbqkJzmj = spfjbqkJzmj;
		this.spfjbqkTnmj = spfjbqkTnmj;
		this.spfjbqkFtmj = spfjbqkFtmj;
		this.cgw = cgw;
		this.ygyt = ygyt;
		this.yjgfbyt = yjgfbyt;
		this.fbytgs = fbytgs;
		this.fwqlzkqn4 = fwqlzkqn4;
		this.fwqlzkqn5 = fwqlzkqn5;
		this.az = az;
		this.fwqlzkcnCffs = fwqlzkcnCffs;
		this.djz = djz;
		this.tnmjBz1 = tnmjBz1;
		this.tnmjY1 = tnmjY1;
		this.tnmjZjkbz1 = tnmjZjkbz1;
		this.tnmjZjk1 = tnmjZjk1;
		this.tnmjZjkdx1 = tnmjZjkdx1;
		this.jzmjBz2 = jzmjBz2;
		this.jzmjY2 = jzmjY2;
		this.jzmjZjkbz2 = jzmjZjkbz2;
		this.jzmjZjk2 = jzmjZjk2;
		this.zjkdx2 = zjkdx2;
		this.TBz3 = TBz3;
		this.TZjk3 = TZjk3;
		this.TZjkdx3 = TZjkdx3;
		this.qtAzjs = qtAzjs;
		this.qtBz4 = qtBz4;
		this.qtZjk4 = qtZjk4;
		this.qtZjkdx4 = qtZjkdx4;
		this.fkfsjqxBz1 = fkfsjqxBz1;
		this.fkfsjqxZjk1 = fkfsjqxZjk1;
		this.fkfsjqxDjjffs = fkfsjqxDjjffs;
		this.fkfsjqxDyspfjk = fkfsjqxDyspfjk;
		this.djzfkfs = djzfkfs;
		this.ycxfkYcxfksj = ycxfkYcxfksj;
		this.fqfkFqfksj = fqfkFqfksj;
		this.fqfkFjq = fqfkFjq;
		this.fqfkSqfjkbz = fqfkSqfjkbz;
		this.fqfkSqfjky = fqfkSqfjky;
		this.fqfkSqfjkdx = fqfkSqfjkdx;
		this.fqfkYdy = fqfkYdy;
		this.fqfkYdybz = fqfkYdybz;
		this.dkfsDkfs = dkfsDkfs;
		this.dkfsMsrsfsj = dkfsMsrsfsj;
		this.dkfsDksfbz = dkfsDksfbz;
		this.dkfsDksfy = dkfsDksfy;
		this.dkfsDksfkdx = dkfsDksfkdx;
		this.dkfsZqbfkbfb = dkfsZqbfkbfb;
		this.dkfsYkbz = dkfsYkbz;
		this.dkfsYk = dkfsYk;
		this.dkfsYkdx = dkfsYkdx;
		this.dkfsDkjg = dkfsDkjg;
		this.fkqtfs = fkqtfs;
		this.yqfkzefs = yqfkzefs;
		this.yqjr1 = yqjr1;
		this.yfkwfzj1 = yfkwfzj1;
		this.yqfkzrYqcgjr = yqfkzrYqcgjr;
		this.sdzrq = sdzrq;
		this.yfkbfb = yfkbfb;
		this.yfkwfzj2 = yfkwfzj2;
		this.yqfkzrbz2 = yqfkzrbz2;
		this.fhtj3 = fhtj3;
		this.fhtj4 = fhtj4;
		this.fhtjmemo3 = fhtjmemo3;
		this.fhtjmemo4 = fhtjmemo4;
		this.jcsssb1 = jcsssb1;
		this.jcsssb2 = jcsssb2;
		this.jcsssb3 = jcsssb3;
		this.jcsssb4 = jcsssb4;
		this.azxldjzcl = azxldjzcl;
		this.zfwyj5 = zfwyj5;
		this.zfwyj6 = zfwyj6;
		this.zfwyj7 = zfwyj7;
		this.ydjfrhdjr = ydjfrhdjr;
		this.jfsytjmemo2 = jfsytjmemo2;
		this.ldlsj = ldlsj;
		this.ldlmemo = ldlmemo;
		this.szdlsj = szdlsj;
		this.szdlsjmemo = szdlsjmemo;
		this.ghdcwsj = ghdcwsj;
		this.ghdcwmemo = ghdcwmemo;
		this.wyfwyf = wyfwyf;
		this.wyfwyfmemo = wyfwyfmemo;
		this.ylwsjg = ylwsjg;
		this.ylwsjgmemo = ylwsjgmemo;
		this.yey = yey;
		this.yeymemo = yeymemo;
		this.xx = xx;
		this.xxmemo = xxmemo;
		this.ggfwjpt8 = ggfwjpt8;
		this.ggfwjpt9 = ggfwjpt9;
		this.xqldpcsm = xqldpcsm;
		this.fszdlpcsm = fszdlpcsm;
		this.cwckpcsm = cwckpcsm;
		this.wyfwyfsm = wyfwyfsm;
		this.qtsswddsm = qtsswddsm;
		this.cmrjhsh = cmrjhsh;
		this.jmq = jmq;
		this.jfsjhsx2 = jfsjhsx2;
		this.cycrq = cycrq;
		this.cyfwbz5 = cyfwbz5;
		this.cyfwbz6 = cyfwbz6;
		this.cyfwbz7 = cyfwbz7;
		this.cyfwbz8 = cyfwbz8;
		this.yqjfclfs = yqjfclfs;
		this.yqzdjrzn = yqzdjrzn;
		this.wfzj1 = wfzj1;
		this.yqcgjr = yqcgjr;
		this.yqcgazbfb2 = yqcgazbfb2;
		this.fjkdbfb2 = fjkdbfb2;
		this.fjkwfzj2 = fjkwfzj2;
		this.yqjfzr2bz = yqjfzr2bz;
		this.spfzljbxzrBfb1 = spfzljbxzrBfb1;
		this.spfzljbxzrMemo1 = spfzljbxzrMemo1;
		this.spfzljbxzrMemo2 = spfzljbxzrMemo2;
		this.spfzljbxzrBfb2 = spfzljbxzrBfb2;
		this.spfzljbxzrQtMemo3 = spfzljbxzrQtMemo3;
		this.spfzljbxzrZxbz2 = spfzljbxzrZxbz2;
		this.spfzljbxzrZxbz3 = spfzljbxzrZxbz3;
		this.spfzljbxzrMemo3 = spfzljbxzrMemo3;
		this.spfzljbxzrMemo4 = spfzljbxzrMemo4;
		this.spfzljbxzrKqzlbz = spfzljbxzrKqzlbz;
		this.spfzljbxzrKqbzmc = spfzljbxzrKqbzmc;
		this.spfzljbxzrKqbzwh = spfzljbxzrKqbzwh;
		this.spfzljbxzrGybz = spfzljbxzrGybz;
		this.spfzljbxzrAz = spfzljbxzrAz;
		this.spfzljbxzrMemo5 = spfzljbxzrMemo5;
		this.spfzljbxzrBxzeMemo6 = spfzljbxzrBxzeMemo6;
		this.spfzljbxzrBxzeHmrr = spfzljbxzrBxzeHmrr;
		this.spfzljbxzrZldbY = spfzljbxzrZldbY;
		this.htbayfwdjQqwyglMc = htbayfwdjQqwyglMc;
		this.htbayfwdjQqwyglFwsjq = htbayfwdjQqwyglFwsjq;
		this.htbayfwdjQqwyglFwsjz = htbayfwdjQqwyglFwsjz;
		this.htbayfwdjQqwyglWyjffs = htbayfwdjQqwyglWyjffs;
		this.htbayfwdjQqwyglMywyf = htbayfwdjQqwyglMywyf;
		this.qtsxJzwqfsyqMemo1 = qtsxJzwqfsyqMemo1;
		this.qtsxJzwqfsyqCkcw = qtsxJzwqfsyqCkcw;
		this.qtsxJzwqfsyqHs = qtsxJzwqfsyqHs;
		this.qtsxJzwqfsyqMemo3 = qtsxJzwqfsyqMemo3;
		this.qtsxSxhsyqcnMemo6 = qtsxSxhsyqcnMemo6;
		this.qtsxSxhsyqcnMemo7 = qtsxSxhsyqcnMemo7;
		this.qtsxSdFs = qtsxSdFs;
		this.qtsxSdBgzr = qtsxSdBgzr;
		this.qtsxZyjjfsFsjw = qtsxZyjjfsFsjw;
		this.qtsxZyjjfsZcwyhmc = qtsxZyjjfsZcwyhmc;
		this.qtsxHtsxBhtys = qtsxHtsxBhtys;
		this.qtsxHtsxHtfs = qtsxHtsxHtfs;
		this.qtsxHtsxCmrfs = qtsxHtsxCmrfs;
		this.qtsxHtsxMsrfs = qtsxHtsxMsrfs;
		this.qtsxHtsxMc1 = qtsxHtsxMc1;
		this.qtsxHtsxFs1 = qtsxHtsxFs1;
		this.qtsxHtsxMc2 = qtsxHtsxMc2;
		this.qtsxHtsxFs2 = qtsxHtsxFs2;
		this.qdsj = qdsj;
		this.qddd = qddd;
		this.zszxjxgsbWq = zszxjxgsbWq;
		this.zszxjxgsbWqbz = zszxjxgsbWqbz;
		this.zszxjxgsbQjsNq = zszxjxgsbQjsNq;
		this.zszxjxgsbQjsDp = zszxjxgsbQjsDp;
		this.zszxjxgsbQjsDpbz = zszxjxgsbQjsDpbz;
		this.zszxjxgsbQjsSndm = zszxjxgsbQjsSndm;
		this.zszxjxgsbQjsSndmbz = zszxjxgsbQjsSndmbz;
		this.zszxjxgsbCfDm = zszxjxgsbCfDm;
		this.zszxjxgsbCfDmbz = zszxjxgsbCfDmbz;
		this.zszxjxgsbCfQm = zszxjxgsbCfQm;
		this.zszxjxgsbCfQmbz = zszxjxgsbCfQmbz;
		this.zszxjxgsbCfDp = zszxjxgsbCfDp;
		this.zszxjxgsbCfDpbz = zszxjxgsbCfDpbz;
		this.zszxjxgsbCfCj = zszxjxgsbCfCj;
		this.zszxjxgsbWsjDm = zszxjxgsbWsjDm;
		this.zszxjxgsbWsjDmbz = zszxjxgsbWsjDmbz;
		this.zszxjxgsbWsjQm = zszxjxgsbWsjQm;
		this.zszxjxgsbWsjQmbz = zszxjxgsbWsjQmbz;
		this.zszxjxgsbWsjDp = zszxjxgsbWsjDp;
		this.zszxjxgsbWsjDpbz = zszxjxgsbWsjDpbz;
		this.zszxjxgsbWsjQj = zszxjxgsbWsjQj;
		this.zszxjxgsbYt = zszxjxgsbYt;
		this.zszxjxgsbYtbz = zszxjxgsbYtbz;
		this.zszxjxgsbDtPp = zszxjxgsbDtPp;
		this.zszxjxgsbDtXh = zszxjxgsbDtXh;
		this.zszxjxgsbGd = zszxjxgsbGd;
		this.zszxjxgsbCh = zszxjxgsbCh;
		this.zszxjxgsbBz9 = zszxjxgsbBz9;
		this.zszxjxgsbBz10 = zszxjxgsbBz10;
		this.bxfwqxzrDjjchztjgBxqx = bxfwqxzrDjjchztjgBxqx;
		this.bxfwqxzrDjjchztjgBxqxbz = bxfwqxzrDjjchztjgBxqxbz;
		this.bxfwqxzrFsgcBxqx = bxfwqxzrFsgcBxqx;
		this.bxfwqxzrFsgcBxqxbz = bxfwqxzrFsgcBxqxbz;
		this.bxfwqxzrGlgrBxqx = bxfwqxzrGlgrBxqx;
		this.bxfwqxzrGlgrBxqxbz = bxfwqxzrGlgrBxqxbz;
		this.bxfwqxzrDxgxBxqx = bxfwqxzrDxgxBxqx;
		this.bxfwqxzrDxgxBxqxbz = bxfwqxzrDxgxBxqxbz;
		this.bxfwqxzrZxgcBxqx = bxfwqxzrZxgcBxqx;
		this.bxfwqxzrZxgcBxqxbz = bxfwqxzrZxgcBxqxbz;
		this.bxfwqxzrMemo6 = bxfwqxzrMemo6;
		this.bxfwqxzrMemo7 = bxfwqxzrMemo7;
		this.bxfwqxzrMemo8 = bxfwqxzrMemo8;
		this.bxfwqxzrQtyd = bxfwqxzrQtyd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "COMMERCI_TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getCommerciType() {
		return this.commerciType;
	}

	public void setCommerciType(String commerciType) {
		this.commerciType = commerciType;
	}

	@Column(name = "HTDSR_CMR", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getHtdsrCmr() {
		return this.htdsrCmr;
	}

	public void setHtdsrCmr(String htdsrCmr) {
		this.htdsrCmr = htdsrCmr;
	}

	@Column(name = "HTDSR_CMR_DZ", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getHtdsrCmrDz() {
		return this.htdsrCmrDz;
	}

	public void setHtdsrCmrDz(String htdsrCmrDz) {
		this.htdsrCmrDz = htdsrCmrDz;
	}

	@Column(name = "HTDSR_CMR_YB", length = 15)
	@Size(max = 15)
	public String getHtdsrCmrYb() {
		return this.htdsrCmrYb;
	}

	public void setHtdsrCmrYb(String htdsrCmrYb) {
		this.htdsrCmrYb = htdsrCmrYb;
	}

	@Column(name = "HTDSR_CMR_YYZZ", nullable = false, length = 30)
	@NotNull
	@Size(max = 30)
	public String getHtdsrCmrYyzz() {
		return this.htdsrCmrYyzz;
	}

	public void setHtdsrCmrYyzz(String htdsrCmrYyzz) {
		this.htdsrCmrYyzz = htdsrCmrYyzz;
	}

	@Column(name = "HTDSR_CMR_QYZSH", nullable = false, length = 30)
	@NotNull
	@Size(max = 30)
	public String getHtdsrCmrQyzsh() {
		return this.htdsrCmrQyzsh;
	}

	public void setHtdsrCmrQyzsh(String htdsrCmrQyzsh) {
		this.htdsrCmrQyzsh = htdsrCmrQyzsh;
	}

	@Column(name = "HTDSR_CMR_FDDBR", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getHtdsrCmrFddbr() {
		return this.htdsrCmrFddbr;
	}

	public void setHtdsrCmrFddbr(String htdsrCmrFddbr) {
		this.htdsrCmrFddbr = htdsrCmrFddbr;
	}

	@Column(name = "HTDSR_CMR_FDDBRDH", nullable = false, length = 15)
	@NotNull
	@Size(max = 15)
	public String getHtdsrCmrFddbrdh() {
		return this.htdsrCmrFddbrdh;
	}

	public void setHtdsrCmrFddbrdh(String htdsrCmrFddbrdh) {
		this.htdsrCmrFddbrdh = htdsrCmrFddbrdh;
	}

	@Column(name = "HTDSR_CMR_WTDLR", length = 10)
	@Size(max = 10)
	public String getHtdsrCmrWtdlr() {
		return this.htdsrCmrWtdlr;
	}

	public void setHtdsrCmrWtdlr(String htdsrCmrWtdlr) {
		this.htdsrCmrWtdlr = htdsrCmrWtdlr;
	}

	@Column(name = "HTDSR_CMR_WTDLRDH", length = 15)
	@Size(max = 15)
	public String getHtdsrCmrWtdlrdh() {
		return this.htdsrCmrWtdlrdh;
	}

	public void setHtdsrCmrWtdlrdh(String htdsrCmrWtdlrdh) {
		this.htdsrCmrWtdlrdh = htdsrCmrWtdlrdh;
	}

	@Column(name = "XMJSYJ_TDQDFS", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getXmjsyjTdqdfs() {
		return this.xmjsyjTdqdfs;
	}

	public void setXmjsyjTdqdfs(String xmjsyjTdqdfs) {
		this.xmjsyjTdqdfs = xmjsyjTdqdfs;
	}

	@Column(name = "XMJSYJ_TDZL", nullable = false)
	@NotNull
	public byte[] getXmjsyjTdzl() {
		return this.xmjsyjTdzl;
	}

	public void setXmjsyjTdzl(byte[] xmjsyjTdzl) {
		this.xmjsyjTdzl = xmjsyjTdzl;
	}

	@Column(name = "XMJSYJ_TDSQQQLX", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getXmjsyjTdsqqqlx() {
		return this.xmjsyjTdsqqqlx;
	}

	public void setXmjsyjTdsqqqlx(String xmjsyjTdsqqqlx) {
		this.xmjsyjTdsqqqlx = xmjsyjTdsqqqlx;
	}

	@Column(name = "XMJSYJ_TDQZH", unique = true, nullable = false, length = 30)
	@NotNull
	@Size(max = 30)
	public String getXmjsyjTdqzh() {
		return this.xmjsyjTdqzh;
	}

	public void setXmjsyjTdqzh(String xmjsyjTdqzh) {
		this.xmjsyjTdqzh = xmjsyjTdqzh;
	}

	@Column(name = "XMJSYJ_TDMJ", nullable = false, precision = 18, scale = 3)
	@NotNull
	public BigDecimal getXmjsyjTdmj() {
		return this.xmjsyjTdmj;
	}

	public void setXmjsyjTdmj(BigDecimal xmjsyjTdmj) {
		this.xmjsyjTdmj = xmjsyjTdmj;
	}

	@Column(name = "XMJSYJ_TDYT", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getXmjsyjTdyt() {
		return this.xmjsyjTdyt;
	}

	public void setXmjsyjTdyt(String xmjsyjTdyt) {
		this.xmjsyjTdyt = xmjsyjTdyt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "XMJSYJ_TDSYQZZSJ", nullable = false, length = 19)
	@NotNull
	public Date getXmjsyjTdsyqzzsj() {
		return this.xmjsyjTdsyqzzsj;
	}

	public void setXmjsyjTdsyqzzsj(Date xmjsyjTdsyqzzsj) {
		this.xmjsyjTdsyqzzsj = xmjsyjTdsyqzzsj;
	}

	@Column(name = "XMJSYJ_XMMC", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getXmjsyjXmmc() {
		return this.xmjsyjXmmc;
	}

	public void setXmjsyjXmmc(String xmjsyjXmmc) {
		this.xmjsyjXmmc = xmjsyjXmmc;
	}

	@Column(name = "XMJSYJ_JSGCGHXKZH", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getXmjsyjJsgcghxkzh() {
		return this.xmjsyjJsgcghxkzh;
	}

	public void setXmjsyjJsgcghxkzh(String xmjsyjJsgcghxkzh) {
		this.xmjsyjJsgcghxkzh = xmjsyjJsgcghxkzh;
	}

	@Column(name = "XMJSYJ_JZGCSGXUKZH", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getXmjsyjJzgcsgxukzh() {
		return this.xmjsyjJzgcsgxukzh;
	}

	public void setXmjsyjJzgcsgxukzh(String xmjsyjJzgcsgxukzh) {
		this.xmjsyjJzgcsgxukzh = xmjsyjJzgcsgxukzh;
	}

	@Column(name = "SPFJBQK_FWSJYT", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getSpfjbqkFwsjyt() {
		return this.spfjbqkFwsjyt;
	}

	public void setSpfjbqkFwsjyt(String spfjbqkFwsjyt) {
		this.spfjbqkFwsjyt = spfjbqkFwsjyt;
	}

	@Column(name = "SPFJBQK_FWJG", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getSpfjbqkFwjg() {
		return this.spfjbqkFwjg;
	}

	public void setSpfjbqkFwjg(String spfjbqkFwjg) {
		this.spfjbqkFwjg = spfjbqkFwjg;
	}

	@Column(name = "SPFJBQK_FWJZZCS", nullable = false)
	public int getSpfjbqkFwjzzcs() {
		return this.spfjbqkFwjzzcs;
	}

	public void setSpfjbqkFwjzzcs(int spfjbqkFwjzzcs) {
		this.spfjbqkFwjzzcs = spfjbqkFwjzzcs;
	}

	@Column(name = "SPFJBQK_FWJZDSCS", nullable = false)
	public int getSpfjbqkFwjzdscs() {
		return this.spfjbqkFwjzdscs;
	}

	public void setSpfjbqkFwjzdscs(int spfjbqkFwjzdscs) {
		this.spfjbqkFwjzdscs = spfjbqkFwjzdscs;
	}

	@Column(name = "SPFJBQK_FWJZDXCS", nullable = false)
	public int getSpfjbqkFwjzdxcs() {
		return this.spfjbqkFwjzdxcs;
	}

	public void setSpfjbqkFwjzdxcs(int spfjbqkFwjzdxcs) {
		this.spfjbqkFwjzdxcs = spfjbqkFwjzdxcs;
	}

	@Column(name = "SPFJBQK_ZH", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getSpfjbqkZh() {
		return this.spfjbqkZh;
	}

	public void setSpfjbqkZh(String spfjbqkZh) {
		this.spfjbqkZh = spfjbqkZh;
	}

	@Column(name = "SPFJBQK_ZUOHAO", length = 20)
	@Size(max = 20)
	public String getSpfjbqkZuohao() {
		return this.spfjbqkZuohao;
	}

	public void setSpfjbqkZuohao(String spfjbqkZuohao) {
		this.spfjbqkZuohao = spfjbqkZuohao;
	}

	@Column(name = "SPFJBQK_DYH", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getSpfjbqkDyh() {
		return this.spfjbqkDyh;
	}

	public void setSpfjbqkDyh(String spfjbqkDyh) {
		this.spfjbqkDyh = spfjbqkDyh;
	}

	@Column(name = "SPFJBQK_CH", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getSpfjbqkCh() {
		return this.spfjbqkCh;
	}

	public void setSpfjbqkCh(String spfjbqkCh) {
		this.spfjbqkCh = spfjbqkCh;
	}

	@Column(name = "SPFJBQK_CHJG", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getSpfjbqkChjg() {
		return this.spfjbqkChjg;
	}

	public void setSpfjbqkChjg(String spfjbqkChjg) {
		this.spfjbqkChjg = spfjbqkChjg;
	}

	@Column(name = "SPFJBQK_JZMJ", nullable = false, precision = 18, scale = 3)
	@NotNull
	public BigDecimal getSpfjbqkJzmj() {
		return this.spfjbqkJzmj;
	}

	public void setSpfjbqkJzmj(BigDecimal spfjbqkJzmj) {
		this.spfjbqkJzmj = spfjbqkJzmj;
	}

	@Column(name = "SPFJBQK_TNMJ", nullable = false, precision = 18, scale = 3)
	@NotNull
	public BigDecimal getSpfjbqkTnmj() {
		return this.spfjbqkTnmj;
	}

	public void setSpfjbqkTnmj(BigDecimal spfjbqkTnmj) {
		this.spfjbqkTnmj = spfjbqkTnmj;
	}

	@Column(name = "SPFJBQK_FTMJ", nullable = false, precision = 18, scale = 3)
	@NotNull
	public BigDecimal getSpfjbqkFtmj() {
		return this.spfjbqkFtmj;
	}

	public void setSpfjbqkFtmj(BigDecimal spfjbqkFtmj) {
		this.spfjbqkFtmj = spfjbqkFtmj;
	}

	@Column(name = "CGW", nullable = false, precision = 8, scale = 3)
	@NotNull
	public BigDecimal getCgw() {
		return this.cgw;
	}

	public void setCgw(BigDecimal cgw) {
		this.cgw = cgw;
	}

	@Column(name = "YGYT", nullable = false)
	public int getYgyt() {
		return this.ygyt;
	}

	public void setYgyt(int ygyt) {
		this.ygyt = ygyt;
	}

	@Column(name = "YJGFBYT", nullable = false)
	public int getYjgfbyt() {
		return this.yjgfbyt;
	}

	public void setYjgfbyt(int yjgfbyt) {
		this.yjgfbyt = yjgfbyt;
	}

	@Column(name = "FBYTGS", nullable = false)
	public int getFbytgs() {
		return this.fbytgs;
	}

	public void setFbytgs(int fbytgs) {
		this.fbytgs = fbytgs;
	}

	@Column(name = "FWQLZKQN4", length = 100)
	@Size(max = 100)
	public String getFwqlzkqn4() {
		return this.fwqlzkqn4;
	}

	public void setFwqlzkqn4(String fwqlzkqn4) {
		this.fwqlzkqn4 = fwqlzkqn4;
	}

	@Column(name = "FWQLZKQN5", length = 100)
	@Size(max = 100)
	public String getFwqlzkqn5() {
		return this.fwqlzkqn5;
	}

	public void setFwqlzkqn5(String fwqlzkqn5) {
		this.fwqlzkqn5 = fwqlzkqn5;
	}

	@Column(name = "AZ", length = 10)
	@Size(max = 10)
	public String getAz() {
		return this.az;
	}

	public void setAz(String az) {
		this.az = az;
	}

	@Column(name = "FWQLZKCN_CFFS", length = 32)
	@Size(max = 32)
	public String getFwqlzkcnCffs() {
		return this.fwqlzkcnCffs;
	}

	public void setFwqlzkcnCffs(String fwqlzkcnCffs) {
		this.fwqlzkcnCffs = fwqlzkcnCffs;
	}

	@Column(name = "DJZ")
	public Integer getDjz() {
		return this.djz;
	}

	public void setDjz(Integer djz) {
		this.djz = djz;
	}

	@Column(name = "TNMJ_BZ1", length = 32)
	@Size(max = 32)
	public String getTnmjBz1() {
		return this.tnmjBz1;
	}

	public void setTnmjBz1(String tnmjBz1) {
		this.tnmjBz1 = tnmjBz1;
	}

	@Column(name = "TNMJ_Y1", precision = 18, scale = 3)
	public BigDecimal getTnmjY1() {
		return this.tnmjY1;
	}

	public void setTnmjY1(BigDecimal tnmjY1) {
		this.tnmjY1 = tnmjY1;
	}

	@Column(name = "TNMJ_ZJKBZ1", length = 32)
	@Size(max = 32)
	public String getTnmjZjkbz1() {
		return this.tnmjZjkbz1;
	}

	public void setTnmjZjkbz1(String tnmjZjkbz1) {
		this.tnmjZjkbz1 = tnmjZjkbz1;
	}

	@Column(name = "TNMJ_ZJK1", precision = 18, scale = 3)
	public BigDecimal getTnmjZjk1() {
		return this.tnmjZjk1;
	}

	public void setTnmjZjk1(BigDecimal tnmjZjk1) {
		this.tnmjZjk1 = tnmjZjk1;
	}

	@Column(name = "TNMJ_ZJKDX1", length = 50)
	@Size(max = 50)
	public String getTnmjZjkdx1() {
		return this.tnmjZjkdx1;
	}

	public void setTnmjZjkdx1(String tnmjZjkdx1) {
		this.tnmjZjkdx1 = tnmjZjkdx1;
	}

	@Column(name = "JZMJ_BZ2", length = 32)
	@Size(max = 32)
	public String getJzmjBz2() {
		return this.jzmjBz2;
	}

	public void setJzmjBz2(String jzmjBz2) {
		this.jzmjBz2 = jzmjBz2;
	}

	@Column(name = "JZMJ_Y2", precision = 18, scale = 3)
	public BigDecimal getJzmjY2() {
		return this.jzmjY2;
	}

	public void setJzmjY2(BigDecimal jzmjY2) {
		this.jzmjY2 = jzmjY2;
	}

	@Column(name = "JZMJ_ZJKBZ2", length = 32)
	@Size(max = 32)
	public String getJzmjZjkbz2() {
		return this.jzmjZjkbz2;
	}

	public void setJzmjZjkbz2(String jzmjZjkbz2) {
		this.jzmjZjkbz2 = jzmjZjkbz2;
	}

	@Column(name = "JZMJ_ZJK2", precision = 18, scale = 3)
	public BigDecimal getJzmjZjk2() {
		return this.jzmjZjk2;
	}

	public void setJzmjZjk2(BigDecimal jzmjZjk2) {
		this.jzmjZjk2 = jzmjZjk2;
	}

	@Column(name = "ZJKDX2", length = 50)
	@Size(max = 50)
	public String getZjkdx2() {
		return this.zjkdx2;
	}

	public void setZjkdx2(String zjkdx2) {
		this.zjkdx2 = zjkdx2;
	}

	@Column(name = "T_BZ3", length = 32)
	@Size(max = 32)
	public String getTBz3() {
		return this.TBz3;
	}

	public void setTBz3(String TBz3) {
		this.TBz3 = TBz3;
	}

	@Column(name = "T_ZJK3", precision = 18, scale = 3)
	public BigDecimal getTZjk3() {
		return this.TZjk3;
	}

	public void setTZjk3(BigDecimal TZjk3) {
		this.TZjk3 = TZjk3;
	}

	@Column(name = "T_ZJKDX3", length = 50)
	@Size(max = 50)
	public String getTZjkdx3() {
		return this.TZjkdx3;
	}

	public void setTZjkdx3(String TZjkdx3) {
		this.TZjkdx3 = TZjkdx3;
	}

	@Column(name = "QT_AZJS", length = 20)
	@Size(max = 20)
	public String getQtAzjs() {
		return this.qtAzjs;
	}

	public void setQtAzjs(String qtAzjs) {
		this.qtAzjs = qtAzjs;
	}

	@Column(name = "QT_BZ4", length = 32)
	@Size(max = 32)
	public String getQtBz4() {
		return this.qtBz4;
	}

	public void setQtBz4(String qtBz4) {
		this.qtBz4 = qtBz4;
	}

	@Column(name = "QT_ZJK4", precision = 18, scale = 3)
	public BigDecimal getQtZjk4() {
		return this.qtZjk4;
	}

	public void setQtZjk4(BigDecimal qtZjk4) {
		this.qtZjk4 = qtZjk4;
	}

	@Column(name = "QT_ZJKDX4", length = 50)
	@Size(max = 50)
	public String getQtZjkdx4() {
		return this.qtZjkdx4;
	}

	public void setQtZjkdx4(String qtZjkdx4) {
		this.qtZjkdx4 = qtZjkdx4;
	}

	@Column(name = "FKFSJQX_BZ1", length = 32)
	@Size(max = 32)
	public String getFkfsjqxBz1() {
		return this.fkfsjqxBz1;
	}

	public void setFkfsjqxBz1(String fkfsjqxBz1) {
		this.fkfsjqxBz1 = fkfsjqxBz1;
	}

	@Column(name = "FKFSJQX_ZJK1", length = 50)
	@Size(max = 50)
	public String getFkfsjqxZjk1() {
		return this.fkfsjqxZjk1;
	}

	public void setFkfsjqxZjk1(String fkfsjqxZjk1) {
		this.fkfsjqxZjk1 = fkfsjqxZjk1;
	}

	@Column(name = "FKFSJQX_DJJFFS", length = 32)
	@Size(max = 32)
	public String getFkfsjqxDjjffs() {
		return this.fkfsjqxDjjffs;
	}

	public void setFkfsjqxDjjffs(String fkfsjqxDjjffs) {
		this.fkfsjqxDjjffs = fkfsjqxDjjffs;
	}

	@Column(name = "FKFSJQX_DYSPFJK", length = 32)
	@Size(max = 32)
	public String getFkfsjqxDyspfjk() {
		return this.fkfsjqxDyspfjk;
	}

	public void setFkfsjqxDyspfjk(String fkfsjqxDyspfjk) {
		this.fkfsjqxDyspfjk = fkfsjqxDyspfjk;
	}

	@Column(name = "DJZFKFS")
	public Integer getDjzfkfs() {
		return this.djzfkfs;
	}

	public void setDjzfkfs(Integer djzfkfs) {
		this.djzfkfs = djzfkfs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "YCXFK_YCXFKSJ", nullable = false, length = 19)
	@NotNull
	public Date getYcxfkYcxfksj() {
		return this.ycxfkYcxfksj;
	}

	public void setYcxfkYcxfksj(Date ycxfkYcxfksj) {
		this.ycxfkYcxfksj = ycxfkYcxfksj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FQFK_FQFKSJ", nullable = false, length = 19)
	@NotNull
	public Date getFqfkFqfksj() {
		return this.fqfkFqfksj;
	}

	public void setFqfkFqfksj(Date fqfkFqfksj) {
		this.fqfkFqfksj = fqfkFqfksj;
	}

	@Column(name = "FQFK_FJQ")
	public Integer getFqfkFjq() {
		return this.fqfkFjq;
	}

	public void setFqfkFjq(Integer fqfkFjq) {
		this.fqfkFjq = fqfkFjq;
	}

	@Column(name = "FQFK_SQFJKBZ", length = 32)
	@Size(max = 32)
	public String getFqfkSqfjkbz() {
		return this.fqfkSqfjkbz;
	}

	public void setFqfkSqfjkbz(String fqfkSqfjkbz) {
		this.fqfkSqfjkbz = fqfkSqfjkbz;
	}

	@Column(name = "FQFK_SQFJKY", precision = 18, scale = 3)
	public BigDecimal getFqfkSqfjky() {
		return this.fqfkSqfjky;
	}

	public void setFqfkSqfjky(BigDecimal fqfkSqfjky) {
		this.fqfkSqfjky = fqfkSqfjky;
	}

	@Column(name = "FQFK_SQFJKDX", length = 50)
	@Size(max = 50)
	public String getFqfkSqfjkdx() {
		return this.fqfkSqfjkdx;
	}

	public void setFqfkSqfjkdx(String fqfkSqfjkdx) {
		this.fqfkSqfjkdx = fqfkSqfjkdx;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FQFK_YDY", nullable = false, length = 19)
	@NotNull
	public Date getFqfkYdy() {
		return this.fqfkYdy;
	}

	public void setFqfkYdy(Date fqfkYdy) {
		this.fqfkYdy = fqfkYdy;
	}

	@Column(name = "FQFK_YDYBZ", length = 100)
	@Size(max = 100)
	public String getFqfkYdybz() {
		return this.fqfkYdybz;
	}

	public void setFqfkYdybz(String fqfkYdybz) {
		this.fqfkYdybz = fqfkYdybz;
	}

	@Column(name = "DKFS_DKFS", length = 32)
	@Size(max = 32)
	public String getDkfsDkfs() {
		return this.dkfsDkfs;
	}

	public void setDkfsDkfs(String dkfsDkfs) {
		this.dkfsDkfs = dkfsDkfs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DKFS_MSRSFSJ", nullable = false, length = 19)
	@NotNull
	public Date getDkfsMsrsfsj() {
		return this.dkfsMsrsfsj;
	}

	public void setDkfsMsrsfsj(Date dkfsMsrsfsj) {
		this.dkfsMsrsfsj = dkfsMsrsfsj;
	}

	@Column(name = "DKFS_DKSFBZ", length = 32)
	@Size(max = 32)
	public String getDkfsDksfbz() {
		return this.dkfsDksfbz;
	}

	public void setDkfsDksfbz(String dkfsDksfbz) {
		this.dkfsDksfbz = dkfsDksfbz;
	}

	@Column(name = "DKFS_DKSFY", precision = 18, scale = 3)
	public BigDecimal getDkfsDksfy() {
		return this.dkfsDksfy;
	}

	public void setDkfsDksfy(BigDecimal dkfsDksfy) {
		this.dkfsDksfy = dkfsDksfy;
	}

	@Column(name = "DKFS_DKSFKDX", length = 50)
	@Size(max = 50)
	public String getDkfsDksfkdx() {
		return this.dkfsDksfkdx;
	}

	public void setDkfsDksfkdx(String dkfsDksfkdx) {
		this.dkfsDksfkdx = dkfsDksfkdx;
	}

	@Column(name = "DKFS_ZQBFKBFB", length = 10)
	@Size(max = 10)
	public String getDkfsZqbfkbfb() {
		return this.dkfsZqbfkbfb;
	}

	public void setDkfsZqbfkbfb(String dkfsZqbfkbfb) {
		this.dkfsZqbfkbfb = dkfsZqbfkbfb;
	}

	@Column(name = "DKFS_YKBZ", length = 32)
	@Size(max = 32)
	public String getDkfsYkbz() {
		return this.dkfsYkbz;
	}

	public void setDkfsYkbz(String dkfsYkbz) {
		this.dkfsYkbz = dkfsYkbz;
	}

	@Column(name = "DKFS_YK", precision = 18, scale = 3)
	public BigDecimal getDkfsYk() {
		return this.dkfsYk;
	}

	public void setDkfsYk(BigDecimal dkfsYk) {
		this.dkfsYk = dkfsYk;
	}

	@Column(name = "DKFS_YKDX", length = 100)
	@Size(max = 100)
	public String getDkfsYkdx() {
		return this.dkfsYkdx;
	}

	public void setDkfsYkdx(String dkfsYkdx) {
		this.dkfsYkdx = dkfsYkdx;
	}

	@Column(name = "DKFS_DKJG", length = 100)
	@Size(max = 100)
	public String getDkfsDkjg() {
		return this.dkfsDkjg;
	}

	public void setDkfsDkjg(String dkfsDkjg) {
		this.dkfsDkjg = dkfsDkjg;
	}

	@Column(name = "FKQTFS", length = 200)
	@Size(max = 200)
	public String getFkqtfs() {
		return this.fkqtfs;
	}

	public void setFkqtfs(String fkqtfs) {
		this.fkqtfs = fkqtfs;
	}

	@Column(name = "YQFKZEFS")
	public Integer getYqfkzefs() {
		return this.yqfkzefs;
	}

	public void setYqfkzefs(Integer yqfkzefs) {
		this.yqfkzefs = yqfkzefs;
	}

	@Column(name = "YQJR1")
	public Integer getYqjr1() {
		return this.yqjr1;
	}

	public void setYqjr1(Integer yqjr1) {
		this.yqjr1 = yqjr1;
	}

	@Column(name = "YFKWFZJ1", precision = 8, scale = 3)
	public BigDecimal getYfkwfzj1() {
		return this.yfkwfzj1;
	}

	public void setYfkwfzj1(BigDecimal yfkwfzj1) {
		this.yfkwfzj1 = yfkwfzj1;
	}

	@Column(name = "YQFKZR_YQCGJR")
	public Integer getYqfkzrYqcgjr() {
		return this.yqfkzrYqcgjr;
	}

	public void setYqfkzrYqcgjr(Integer yqfkzrYqcgjr) {
		this.yqfkzrYqcgjr = yqfkzrYqcgjr;
	}

	@Column(name = "SDZRQ")
	public Integer getSdzrq() {
		return this.sdzrq;
	}

	public void setSdzrq(Integer sdzrq) {
		this.sdzrq = sdzrq;
	}

	@Column(name = "YFKBFB", precision = 8, scale = 3)
	public BigDecimal getYfkbfb() {
		return this.yfkbfb;
	}

	public void setYfkbfb(BigDecimal yfkbfb) {
		this.yfkbfb = yfkbfb;
	}

	@Column(name = "YFKWFZJ2", precision = 8, scale = 3)
	public BigDecimal getYfkwfzj2() {
		return this.yfkwfzj2;
	}

	public void setYfkwfzj2(BigDecimal yfkwfzj2) {
		this.yfkwfzj2 = yfkwfzj2;
	}

	@Column(name = "YQFKZRBZ2", length = 200)
	@Size(max = 200)
	public String getYqfkzrbz2() {
		return this.yqfkzrbz2;
	}

	public void setYqfkzrbz2(String yqfkzrbz2) {
		this.yqfkzrbz2 = yqfkzrbz2;
	}

	@Column(name = "FHTJ3")
	public Integer getFhtj3() {
		return this.fhtj3;
	}

	public void setFhtj3(Integer fhtj3) {
		this.fhtj3 = fhtj3;
	}

	@Column(name = "FHTJ4")
	public Integer getFhtj4() {
		return this.fhtj4;
	}

	public void setFhtj4(Integer fhtj4) {
		this.fhtj4 = fhtj4;
	}

	@Column(name = "FHTJMEMO3", length = 100)
	@Size(max = 100)
	public String getFhtjmemo3() {
		return this.fhtjmemo3;
	}

	public void setFhtjmemo3(String fhtjmemo3) {
		this.fhtjmemo3 = fhtjmemo3;
	}

	@Column(name = "FHTJMEMO4", length = 100)
	@Size(max = 100)
	public String getFhtjmemo4() {
		return this.fhtjmemo4;
	}

	public void setFhtjmemo4(String fhtjmemo4) {
		this.fhtjmemo4 = fhtjmemo4;
	}

	@Column(name = "JCSSSB1", length = 100)
	@Size(max = 100)
	public String getJcsssb1() {
		return this.jcsssb1;
	}

	public void setJcsssb1(String jcsssb1) {
		this.jcsssb1 = jcsssb1;
	}

	@Column(name = "JCSSSB2", length = 100)
	@Size(max = 100)
	public String getJcsssb2() {
		return this.jcsssb2;
	}

	public void setJcsssb2(String jcsssb2) {
		this.jcsssb2 = jcsssb2;
	}

	@Column(name = "JCSSSB3", length = 100)
	@Size(max = 100)
	public String getJcsssb3() {
		return this.jcsssb3;
	}

	public void setJcsssb3(String jcsssb3) {
		this.jcsssb3 = jcsssb3;
	}

	@Column(name = "JCSSSB4", length = 100)
	@Size(max = 100)
	public String getJcsssb4() {
		return this.jcsssb4;
	}

	public void setJcsssb4(String jcsssb4) {
		this.jcsssb4 = jcsssb4;
	}

	@Column(name = "AZXLDJZCL")
	public Integer getAzxldjzcl() {
		return this.azxldjzcl;
	}

	public void setAzxldjzcl(Integer azxldjzcl) {
		this.azxldjzcl = azxldjzcl;
	}

	@Column(name = "ZFWYJ5", precision = 18, scale = 3)
	public BigDecimal getZfwyj5() {
		return this.zfwyj5;
	}

	public void setZfwyj5(BigDecimal zfwyj5) {
		this.zfwyj5 = zfwyj5;
	}

	@Column(name = "ZFWYJ6", precision = 18, scale = 3)
	public BigDecimal getZfwyj6() {
		return this.zfwyj6;
	}

	public void setZfwyj6(BigDecimal zfwyj6) {
		this.zfwyj6 = zfwyj6;
	}

	@Column(name = "ZFWYJ7", precision = 18, scale = 3)
	public BigDecimal getZfwyj7() {
		return this.zfwyj7;
	}

	public void setZfwyj7(BigDecimal zfwyj7) {
		this.zfwyj7 = zfwyj7;
	}

	@Column(name = "YDJFRHDJR")
	public Integer getYdjfrhdjr() {
		return this.ydjfrhdjr;
	}

	public void setYdjfrhdjr(Integer ydjfrhdjr) {
		this.ydjfrhdjr = ydjfrhdjr;
	}

	@Column(name = "JFSYTJMEMO2", length = 100)
	@Size(max = 100)
	public String getJfsytjmemo2() {
		return this.jfsytjmemo2;
	}

	public void setJfsytjmemo2(String jfsytjmemo2) {
		this.jfsytjmemo2 = jfsytjmemo2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LDLSJ", nullable = false, length = 19)
	@NotNull
	public Date getLdlsj() {
		return this.ldlsj;
	}

	public void setLdlsj(Date ldlsj) {
		this.ldlsj = ldlsj;
	}

	@Column(name = "LDLMEMO", length = 50)
	@Size(max = 50)
	public String getLdlmemo() {
		return this.ldlmemo;
	}

	public void setLdlmemo(String ldlmemo) {
		this.ldlmemo = ldlmemo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SZDLSJ", nullable = false, length = 19)
	@NotNull
	public Date getSzdlsj() {
		return this.szdlsj;
	}

	public void setSzdlsj(Date szdlsj) {
		this.szdlsj = szdlsj;
	}

	@Column(name = "SZDLSJMEMO", length = 50)
	@Size(max = 50)
	public String getSzdlsjmemo() {
		return this.szdlsjmemo;
	}

	public void setSzdlsjmemo(String szdlsjmemo) {
		this.szdlsjmemo = szdlsjmemo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GHDCWSJ", nullable = false, length = 19)
	@NotNull
	public Date getGhdcwsj() {
		return this.ghdcwsj;
	}

	public void setGhdcwsj(Date ghdcwsj) {
		this.ghdcwsj = ghdcwsj;
	}

	@Column(name = "GHDCWMEMO", length = 50)
	@Size(max = 50)
	public String getGhdcwmemo() {
		return this.ghdcwmemo;
	}

	public void setGhdcwmemo(String ghdcwmemo) {
		this.ghdcwmemo = ghdcwmemo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WYFWYF", nullable = false, length = 19)
	@NotNull
	public Date getWyfwyf() {
		return this.wyfwyf;
	}

	public void setWyfwyf(Date wyfwyf) {
		this.wyfwyf = wyfwyf;
	}

	@Column(name = "WYFWYFMEMO", length = 50)
	@Size(max = 50)
	public String getWyfwyfmemo() {
		return this.wyfwyfmemo;
	}

	public void setWyfwyfmemo(String wyfwyfmemo) {
		this.wyfwyfmemo = wyfwyfmemo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "YLWSJG", nullable = false, length = 19)
	@NotNull
	public Date getYlwsjg() {
		return this.ylwsjg;
	}

	public void setYlwsjg(Date ylwsjg) {
		this.ylwsjg = ylwsjg;
	}

	@Column(name = "YLWSJGMEMO", length = 50)
	@Size(max = 50)
	public String getYlwsjgmemo() {
		return this.ylwsjgmemo;
	}

	public void setYlwsjgmemo(String ylwsjgmemo) {
		this.ylwsjgmemo = ylwsjgmemo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "YEY", nullable = false, length = 19)
	@NotNull
	public Date getYey() {
		return this.yey;
	}

	public void setYey(Date yey) {
		this.yey = yey;
	}

	@Column(name = "YEYMEMO", length = 50)
	@Size(max = 50)
	public String getYeymemo() {
		return this.yeymemo;
	}

	public void setYeymemo(String yeymemo) {
		this.yeymemo = yeymemo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "XX", nullable = false, length = 19)
	@NotNull
	public Date getXx() {
		return this.xx;
	}

	public void setXx(Date xx) {
		this.xx = xx;
	}

	@Column(name = "XXMEMO", length = 50)
	@Size(max = 50)
	public String getXxmemo() {
		return this.xxmemo;
	}

	public void setXxmemo(String xxmemo) {
		this.xxmemo = xxmemo;
	}

	@Column(name = "GGFWJPT8", length = 100)
	@Size(max = 100)
	public String getGgfwjpt8() {
		return this.ggfwjpt8;
	}

	public void setGgfwjpt8(String ggfwjpt8) {
		this.ggfwjpt8 = ggfwjpt8;
	}

	@Column(name = "GGFWJPT9", length = 100)
	@Size(max = 100)
	public String getGgfwjpt9() {
		return this.ggfwjpt9;
	}

	public void setGgfwjpt9(String ggfwjpt9) {
		this.ggfwjpt9 = ggfwjpt9;
	}

	@Column(name = "XQLDPCSM", length = 50)
	@Size(max = 50)
	public String getXqldpcsm() {
		return this.xqldpcsm;
	}

	public void setXqldpcsm(String xqldpcsm) {
		this.xqldpcsm = xqldpcsm;
	}

	@Column(name = "FSZDLPCSM", length = 50)
	@Size(max = 50)
	public String getFszdlpcsm() {
		return this.fszdlpcsm;
	}

	public void setFszdlpcsm(String fszdlpcsm) {
		this.fszdlpcsm = fszdlpcsm;
	}

	@Column(name = "CWCKPCSM", length = 50)
	@Size(max = 50)
	public String getCwckpcsm() {
		return this.cwckpcsm;
	}

	public void setCwckpcsm(String cwckpcsm) {
		this.cwckpcsm = cwckpcsm;
	}

	@Column(name = "WYFWYFSM", length = 50)
	@Size(max = 50)
	public String getWyfwyfsm() {
		return this.wyfwyfsm;
	}

	public void setWyfwyfsm(String wyfwyfsm) {
		this.wyfwyfsm = wyfwyfsm;
	}

	@Column(name = "QTSSWDDSM", length = 50)
	@Size(max = 50)
	public String getQtsswddsm() {
		return this.qtsswddsm;
	}

	public void setQtsswddsm(String qtsswddsm) {
		this.qtsswddsm = qtsswddsm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CMRJHSH", nullable = false, length = 19)
	@NotNull
	public Date getCmrjhsh() {
		return this.cmrjhsh;
	}

	public void setCmrjhsh(Date cmrjhsh) {
		this.cmrjhsh = cmrjhsh;
	}

	@Column(name = "JMQ")
	public Integer getJmq() {
		return this.jmq;
	}

	public void setJmq(Integer jmq) {
		this.jmq = jmq;
	}

	@Column(name = "JFSJHSX2", length = 100)
	@Size(max = 100)
	public String getJfsjhsx2() {
		return this.jfsjhsx2;
	}

	public void setJfsjhsx2(String jfsjhsx2) {
		this.jfsjhsx2 = jfsjhsx2;
	}

	@Column(name = "CYCRQ")
	public Integer getCycrq() {
		return this.cycrq;
	}

	public void setCycrq(Integer cycrq) {
		this.cycrq = cycrq;
	}

	@Column(name = "CYFWBZ5", length = 100)
	@Size(max = 100)
	public String getCyfwbz5() {
		return this.cyfwbz5;
	}

	public void setCyfwbz5(String cyfwbz5) {
		this.cyfwbz5 = cyfwbz5;
	}

	@Column(name = "CYFWBZ6", length = 100)
	@Size(max = 100)
	public String getCyfwbz6() {
		return this.cyfwbz6;
	}

	public void setCyfwbz6(String cyfwbz6) {
		this.cyfwbz6 = cyfwbz6;
	}

	@Column(name = "CYFWBZ7", length = 100)
	@Size(max = 100)
	public String getCyfwbz7() {
		return this.cyfwbz7;
	}

	public void setCyfwbz7(String cyfwbz7) {
		this.cyfwbz7 = cyfwbz7;
	}

	@Column(name = "CYFWBZ8", length = 100)
	@Size(max = 100)
	public String getCyfwbz8() {
		return this.cyfwbz8;
	}

	public void setCyfwbz8(String cyfwbz8) {
		this.cyfwbz8 = cyfwbz8;
	}

	@Column(name = "YQJFCLFS")
	public Integer getYqjfclfs() {
		return this.yqjfclfs;
	}

	public void setYqjfclfs(Integer yqjfclfs) {
		this.yqjfclfs = yqjfclfs;
	}

	@Column(name = "YQZDJRZN")
	public Integer getYqzdjrzn() {
		return this.yqzdjrzn;
	}

	public void setYqzdjrzn(Integer yqzdjrzn) {
		this.yqzdjrzn = yqzdjrzn;
	}

	@Column(name = "WFZJ1", precision = 8, scale = 3)
	public BigDecimal getWfzj1() {
		return this.wfzj1;
	}

	public void setWfzj1(BigDecimal wfzj1) {
		this.wfzj1 = wfzj1;
	}

	@Column(name = "YQCGJR")
	public Integer getYqcgjr() {
		return this.yqcgjr;
	}

	public void setYqcgjr(Integer yqcgjr) {
		this.yqcgjr = yqcgjr;
	}

	@Column(name = "YQCGAZBFB2", precision = 8, scale = 3)
	public BigDecimal getYqcgazbfb2() {
		return this.yqcgazbfb2;
	}

	public void setYqcgazbfb2(BigDecimal yqcgazbfb2) {
		this.yqcgazbfb2 = yqcgazbfb2;
	}

	@Column(name = "FJKDBFB2", precision = 8, scale = 3)
	public BigDecimal getFjkdbfb2() {
		return this.fjkdbfb2;
	}

	public void setFjkdbfb2(BigDecimal fjkdbfb2) {
		this.fjkdbfb2 = fjkdbfb2;
	}

	@Column(name = "FJKWFZJ2", precision = 8, scale = 3)
	public BigDecimal getFjkwfzj2() {
		return this.fjkwfzj2;
	}

	public void setFjkwfzj2(BigDecimal fjkwfzj2) {
		this.fjkwfzj2 = fjkwfzj2;
	}

	@Column(name = "YQJFZR2BZ", length = 100)
	@Size(max = 100)
	public String getYqjfzr2bz() {
		return this.yqjfzr2bz;
	}

	public void setYqjfzr2bz(String yqjfzr2bz) {
		this.yqjfzr2bz = yqjfzr2bz;
	}

	@Column(name = "SPFZLJBXZR_BFB1", precision = 8, scale = 3)
	public BigDecimal getSpfzljbxzrBfb1() {
		return this.spfzljbxzrBfb1;
	}

	public void setSpfzljbxzrBfb1(BigDecimal spfzljbxzrBfb1) {
		this.spfzljbxzrBfb1 = spfzljbxzrBfb1;
	}

	@Column(name = "SPFZLJBXZR_MEMO1", length = 100)
	@Size(max = 100)
	public String getSpfzljbxzrMemo1() {
		return this.spfzljbxzrMemo1;
	}

	public void setSpfzljbxzrMemo1(String spfzljbxzrMemo1) {
		this.spfzljbxzrMemo1 = spfzljbxzrMemo1;
	}

	@Column(name = "SPFZLJBXZR_MEMO2", length = 100)
	@Size(max = 100)
	public String getSpfzljbxzrMemo2() {
		return this.spfzljbxzrMemo2;
	}

	public void setSpfzljbxzrMemo2(String spfzljbxzrMemo2) {
		this.spfzljbxzrMemo2 = spfzljbxzrMemo2;
	}

	@Column(name = "SPFZLJBXZR_BFB2", precision = 18, scale = 3)
	public BigDecimal getSpfzljbxzrBfb2() {
		return this.spfzljbxzrBfb2;
	}

	public void setSpfzljbxzrBfb2(BigDecimal spfzljbxzrBfb2) {
		this.spfzljbxzrBfb2 = spfzljbxzrBfb2;
	}

	@Column(name = "SPFZLJBXZR_QT_MEMO3", length = 100)
	@Size(max = 100)
	public String getSpfzljbxzrQtMemo3() {
		return this.spfzljbxzrQtMemo3;
	}

	public void setSpfzljbxzrQtMemo3(String spfzljbxzrQtMemo3) {
		this.spfzljbxzrQtMemo3 = spfzljbxzrQtMemo3;
	}

	@Column(name = "SPFZLJBXZR_ZXBZ2")
	public Integer getSpfzljbxzrZxbz2() {
		return this.spfzljbxzrZxbz2;
	}

	public void setSpfzljbxzrZxbz2(Integer spfzljbxzrZxbz2) {
		this.spfzljbxzrZxbz2 = spfzljbxzrZxbz2;
	}

	@Column(name = "SPFZLJBXZR_ZXBZ3")
	public Integer getSpfzljbxzrZxbz3() {
		return this.spfzljbxzrZxbz3;
	}

	public void setSpfzljbxzrZxbz3(Integer spfzljbxzrZxbz3) {
		this.spfzljbxzrZxbz3 = spfzljbxzrZxbz3;
	}

	@Column(name = "SPFZLJBXZR_MEMO3", length = 100)
	@Size(max = 100)
	public String getSpfzljbxzrMemo3() {
		return this.spfzljbxzrMemo3;
	}

	public void setSpfzljbxzrMemo3(String spfzljbxzrMemo3) {
		this.spfzljbxzrMemo3 = spfzljbxzrMemo3;
	}

	@Column(name = "SPFZLJBXZR_MEMO4", length = 100)
	@Size(max = 100)
	public String getSpfzljbxzrMemo4() {
		return this.spfzljbxzrMemo4;
	}

	public void setSpfzljbxzrMemo4(String spfzljbxzrMemo4) {
		this.spfzljbxzrMemo4 = spfzljbxzrMemo4;
	}

	@Column(name = "SPFZLJBXZR_KQZLBZ", length = 32)
	@Size(max = 32)
	public String getSpfzljbxzrKqzlbz() {
		return this.spfzljbxzrKqzlbz;
	}

	public void setSpfzljbxzrKqzlbz(String spfzljbxzrKqzlbz) {
		this.spfzljbxzrKqzlbz = spfzljbxzrKqzlbz;
	}

	@Column(name = "SPFZLJBXZR_KQBZMC")
	public byte[] getSpfzljbxzrKqbzmc() {
		return this.spfzljbxzrKqbzmc;
	}

	public void setSpfzljbxzrKqbzmc(byte[] spfzljbxzrKqbzmc) {
		this.spfzljbxzrKqbzmc = spfzljbxzrKqbzmc;
	}

	@Column(name = "SPFZLJBXZR_KQBZWH", length = 50)
	@Size(max = 50)
	public String getSpfzljbxzrKqbzwh() {
		return this.spfzljbxzrKqbzwh;
	}

	public void setSpfzljbxzrKqbzwh(String spfzljbxzrKqbzwh) {
		this.spfzljbxzrKqbzwh = spfzljbxzrKqbzwh;
	}

	@Column(name = "SPFZLJBXZR_GYBZ", length = 32)
	@Size(max = 32)
	public String getSpfzljbxzrGybz() {
		return this.spfzljbxzrGybz;
	}

	public void setSpfzljbxzrGybz(String spfzljbxzrGybz) {
		this.spfzljbxzrGybz = spfzljbxzrGybz;
	}

	@Column(name = "SPFZLJBXZR_AZ", precision = 8, scale = 3)
	public BigDecimal getSpfzljbxzrAz() {
		return this.spfzljbxzrAz;
	}

	public void setSpfzljbxzrAz(BigDecimal spfzljbxzrAz) {
		this.spfzljbxzrAz = spfzljbxzrAz;
	}

	@Column(name = "SPFZLJBXZR_MEMO5", length = 100)
	@Size(max = 100)
	public String getSpfzljbxzrMemo5() {
		return this.spfzljbxzrMemo5;
	}

	public void setSpfzljbxzrMemo5(String spfzljbxzrMemo5) {
		this.spfzljbxzrMemo5 = spfzljbxzrMemo5;
	}

	@Column(name = "SPFZLJBXZR_BXZE_MEMO6")
	public byte[] getSpfzljbxzrBxzeMemo6() {
		return this.spfzljbxzrBxzeMemo6;
	}

	public void setSpfzljbxzrBxzeMemo6(byte[] spfzljbxzrBxzeMemo6) {
		this.spfzljbxzrBxzeMemo6 = spfzljbxzrBxzeMemo6;
	}

	@Column(name = "SPFZLJBXZR_BXZE_HMRR")
	public Integer getSpfzljbxzrBxzeHmrr() {
		return this.spfzljbxzrBxzeHmrr;
	}

	public void setSpfzljbxzrBxzeHmrr(Integer spfzljbxzrBxzeHmrr) {
		this.spfzljbxzrBxzeHmrr = spfzljbxzrBxzeHmrr;
	}

	@Column(name = "SPFZLJBXZR_ZLDB_Y", length = 50)
	@Size(max = 50)
	public String getSpfzljbxzrZldbY() {
		return this.spfzljbxzrZldbY;
	}

	public void setSpfzljbxzrZldbY(String spfzljbxzrZldbY) {
		this.spfzljbxzrZldbY = spfzljbxzrZldbY;
	}

	@Column(name = "HTBAYFWDJ_QQWYGL_MC", length = 50)
	@Size(max = 50)
	public String getHtbayfwdjQqwyglMc() {
		return this.htbayfwdjQqwyglMc;
	}

	public void setHtbayfwdjQqwyglMc(String htbayfwdjQqwyglMc) {
		this.htbayfwdjQqwyglMc = htbayfwdjQqwyglMc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HTBAYFWDJ_QQWYGL_FWSJQ", nullable = false, length = 19)
	@NotNull
	public Date getHtbayfwdjQqwyglFwsjq() {
		return this.htbayfwdjQqwyglFwsjq;
	}

	public void setHtbayfwdjQqwyglFwsjq(Date htbayfwdjQqwyglFwsjq) {
		this.htbayfwdjQqwyglFwsjq = htbayfwdjQqwyglFwsjq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HTBAYFWDJ_QQWYGL_FWSJZ", nullable = false, length = 19)
	@NotNull
	public Date getHtbayfwdjQqwyglFwsjz() {
		return this.htbayfwdjQqwyglFwsjz;
	}

	public void setHtbayfwdjQqwyglFwsjz(Date htbayfwdjQqwyglFwsjz) {
		this.htbayfwdjQqwyglFwsjz = htbayfwdjQqwyglFwsjz;
	}

	@Column(name = "HTBAYFWDJ_QQWYGL_WYJFFS", length = 32)
	@Size(max = 32)
	public String getHtbayfwdjQqwyglWyjffs() {
		return this.htbayfwdjQqwyglWyjffs;
	}

	public void setHtbayfwdjQqwyglWyjffs(String htbayfwdjQqwyglWyjffs) {
		this.htbayfwdjQqwyglWyjffs = htbayfwdjQqwyglWyjffs;
	}

	@Column(name = "HTBAYFWDJ_QQWYGL_MYWYF", precision = 10, scale = 3)
	public BigDecimal getHtbayfwdjQqwyglMywyf() {
		return this.htbayfwdjQqwyglMywyf;
	}

	public void setHtbayfwdjQqwyglMywyf(BigDecimal htbayfwdjQqwyglMywyf) {
		this.htbayfwdjQqwyglMywyf = htbayfwdjQqwyglMywyf;
	}

	@Column(name = "QTSX_JZWQFSYQ_MEMO1", length = 100)
	@Size(max = 100)
	public String getQtsxJzwqfsyqMemo1() {
		return this.qtsxJzwqfsyqMemo1;
	}

	public void setQtsxJzwqfsyqMemo1(String qtsxJzwqfsyqMemo1) {
		this.qtsxJzwqfsyqMemo1 = qtsxJzwqfsyqMemo1;
	}

	@Column(name = "QTSX_JZWQFSYQ_CKCW", length = 50)
	@Size(max = 50)
	public String getQtsxJzwqfsyqCkcw() {
		return this.qtsxJzwqfsyqCkcw;
	}

	public void setQtsxJzwqfsyqCkcw(String qtsxJzwqfsyqCkcw) {
		this.qtsxJzwqfsyqCkcw = qtsxJzwqfsyqCkcw;
	}

	@Column(name = "QTSX_JZWQFSYQ_HS", length = 100)
	@Size(max = 100)
	public String getQtsxJzwqfsyqHs() {
		return this.qtsxJzwqfsyqHs;
	}

	public void setQtsxJzwqfsyqHs(String qtsxJzwqfsyqHs) {
		this.qtsxJzwqfsyqHs = qtsxJzwqfsyqHs;
	}

	@Column(name = "QTSX_JZWQFSYQ_MEMO3", length = 100)
	@Size(max = 100)
	public String getQtsxJzwqfsyqMemo3() {
		return this.qtsxJzwqfsyqMemo3;
	}

	public void setQtsxJzwqfsyqMemo3(String qtsxJzwqfsyqMemo3) {
		this.qtsxJzwqfsyqMemo3 = qtsxJzwqfsyqMemo3;
	}

	@Column(name = "QTSX_SXHSYQCN_MEMO6", length = 100)
	@Size(max = 100)
	public String getQtsxSxhsyqcnMemo6() {
		return this.qtsxSxhsyqcnMemo6;
	}

	public void setQtsxSxhsyqcnMemo6(String qtsxSxhsyqcnMemo6) {
		this.qtsxSxhsyqcnMemo6 = qtsxSxhsyqcnMemo6;
	}

	@Column(name = "QTSX_SXHSYQCN_MEMO7", length = 100)
	@Size(max = 100)
	public String getQtsxSxhsyqcnMemo7() {
		return this.qtsxSxhsyqcnMemo7;
	}

	public void setQtsxSxhsyqcnMemo7(String qtsxSxhsyqcnMemo7) {
		this.qtsxSxhsyqcnMemo7 = qtsxSxhsyqcnMemo7;
	}

	@Column(name = "QTSX_SD_FS", length = 32)
	@Size(max = 32)
	public String getQtsxSdFs() {
		return this.qtsxSdFs;
	}

	public void setQtsxSdFs(String qtsxSdFs) {
		this.qtsxSdFs = qtsxSdFs;
	}

	@Column(name = "QTSX_SD_BGZR")
	public Integer getQtsxSdBgzr() {
		return this.qtsxSdBgzr;
	}

	public void setQtsxSdBgzr(Integer qtsxSdBgzr) {
		this.qtsxSdBgzr = qtsxSdBgzr;
	}

	@Column(name = "QTSX_ZYJJFS_FSJW")
	public Integer getQtsxZyjjfsFsjw() {
		return this.qtsxZyjjfsFsjw;
	}

	public void setQtsxZyjjfsFsjw(Integer qtsxZyjjfsFsjw) {
		this.qtsxZyjjfsFsjw = qtsxZyjjfsFsjw;
	}

	@Column(name = "QTSX_ZYJJFS_ZCWYHMC", length = 50)
	@Size(max = 50)
	public String getQtsxZyjjfsZcwyhmc() {
		return this.qtsxZyjjfsZcwyhmc;
	}

	public void setQtsxZyjjfsZcwyhmc(String qtsxZyjjfsZcwyhmc) {
		this.qtsxZyjjfsZcwyhmc = qtsxZyjjfsZcwyhmc;
	}

	@Column(name = "QTSX_HTSX_BHTYS")
	public Integer getQtsxHtsxBhtys() {
		return this.qtsxHtsxBhtys;
	}

	public void setQtsxHtsxBhtys(Integer qtsxHtsxBhtys) {
		this.qtsxHtsxBhtys = qtsxHtsxBhtys;
	}

	@Column(name = "QTSX_HTSX_HTFS")
	public Integer getQtsxHtsxHtfs() {
		return this.qtsxHtsxHtfs;
	}

	public void setQtsxHtsxHtfs(Integer qtsxHtsxHtfs) {
		this.qtsxHtsxHtfs = qtsxHtsxHtfs;
	}

	@Column(name = "QTSX_HTSX_CMRFS")
	public Integer getQtsxHtsxCmrfs() {
		return this.qtsxHtsxCmrfs;
	}

	public void setQtsxHtsxCmrfs(Integer qtsxHtsxCmrfs) {
		this.qtsxHtsxCmrfs = qtsxHtsxCmrfs;
	}

	@Column(name = "QTSX_HTSX_MSRFS")
	public Integer getQtsxHtsxMsrfs() {
		return this.qtsxHtsxMsrfs;
	}

	public void setQtsxHtsxMsrfs(Integer qtsxHtsxMsrfs) {
		this.qtsxHtsxMsrfs = qtsxHtsxMsrfs;
	}

	@Column(name = "QTSX_HTSX_MC1")
	public Integer getQtsxHtsxMc1() {
		return this.qtsxHtsxMc1;
	}

	public void setQtsxHtsxMc1(Integer qtsxHtsxMc1) {
		this.qtsxHtsxMc1 = qtsxHtsxMc1;
	}

	@Column(name = "QTSX_HTSX_FS1")
	public Integer getQtsxHtsxFs1() {
		return this.qtsxHtsxFs1;
	}

	public void setQtsxHtsxFs1(Integer qtsxHtsxFs1) {
		this.qtsxHtsxFs1 = qtsxHtsxFs1;
	}

	@Column(name = "QTSX_HTSX_MC2")
	public Integer getQtsxHtsxMc2() {
		return this.qtsxHtsxMc2;
	}

	public void setQtsxHtsxMc2(Integer qtsxHtsxMc2) {
		this.qtsxHtsxMc2 = qtsxHtsxMc2;
	}

	@Column(name = "QTSX_HTSX_FS2")
	public Integer getQtsxHtsxFs2() {
		return this.qtsxHtsxFs2;
	}

	public void setQtsxHtsxFs2(Integer qtsxHtsxFs2) {
		this.qtsxHtsxFs2 = qtsxHtsxFs2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QDSJ", nullable = false, length = 19)
	@NotNull
	public Date getQdsj() {
		return this.qdsj;
	}

	public void setQdsj(Date qdsj) {
		this.qdsj = qdsj;
	}

	@Column(name = "QDDD", length = 50)
	@Size(max = 50)
	public String getQddd() {
		return this.qddd;
	}

	public void setQddd(String qddd) {
		this.qddd = qddd;
	}

	@Column(name = "ZSZXJXGSB_WQ", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbWq() {
		return this.zszxjxgsbWq;
	}

	public void setZszxjxgsbWq(String zszxjxgsbWq) {
		this.zszxjxgsbWq = zszxjxgsbWq;
	}

	@Column(name = "ZSZXJXGSB_WQBZ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbWqbz() {
		return this.zszxjxgsbWqbz;
	}

	public void setZszxjxgsbWqbz(String zszxjxgsbWqbz) {
		this.zszxjxgsbWqbz = zszxjxgsbWqbz;
	}

	@Column(name = "ZSZXJXGSB_QJS_NQ", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbQjsNq() {
		return this.zszxjxgsbQjsNq;
	}

	public void setZszxjxgsbQjsNq(String zszxjxgsbQjsNq) {
		this.zszxjxgsbQjsNq = zszxjxgsbQjsNq;
	}

	@Column(name = "ZSZXJXGSB_QJS_DP", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbQjsDp() {
		return this.zszxjxgsbQjsDp;
	}

	public void setZszxjxgsbQjsDp(String zszxjxgsbQjsDp) {
		this.zszxjxgsbQjsDp = zszxjxgsbQjsDp;
	}

	@Column(name = "ZSZXJXGSB_QJS_DPBZ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbQjsDpbz() {
		return this.zszxjxgsbQjsDpbz;
	}

	public void setZszxjxgsbQjsDpbz(String zszxjxgsbQjsDpbz) {
		this.zszxjxgsbQjsDpbz = zszxjxgsbQjsDpbz;
	}

	@Column(name = "ZSZXJXGSB_QJS_SNDM", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbQjsSndm() {
		return this.zszxjxgsbQjsSndm;
	}

	public void setZszxjxgsbQjsSndm(String zszxjxgsbQjsSndm) {
		this.zszxjxgsbQjsSndm = zszxjxgsbQjsSndm;
	}

	@Column(name = "ZSZXJXGSB_QJS_SNDMBZ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbQjsSndmbz() {
		return this.zszxjxgsbQjsSndmbz;
	}

	public void setZszxjxgsbQjsSndmbz(String zszxjxgsbQjsSndmbz) {
		this.zszxjxgsbQjsSndmbz = zszxjxgsbQjsSndmbz;
	}

	@Column(name = "ZSZXJXGSB_CF_DM", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbCfDm() {
		return this.zszxjxgsbCfDm;
	}

	public void setZszxjxgsbCfDm(String zszxjxgsbCfDm) {
		this.zszxjxgsbCfDm = zszxjxgsbCfDm;
	}

	@Column(name = "ZSZXJXGSB_CF_DMBZ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbCfDmbz() {
		return this.zszxjxgsbCfDmbz;
	}

	public void setZszxjxgsbCfDmbz(String zszxjxgsbCfDmbz) {
		this.zszxjxgsbCfDmbz = zszxjxgsbCfDmbz;
	}

	@Column(name = "ZSZXJXGSB_CF_QM", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbCfQm() {
		return this.zszxjxgsbCfQm;
	}

	public void setZszxjxgsbCfQm(String zszxjxgsbCfQm) {
		this.zszxjxgsbCfQm = zszxjxgsbCfQm;
	}

	@Column(name = "ZSZXJXGSB_CF_QMBZ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbCfQmbz() {
		return this.zszxjxgsbCfQmbz;
	}

	public void setZszxjxgsbCfQmbz(String zszxjxgsbCfQmbz) {
		this.zszxjxgsbCfQmbz = zszxjxgsbCfQmbz;
	}

	@Column(name = "ZSZXJXGSB_CF_DP", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbCfDp() {
		return this.zszxjxgsbCfDp;
	}

	public void setZszxjxgsbCfDp(String zszxjxgsbCfDp) {
		this.zszxjxgsbCfDp = zszxjxgsbCfDp;
	}

	@Column(name = "ZSZXJXGSB_CF_DPBZ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbCfDpbz() {
		return this.zszxjxgsbCfDpbz;
	}

	public void setZszxjxgsbCfDpbz(String zszxjxgsbCfDpbz) {
		this.zszxjxgsbCfDpbz = zszxjxgsbCfDpbz;
	}

	@Column(name = "ZSZXJXGSB_CF_CJ", length = 200)
	@Size(max = 200)
	public String getZszxjxgsbCfCj() {
		return this.zszxjxgsbCfCj;
	}

	public void setZszxjxgsbCfCj(String zszxjxgsbCfCj) {
		this.zszxjxgsbCfCj = zszxjxgsbCfCj;
	}

	@Column(name = "ZSZXJXGSB_WSJ_DM", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbWsjDm() {
		return this.zszxjxgsbWsjDm;
	}

	public void setZszxjxgsbWsjDm(String zszxjxgsbWsjDm) {
		this.zszxjxgsbWsjDm = zszxjxgsbWsjDm;
	}

	@Column(name = "ZSZXJXGSB_WSJ_DMBZ")
	public byte[] getZszxjxgsbWsjDmbz() {
		return this.zszxjxgsbWsjDmbz;
	}

	public void setZszxjxgsbWsjDmbz(byte[] zszxjxgsbWsjDmbz) {
		this.zszxjxgsbWsjDmbz = zszxjxgsbWsjDmbz;
	}

	@Column(name = "ZSZXJXGSB_WSJ_QM", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbWsjQm() {
		return this.zszxjxgsbWsjQm;
	}

	public void setZszxjxgsbWsjQm(String zszxjxgsbWsjQm) {
		this.zszxjxgsbWsjQm = zszxjxgsbWsjQm;
	}

	@Column(name = "ZSZXJXGSB_WSJ_QMBZ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbWsjQmbz() {
		return this.zszxjxgsbWsjQmbz;
	}

	public void setZszxjxgsbWsjQmbz(String zszxjxgsbWsjQmbz) {
		this.zszxjxgsbWsjQmbz = zszxjxgsbWsjQmbz;
	}

	@Column(name = "ZSZXJXGSB_WSJ_DP", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbWsjDp() {
		return this.zszxjxgsbWsjDp;
	}

	public void setZszxjxgsbWsjDp(String zszxjxgsbWsjDp) {
		this.zszxjxgsbWsjDp = zszxjxgsbWsjDp;
	}

	@Column(name = "ZSZXJXGSB_WSJ_DPBZ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbWsjDpbz() {
		return this.zszxjxgsbWsjDpbz;
	}

	public void setZszxjxgsbWsjDpbz(String zszxjxgsbWsjDpbz) {
		this.zszxjxgsbWsjDpbz = zszxjxgsbWsjDpbz;
	}

	@Column(name = "ZSZXJXGSB_WSJ_QJ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbWsjQj() {
		return this.zszxjxgsbWsjQj;
	}

	public void setZszxjxgsbWsjQj(String zszxjxgsbWsjQj) {
		this.zszxjxgsbWsjQj = zszxjxgsbWsjQj;
	}

	@Column(name = "ZSZXJXGSB_YT", length = 32)
	@Size(max = 32)
	public String getZszxjxgsbYt() {
		return this.zszxjxgsbYt;
	}

	public void setZszxjxgsbYt(String zszxjxgsbYt) {
		this.zszxjxgsbYt = zszxjxgsbYt;
	}

	@Column(name = "ZSZXJXGSB_YTBZ", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbYtbz() {
		return this.zszxjxgsbYtbz;
	}

	public void setZszxjxgsbYtbz(String zszxjxgsbYtbz) {
		this.zszxjxgsbYtbz = zszxjxgsbYtbz;
	}

	@Column(name = "ZSZXJXGSB_DT_PP", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbDtPp() {
		return this.zszxjxgsbDtPp;
	}

	public void setZszxjxgsbDtPp(String zszxjxgsbDtPp) {
		this.zszxjxgsbDtPp = zszxjxgsbDtPp;
	}

	@Column(name = "ZSZXJXGSB_DT_XH", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbDtXh() {
		return this.zszxjxgsbDtXh;
	}

	public void setZszxjxgsbDtXh(String zszxjxgsbDtXh) {
		this.zszxjxgsbDtXh = zszxjxgsbDtXh;
	}

	@Column(name = "ZSZXJXGSB_GD", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbGd() {
		return this.zszxjxgsbGd;
	}

	public void setZszxjxgsbGd(String zszxjxgsbGd) {
		this.zszxjxgsbGd = zszxjxgsbGd;
	}

	@Column(name = "ZSZXJXGSB_CH", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbCh() {
		return this.zszxjxgsbCh;
	}

	public void setZszxjxgsbCh(String zszxjxgsbCh) {
		this.zszxjxgsbCh = zszxjxgsbCh;
	}

	@Column(name = "ZSZXJXGSB_BZ9", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbBz9() {
		return this.zszxjxgsbBz9;
	}

	public void setZszxjxgsbBz9(String zszxjxgsbBz9) {
		this.zszxjxgsbBz9 = zszxjxgsbBz9;
	}

	@Column(name = "ZSZXJXGSB_BZ10", length = 100)
	@Size(max = 100)
	public String getZszxjxgsbBz10() {
		return this.zszxjxgsbBz10;
	}

	public void setZszxjxgsbBz10(String zszxjxgsbBz10) {
		this.zszxjxgsbBz10 = zszxjxgsbBz10;
	}

	@Column(name = "BXFWQXZR_DJJCHZTJG_BXQX", length = 20)
	@Size(max = 20)
	public String getBxfwqxzrDjjchztjgBxqx() {
		return this.bxfwqxzrDjjchztjgBxqx;
	}

	public void setBxfwqxzrDjjchztjgBxqx(String bxfwqxzrDjjchztjgBxqx) {
		this.bxfwqxzrDjjchztjgBxqx = bxfwqxzrDjjchztjgBxqx;
	}

	@Column(name = "BXFWQXZR_DJJCHZTJG_BXQXBZ", length = 100)
	@Size(max = 100)
	public String getBxfwqxzrDjjchztjgBxqxbz() {
		return this.bxfwqxzrDjjchztjgBxqxbz;
	}

	public void setBxfwqxzrDjjchztjgBxqxbz(String bxfwqxzrDjjchztjgBxqxbz) {
		this.bxfwqxzrDjjchztjgBxqxbz = bxfwqxzrDjjchztjgBxqxbz;
	}

	@Column(name = "BXFWQXZR_FSGC_BXQX", length = 20)
	@Size(max = 20)
	public String getBxfwqxzrFsgcBxqx() {
		return this.bxfwqxzrFsgcBxqx;
	}

	public void setBxfwqxzrFsgcBxqx(String bxfwqxzrFsgcBxqx) {
		this.bxfwqxzrFsgcBxqx = bxfwqxzrFsgcBxqx;
	}

	@Column(name = "BXFWQXZR_FSGC_BXQXBZ", length = 100)
	@Size(max = 100)
	public String getBxfwqxzrFsgcBxqxbz() {
		return this.bxfwqxzrFsgcBxqxbz;
	}

	public void setBxfwqxzrFsgcBxqxbz(String bxfwqxzrFsgcBxqxbz) {
		this.bxfwqxzrFsgcBxqxbz = bxfwqxzrFsgcBxqxbz;
	}

	@Column(name = "BXFWQXZR_GLGR_BXQX", length = 20)
	@Size(max = 20)
	public String getBxfwqxzrGlgrBxqx() {
		return this.bxfwqxzrGlgrBxqx;
	}

	public void setBxfwqxzrGlgrBxqx(String bxfwqxzrGlgrBxqx) {
		this.bxfwqxzrGlgrBxqx = bxfwqxzrGlgrBxqx;
	}

	@Column(name = "BXFWQXZR_GLGR_BXQXBZ", length = 100)
	@Size(max = 100)
	public String getBxfwqxzrGlgrBxqxbz() {
		return this.bxfwqxzrGlgrBxqxbz;
	}

	public void setBxfwqxzrGlgrBxqxbz(String bxfwqxzrGlgrBxqxbz) {
		this.bxfwqxzrGlgrBxqxbz = bxfwqxzrGlgrBxqxbz;
	}

	@Column(name = "BXFWQXZR_DXGX_BXQX", length = 20)
	@Size(max = 20)
	public String getBxfwqxzrDxgxBxqx() {
		return this.bxfwqxzrDxgxBxqx;
	}

	public void setBxfwqxzrDxgxBxqx(String bxfwqxzrDxgxBxqx) {
		this.bxfwqxzrDxgxBxqx = bxfwqxzrDxgxBxqx;
	}

	@Column(name = "BXFWQXZR_DXGX_BXQXBZ", length = 100)
	@Size(max = 100)
	public String getBxfwqxzrDxgxBxqxbz() {
		return this.bxfwqxzrDxgxBxqxbz;
	}

	public void setBxfwqxzrDxgxBxqxbz(String bxfwqxzrDxgxBxqxbz) {
		this.bxfwqxzrDxgxBxqxbz = bxfwqxzrDxgxBxqxbz;
	}

	@Column(name = "BXFWQXZR_ZXGC_BXQX", length = 20)
	@Size(max = 20)
	public String getBxfwqxzrZxgcBxqx() {
		return this.bxfwqxzrZxgcBxqx;
	}

	public void setBxfwqxzrZxgcBxqx(String bxfwqxzrZxgcBxqx) {
		this.bxfwqxzrZxgcBxqx = bxfwqxzrZxgcBxqx;
	}

	@Column(name = "BXFWQXZR_ZXGC_BXQXBZ", length = 100)
	@Size(max = 100)
	public String getBxfwqxzrZxgcBxqxbz() {
		return this.bxfwqxzrZxgcBxqxbz;
	}

	public void setBxfwqxzrZxgcBxqxbz(String bxfwqxzrZxgcBxqxbz) {
		this.bxfwqxzrZxgcBxqxbz = bxfwqxzrZxgcBxqxbz;
	}

	@Column(name = "BXFWQXZR_MEMO6", length = 100)
	@Size(max = 100)
	public String getBxfwqxzrMemo6() {
		return this.bxfwqxzrMemo6;
	}

	public void setBxfwqxzrMemo6(String bxfwqxzrMemo6) {
		this.bxfwqxzrMemo6 = bxfwqxzrMemo6;
	}

	@Column(name = "BXFWQXZR_MEMO7", length = 100)
	@Size(max = 100)
	public String getBxfwqxzrMemo7() {
		return this.bxfwqxzrMemo7;
	}

	public void setBxfwqxzrMemo7(String bxfwqxzrMemo7) {
		this.bxfwqxzrMemo7 = bxfwqxzrMemo7;
	}

	@Column(name = "BXFWQXZR_MEMO8", length = 100)
	@Size(max = 100)
	public String getBxfwqxzrMemo8() {
		return this.bxfwqxzrMemo8;
	}

	public void setBxfwqxzrMemo8(String bxfwqxzrMemo8) {
		this.bxfwqxzrMemo8 = bxfwqxzrMemo8;
	}

	@Column(name = "BXFWQXZR_QTYD", length = 200)
	@Size(max = 200)
	public String getBxfwqxzrQtyd() {
		return this.bxfwqxzrQtyd;
	}

	public void setBxfwqxzrQtyd(String bxfwqxzrQtyd) {
		this.bxfwqxzrQtyd = bxfwqxzrQtyd;
	}

}
