package com.dgsoft.house.owner.model;
// Generated Aug 18, 2014 5:12:39 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * MappingCorp generated by hbm2java
 */
@Entity
@Table(name = "MAPPING_CORP", catalog = "HOUSE_OWNER_RECORD")
public class MappingCorp implements java.io.Serializable {

	private String id;
	private Business business;
	private String name;
	private String code;

	public MappingCorp() {
	}

	public MappingCorp(String id, Business business, String name, String code) {
		this.id = id;
		this.business = business;
		this.name = name;
		this.code = code;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_ID", nullable = false)
	@NotNull
	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
