package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * MortgaegeRegiste generated by hbm2java
 */
@Entity
@Table(name = "MORTGAEGE_REGISTE", catalog = "HOUSE_OWNER_RECORD")
public class MortgaegeRegiste implements java.io.Serializable {

	private String id;
	private HouseBusiness houseBusiness;
	private BigDecimal highestMountMoney;
	private String warrantScope;
	private String interestType;
	private Date mortgageDueTimeS;
	private Date mortgageDueTimeE;
	private BigDecimal mortgageArea;
	private String deptSureFact;

	public MortgaegeRegiste() {
	}

	public MortgaegeRegiste(String id, HouseBusiness houseBusiness,
			BigDecimal highestMountMoney, String warrantScope,
			String interestType, Date mortgageDueTimeS, Date mortgageDueTimeE,
			BigDecimal mortgageArea) {
		this.id = id;
		this.houseBusiness = houseBusiness;
		this.highestMountMoney = highestMountMoney;
		this.warrantScope = warrantScope;
		this.interestType = interestType;
		this.mortgageDueTimeS = mortgageDueTimeS;
		this.mortgageDueTimeE = mortgageDueTimeE;
		this.mortgageArea = mortgageArea;
	}
	public MortgaegeRegiste(String id, HouseBusiness houseBusiness,
			BigDecimal highestMountMoney, String warrantScope,
			String interestType, Date mortgageDueTimeS, Date mortgageDueTimeE,
			BigDecimal mortgageArea, String deptSureFact) {
		this.id = id;
		this.houseBusiness = houseBusiness;
		this.highestMountMoney = highestMountMoney;
		this.warrantScope = warrantScope;
		this.interestType = interestType;
		this.mortgageDueTimeS = mortgageDueTimeS;
		this.mortgageDueTimeE = mortgageDueTimeE;
		this.mortgageArea = mortgageArea;
		this.deptSureFact = deptSureFact;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_ID", nullable = false)
	@NotNull
	public HouseBusiness getHouseBusiness() {
		return this.houseBusiness;
	}

	public void setHouseBusiness(HouseBusiness houseBusiness) {
		this.houseBusiness = houseBusiness;
	}

	@Column(name = "HIGHEST_MOUNT_MONEY", nullable = false, scale = 4)
	@NotNull
	public BigDecimal getHighestMountMoney() {
		return this.highestMountMoney;
	}

	public void setHighestMountMoney(BigDecimal highestMountMoney) {
		this.highestMountMoney = highestMountMoney;
	}

	@Column(name = "WARRANT_SCOPE", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getWarrantScope() {
		return this.warrantScope;
	}

	public void setWarrantScope(String warrantScope) {
		this.warrantScope = warrantScope;
	}

	@Column(name = "INTEREST_TYPE", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getInterestType() {
		return this.interestType;
	}

	public void setInterestType(String interestType) {
		this.interestType = interestType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MORTGAGE_DUE_TIME_S", nullable = false, length = 19)
	@NotNull
	public Date getMortgageDueTimeS() {
		return this.mortgageDueTimeS;
	}

	public void setMortgageDueTimeS(Date mortgageDueTimeS) {
		this.mortgageDueTimeS = mortgageDueTimeS;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MORTGAGE_DUE_TIME_E", nullable = false, length = 19)
	@NotNull
	public Date getMortgageDueTimeE() {
		return this.mortgageDueTimeE;
	}

	public void setMortgageDueTimeE(Date mortgageDueTimeE) {
		this.mortgageDueTimeE = mortgageDueTimeE;
	}

	@Column(name = "MORTGAGE_AREA", nullable = false, scale = 4)
	@NotNull
	public BigDecimal getMortgageArea() {
		return this.mortgageArea;
	}

	public void setMortgageArea(BigDecimal mortgageArea) {
		this.mortgageArea = mortgageArea;
	}

	@Column(name = "DEPT_SURE_FACT", length = 200)
	@Size(max = 200)
	public String getDeptSureFact() {
		return this.deptSureFact;
	}

	public void setDeptSureFact(String deptSureFact) {
		this.deptSureFact = deptSureFact;
	}

}
