package com.dgsoft.house.owner.model;
// Generated Aug 24, 2015 1:17:35 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * NewHouseContractSale generated by hbm2java
 */
@Entity
@Table(name = "NEW_HOUSE_CONTRACT_SALE", catalog = "HOUSE_OWNER_RECORD")
public class NewHouseContractSale implements java.io.Serializable {

	private String id;
	private String ssyjZjlx;
	private String ssyjQzh;
	private String ssyjJgmc;
	private String ssyjDjjg;
	private String ssyjSfcz;
	private Date ssyjZlqxs;
	private Date ssyjZlqxz;
	private String ssyjBz;
	private String zhmc;
	private String khyh;
	private String zk;

	public NewHouseContractSale() {
	}

	public NewHouseContractSale(String id, Date ssyjZlqxs, Date ssyjZlqxz) {
		this.id = id;
		this.ssyjZlqxs = ssyjZlqxs;
		this.ssyjZlqxz = ssyjZlqxz;
	}
	public NewHouseContractSale(String id, String ssyjZjlx, String ssyjQzh,
			String ssyjJgmc, String ssyjDjjg, String ssyjSfcz, Date ssyjZlqxs,
			Date ssyjZlqxz, String ssyjBz, String zhmc, String khyh, String zk) {
		this.id = id;
		this.ssyjZjlx = ssyjZjlx;
		this.ssyjQzh = ssyjQzh;
		this.ssyjJgmc = ssyjJgmc;
		this.ssyjDjjg = ssyjDjjg;
		this.ssyjSfcz = ssyjSfcz;
		this.ssyjZlqxs = ssyjZlqxs;
		this.ssyjZlqxz = ssyjZlqxz;
		this.ssyjBz = ssyjBz;
		this.zhmc = zhmc;
		this.khyh = khyh;
		this.zk = zk;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "SSYJ_ZJLX", length = 32)
	@Size(max = 32)
	public String getSsyjZjlx() {
		return this.ssyjZjlx;
	}

	public void setSsyjZjlx(String ssyjZjlx) {
		this.ssyjZjlx = ssyjZjlx;
	}

	@Column(name = "SSYJ_QZH", length = 30)
	@Size(max = 30)
	public String getSsyjQzh() {
		return this.ssyjQzh;
	}

	public void setSsyjQzh(String ssyjQzh) {
		this.ssyjQzh = ssyjQzh;
	}

	@Column(name = "SSYJ_JGMC", length = 32)
	@Size(max = 32)
	public String getSsyjJgmc() {
		return this.ssyjJgmc;
	}

	public void setSsyjJgmc(String ssyjJgmc) {
		this.ssyjJgmc = ssyjJgmc;
	}

	@Column(name = "SSYJ_DJJG", length = 50)
	@Size(max = 50)
	public String getSsyjDjjg() {
		return this.ssyjDjjg;
	}

	public void setSsyjDjjg(String ssyjDjjg) {
		this.ssyjDjjg = ssyjDjjg;
	}

	@Column(name = "SSYJ_SFCZ", length = 32)
	@Size(max = 32)
	public String getSsyjSfcz() {
		return this.ssyjSfcz;
	}

	public void setSsyjSfcz(String ssyjSfcz) {
		this.ssyjSfcz = ssyjSfcz;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SSYJ_ZLQXS", nullable = false, length = 19)
	@NotNull
	public Date getSsyjZlqxs() {
		return this.ssyjZlqxs;
	}

	public void setSsyjZlqxs(Date ssyjZlqxs) {
		this.ssyjZlqxs = ssyjZlqxs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SSYJ_ZLQXZ", nullable = false, length = 19)
	@NotNull
	public Date getSsyjZlqxz() {
		return this.ssyjZlqxz;
	}

	public void setSsyjZlqxz(Date ssyjZlqxz) {
		this.ssyjZlqxz = ssyjZlqxz;
	}

	@Column(name = "SSYJ_BZ", length = 100)
	@Size(max = 100)
	public String getSsyjBz() {
		return this.ssyjBz;
	}

	public void setSsyjBz(String ssyjBz) {
		this.ssyjBz = ssyjBz;
	}

	@Column(name = "ZHMC", length = 50)
	@Size(max = 50)
	public String getZhmc() {
		return this.zhmc;
	}

	public void setZhmc(String zhmc) {
		this.zhmc = zhmc;
	}

	@Column(name = "KHYH", length = 100)
	@Size(max = 100)
	public String getKhyh() {
		return this.khyh;
	}

	public void setKhyh(String khyh) {
		this.khyh = khyh;
	}

	@Column(name = "ZK", length = 50)
	@Size(max = 50)
	public String getZk() {
		return this.zk;
	}

	public void setZk(String zk) {
		this.zk = zk;
	}

}
