package com.dgsoft.house.owner.model;
// Generated Aug 24, 2015 1:17:35 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * NewHouseContractPresale generated by hbm2java
 */
@Entity
@Table(name = "NEW_HOUSE_CONTRACT_PRESALE", catalog = "HOUSE_OWNER_RECORD")
public class NewHouseContractPresale implements java.io.Serializable {

	private String id;
	private int version;
	private String ysyjYsjg;
	private String ysyjYsxkzh;
	private String yszjjgjg;
	private String ysjzjgzhmc;
	private String yszjjgjgzh;
	private Integer mjcyclfs;
	private BigDecimal mjcyAzbfb1;
	private BigDecimal mjcyAzbfb2;
	private String mjcymemo3;
	private String mjclclmemo4;
	private BigDecimal ghsjBfb1;
	private BigDecimal ghsjFjkbfb1;
	private String ghsjMemo1;
	private String ghsjMemo3;
	private String ghsjMemo4;
	private String ghsjMemo5;
	private BigDecimal ghsjBfb2;
	private BigDecimal ghsjFjkbfb2;
	private String ghsjMemo6;
	private Integer htbayfwdjBasj;
	private String htbayfwdjBasjQtyd;
	private Integer htbayfwdjFwdjFjzrqn;
	private Integer htbayfwdjFwdjClfs;
	private BigDecimal htbayfwdjFwdjAzbfb;
	private BigDecimal htbayfwdjFwdjWfzj;
	private String htbayfwdjFwdjMemo1;
	private String qtsxSfYcd;

	public NewHouseContractPresale() {
	}

	public NewHouseContractPresale(String id, String ysyjYsjg, String ysyjYsxkzh) {
		this.id = id;
		this.ysyjYsjg = ysyjYsjg;
		this.ysyjYsxkzh = ysyjYsxkzh;
	}
	public NewHouseContractPresale(String id, String ysyjYsjg,
			String ysyjYsxkzh, String yszjjgjg, String ysjzjgzhmc,
			String yszjjgjgzh, Integer mjcyclfs, BigDecimal mjcyAzbfb1,
			BigDecimal mjcyAzbfb2, String mjcymemo3, String mjclclmemo4,
			BigDecimal ghsjBfb1, BigDecimal ghsjFjkbfb1, String ghsjMemo1,
			String ghsjMemo3, String ghsjMemo4, String ghsjMemo5,
			BigDecimal ghsjBfb2, BigDecimal ghsjFjkbfb2, String ghsjMemo6,
			Integer htbayfwdjBasj, String htbayfwdjBasjQtyd,
			Integer htbayfwdjFwdjFjzrqn, Integer htbayfwdjFwdjClfs,
			BigDecimal htbayfwdjFwdjAzbfb, BigDecimal htbayfwdjFwdjWfzj,
			String htbayfwdjFwdjMemo1, String qtsxSfYcd) {
		this.id = id;
		this.ysyjYsjg = ysyjYsjg;
		this.ysyjYsxkzh = ysyjYsxkzh;
		this.yszjjgjg = yszjjgjg;
		this.ysjzjgzhmc = ysjzjgzhmc;
		this.yszjjgjgzh = yszjjgjgzh;
		this.mjcyclfs = mjcyclfs;
		this.mjcyAzbfb1 = mjcyAzbfb1;
		this.mjcyAzbfb2 = mjcyAzbfb2;
		this.mjcymemo3 = mjcymemo3;
		this.mjclclmemo4 = mjclclmemo4;
		this.ghsjBfb1 = ghsjBfb1;
		this.ghsjFjkbfb1 = ghsjFjkbfb1;
		this.ghsjMemo1 = ghsjMemo1;
		this.ghsjMemo3 = ghsjMemo3;
		this.ghsjMemo4 = ghsjMemo4;
		this.ghsjMemo5 = ghsjMemo5;
		this.ghsjBfb2 = ghsjBfb2;
		this.ghsjFjkbfb2 = ghsjFjkbfb2;
		this.ghsjMemo6 = ghsjMemo6;
		this.htbayfwdjBasj = htbayfwdjBasj;
		this.htbayfwdjBasjQtyd = htbayfwdjBasjQtyd;
		this.htbayfwdjFwdjFjzrqn = htbayfwdjFwdjFjzrqn;
		this.htbayfwdjFwdjClfs = htbayfwdjFwdjClfs;
		this.htbayfwdjFwdjAzbfb = htbayfwdjFwdjAzbfb;
		this.htbayfwdjFwdjWfzj = htbayfwdjFwdjWfzj;
		this.htbayfwdjFwdjMemo1 = htbayfwdjFwdjMemo1;
		this.qtsxSfYcd = qtsxSfYcd;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "YSYJ_YSJG", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getYsyjYsjg() {
		return this.ysyjYsjg;
	}

	public void setYsyjYsjg(String ysyjYsjg) {
		this.ysyjYsjg = ysyjYsjg;
	}

	@Column(name = "YSYJ_YSXKZH", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getYsyjYsxkzh() {
		return this.ysyjYsxkzh;
	}

	public void setYsyjYsxkzh(String ysyjYsxkzh) {
		this.ysyjYsxkzh = ysyjYsxkzh;
	}

	@Column(name = "YSZJJGJG", length = 100)
	@Size(max = 100)
	public String getYszjjgjg() {
		return this.yszjjgjg;
	}

	public void setYszjjgjg(String yszjjgjg) {
		this.yszjjgjg = yszjjgjg;
	}

	@Column(name = "YSJZJGZHMC", length = 100)
	@Size(max = 100)
	public String getYsjzjgzhmc() {
		return this.ysjzjgzhmc;
	}

	public void setYsjzjgzhmc(String ysjzjgzhmc) {
		this.ysjzjgzhmc = ysjzjgzhmc;
	}

	@Column(name = "YSZJJGJGZH", length = 100)
	@Size(max = 100)
	public String getYszjjgjgzh() {
		return this.yszjjgjgzh;
	}

	public void setYszjjgjgzh(String yszjjgjgzh) {
		this.yszjjgjgzh = yszjjgjgzh;
	}

	@Column(name = "MJCYCLFS")
	public Integer getMjcyclfs() {
		return this.mjcyclfs;
	}

	public void setMjcyclfs(Integer mjcyclfs) {
		this.mjcyclfs = mjcyclfs;
	}

	@Column(name = "MJCY_AZBFB1", precision = 8, scale = 3)
	public BigDecimal getMjcyAzbfb1() {
		return this.mjcyAzbfb1;
	}

	public void setMjcyAzbfb1(BigDecimal mjcyAzbfb1) {
		this.mjcyAzbfb1 = mjcyAzbfb1;
	}

	@Column(name = "MJCY_AZBFB2", precision = 8, scale = 3)
	public BigDecimal getMjcyAzbfb2() {
		return this.mjcyAzbfb2;
	}

	public void setMjcyAzbfb2(BigDecimal mjcyAzbfb2) {
		this.mjcyAzbfb2 = mjcyAzbfb2;
	}

	@Column(name = "MJCYMEMO3", length = 100)
	@Size(max = 100)
	public String getMjcymemo3() {
		return this.mjcymemo3;
	}

	public void setMjcymemo3(String mjcymemo3) {
		this.mjcymemo3 = mjcymemo3;
	}

	@Column(name = "MJCLCLMEMO4", length = 100)
	@Size(max = 100)
	public String getMjclclmemo4() {
		return this.mjclclmemo4;
	}

	public void setMjclclmemo4(String mjclclmemo4) {
		this.mjclclmemo4 = mjclclmemo4;
	}

	@Column(name = "GHSJ_BFB1", precision = 8, scale = 3)
	public BigDecimal getGhsjBfb1() {
		return this.ghsjBfb1;
	}

	public void setGhsjBfb1(BigDecimal ghsjBfb1) {
		this.ghsjBfb1 = ghsjBfb1;
	}

	@Column(name = "GHSJ_FJKBFB1", precision = 8, scale = 3)
	public BigDecimal getGhsjFjkbfb1() {
		return this.ghsjFjkbfb1;
	}

	public void setGhsjFjkbfb1(BigDecimal ghsjFjkbfb1) {
		this.ghsjFjkbfb1 = ghsjFjkbfb1;
	}

	@Column(name = "GHSJ_MEMO1", length = 100)
	@Size(max = 100)
	public String getGhsjMemo1() {
		return this.ghsjMemo1;
	}

	public void setGhsjMemo1(String ghsjMemo1) {
		this.ghsjMemo1 = ghsjMemo1;
	}

	@Column(name = "GHSJ_MEMO3", length = 100)
	@Size(max = 100)
	public String getGhsjMemo3() {
		return this.ghsjMemo3;
	}

	public void setGhsjMemo3(String ghsjMemo3) {
		this.ghsjMemo3 = ghsjMemo3;
	}

	@Column(name = "GHSJ_MEMO4", length = 4)
	@Size(max = 4)
	public String getGhsjMemo4() {
		return this.ghsjMemo4;
	}

	public void setGhsjMemo4(String ghsjMemo4) {
		this.ghsjMemo4 = ghsjMemo4;
	}

	@Column(name = "GHSJ_MEMO5", length = 100)
	@Size(max = 100)
	public String getGhsjMemo5() {
		return this.ghsjMemo5;
	}

	public void setGhsjMemo5(String ghsjMemo5) {
		this.ghsjMemo5 = ghsjMemo5;
	}

	@Column(name = "GHSJ_BFB2", precision = 8, scale = 3)
	public BigDecimal getGhsjBfb2() {
		return this.ghsjBfb2;
	}

	public void setGhsjBfb2(BigDecimal ghsjBfb2) {
		this.ghsjBfb2 = ghsjBfb2;
	}

	@Column(name = "GHSJ_FJKBFB2", precision = 8, scale = 3)
	public BigDecimal getGhsjFjkbfb2() {
		return this.ghsjFjkbfb2;
	}

	public void setGhsjFjkbfb2(BigDecimal ghsjFjkbfb2) {
		this.ghsjFjkbfb2 = ghsjFjkbfb2;
	}

	@Column(name = "GHSJ_MEMO6", length = 100)
	@Size(max = 100)
	public String getGhsjMemo6() {
		return this.ghsjMemo6;
	}

	public void setGhsjMemo6(String ghsjMemo6) {
		this.ghsjMemo6 = ghsjMemo6;
	}

	@Column(name = "HTBAYFWDJ_BASJ")
	public Integer getHtbayfwdjBasj() {
		return this.htbayfwdjBasj;
	}

	public void setHtbayfwdjBasj(Integer htbayfwdjBasj) {
		this.htbayfwdjBasj = htbayfwdjBasj;
	}

	@Column(name = "HTBAYFWDJ_BASJ_QTYD", length = 150)
	@Size(max = 150)
	public String getHtbayfwdjBasjQtyd() {
		return this.htbayfwdjBasjQtyd;
	}

	public void setHtbayfwdjBasjQtyd(String htbayfwdjBasjQtyd) {
		this.htbayfwdjBasjQtyd = htbayfwdjBasjQtyd;
	}

	@Column(name = "HTBAYFWDJ_FWDJ_FJZRQN")
	public Integer getHtbayfwdjFwdjFjzrqn() {
		return this.htbayfwdjFwdjFjzrqn;
	}

	public void setHtbayfwdjFwdjFjzrqn(Integer htbayfwdjFwdjFjzrqn) {
		this.htbayfwdjFwdjFjzrqn = htbayfwdjFwdjFjzrqn;
	}

	@Column(name = "HTBAYFWDJ_FWDJ_CLFS")
	public Integer getHtbayfwdjFwdjClfs() {
		return this.htbayfwdjFwdjClfs;
	}

	public void setHtbayfwdjFwdjClfs(Integer htbayfwdjFwdjClfs) {
		this.htbayfwdjFwdjClfs = htbayfwdjFwdjClfs;
	}

	@Column(name = "HTBAYFWDJ_FWDJ_AZBFB", precision = 8, scale = 3)
	public BigDecimal getHtbayfwdjFwdjAzbfb() {
		return this.htbayfwdjFwdjAzbfb;
	}

	public void setHtbayfwdjFwdjAzbfb(BigDecimal htbayfwdjFwdjAzbfb) {
		this.htbayfwdjFwdjAzbfb = htbayfwdjFwdjAzbfb;
	}

	@Column(name = "HTBAYFWDJ_FWDJ_WFZJ", precision = 8, scale = 3)
	public BigDecimal getHtbayfwdjFwdjWfzj() {
		return this.htbayfwdjFwdjWfzj;
	}

	public void setHtbayfwdjFwdjWfzj(BigDecimal htbayfwdjFwdjWfzj) {
		this.htbayfwdjFwdjWfzj = htbayfwdjFwdjWfzj;
	}

	@Column(name = "HTBAYFWDJ_FWDJ_MEMO1", length = 100)
	@Size(max = 100)
	public String getHtbayfwdjFwdjMemo1() {
		return this.htbayfwdjFwdjMemo1;
	}

	public void setHtbayfwdjFwdjMemo1(String htbayfwdjFwdjMemo1) {
		this.htbayfwdjFwdjMemo1 = htbayfwdjFwdjMemo1;
	}

	@Column(name = "QTSX_SF_YCD", length = 50)
	@Size(max = 50)
	public String getQtsxSfYcd() {
		return this.qtsxSfYcd;
	}

	public void setQtsxSfYcd(String qtsxSfYcd) {
		this.qtsxSfYcd = qtsxSfYcd;
	}

}
