package com.dgsoft.house.owner.model;
// Generated Aug 19, 2014 4:32:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * NewHouseContract generated by hbm2java
 */
@Entity
@Table(name = "NEW_HOUSE_CONTRACT", catalog = "HOUSE_OWNER_RECORD")
public class NewHouseContract implements java.io.Serializable {

	private String id;
	private BusinessHouse businessHouse;
	private String poolMemo;
	private String housePorperty;
	private String houseFrom;
	private String compactNo;
	private Date signDate;
	private Date recordDate;

	public NewHouseContract() {
	}

	public NewHouseContract(String id, BusinessHouse businessHouse,
			String poolMemo, String housePorperty, String houseFrom,
			String compactNo, Date signDate, Date recordDate) {
		this.id = id;
		this.businessHouse = businessHouse;
		this.poolMemo = poolMemo;
		this.housePorperty = housePorperty;
		this.houseFrom = houseFrom;
		this.compactNo = compactNo;
		this.signDate = signDate;
		this.recordDate = recordDate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_ID", nullable = false)
	@NotNull
	public BusinessHouse getBusinessHouse() {
		return this.businessHouse;
	}

	public void setBusinessHouse(BusinessHouse businessHouse) {
		this.businessHouse = businessHouse;
	}

	@Column(name = "POOL_MEMO", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getPoolMemo() {
		return this.poolMemo;
	}

	public void setPoolMemo(String poolMemo) {
		this.poolMemo = poolMemo;
	}

	@Column(name = "HOUSE_PORPERTY", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getHousePorperty() {
		return this.housePorperty;
	}

	public void setHousePorperty(String housePorperty) {
		this.housePorperty = housePorperty;
	}

	@Column(name = "HOUSE_FROM", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getHouseFrom() {
		return this.houseFrom;
	}

	public void setHouseFrom(String houseFrom) {
		this.houseFrom = houseFrom;
	}

	@Column(name = "COMPACT_NO", nullable = false, length = 30)
	@NotNull
	@Size(max = 30)
	public String getCompactNo() {
		return this.compactNo;
	}

	public void setCompactNo(String compactNo) {
		this.compactNo = compactNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIGN_DATE", nullable = false, length = 19)
	@NotNull
	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORD_DATE", nullable = false, length = 19)
	@NotNull
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

}
