package com.dgsoft.house.owner.model;
// Generated Oct 15, 2014 10:41:24 AM by Hibernate Tools 4.0.0

import com.dgsoft.common.system.PersonEntity;
import org.hibernate.annotations.*;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OtherPowerCard generated by hbm2java
 */
@Entity
@Table(name = "OTHER_POWER_CARD", catalog = "HOUSE_OWNER_RECORD")
public class OtherPowerCard implements java.io.Serializable,PersonEntity {

	private String id;
    private String financialName;
    private String financialCode;
    private String financialPhone;
    private Financial.FinancialType financialType;
    private CredentialsType credentialsType;
    private CardInfo cardInfo;



	public OtherPowerCard() {
	}

    public OtherPowerCard(String financialName,String financialCode,String financialPhone,
                          Financial.FinancialType financialType,CredentialsType credentialsType) {
        this.financialName = financialName;
        this.financialCode = financialCode;
        this.financialPhone = financialPhone;
        this.financialType = financialType;
        this.credentialsType = credentialsType;
    }


    @OneToOne
    @PrimaryKeyJoinColumn
    public CardInfo getCardInfo() {
        return cardInfo;
    }

    public void setCardInfo(CardInfo cardInfo) {
        this.cardInfo = cardInfo;
    }

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)

	@NotNull
	@Size(max = 32)
    @GenericGenerator(name = "pkGenerator",
            strategy = "foreign",
            parameters = { @org.hibernate.annotations.Parameter(name = "property", value = "cardInfo") })
    @GeneratedValue(generator = "pkGenerator")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


    @Column(name = "FINANCIAL_NAME",nullable = false,length = 120)
    @Size(max = 120)
    @NotNull
    public String getFinancialName() {
        return financialName;
    }

    public void setFinancialName(String financialName) {
        this.financialName = financialName;
    }

    @Column(name = "FINANCIAL_CODE",nullable = true,length = 100)
    @Size(max = 100)
    public String getFinancialCode() {
        return financialCode;
    }

    public void setFinancialCode(String financialCode) {
        this.financialCode = financialCode;
    }

    @Column(name = "FINANCIAL_PHONE",nullable = true,length = 15)
    @Size(max = 15)
    public String getFinancialPhone() {
        return financialPhone;
    }

    public void setFinancialPhone(String financialPhone) {
        this.financialPhone = financialPhone;
    }

    @Override
    @Enumerated(EnumType.STRING)
    @Column(name = "ID_TYPE",nullable = true,length = 32)
    public CredentialsType getCredentialsType() {
        return credentialsType;
    }

    @Override
    public void setCredentialsType(CredentialsType credentialsType) {
        this.credentialsType = credentialsType;
    }

    @Enumerated(EnumType.STRING)
    @Column(name="FINANCIAL_TYPE",nullable = false,length = 20)
    @NotNull
    public Financial.FinancialType getFinancialType() {
        return financialType;
    }

    public void setFinancialType(Financial.FinancialType financialType) {
        this.financialType = financialType;
    }


    @Override
    @Transient
    public String getCredentialsNumber() {
        return getFinancialCode();
    }

    @Override
    @Transient
    public void setCredentialsNumber(String credentialsNumber) {
        setFinancialCode(credentialsNumber);
    }

    @Override
    @Transient
    public String getPersonName() {
        return getFinancialName();
    }

    @Override
    @Transient
    public void setPersonName(String personName) {
        setFinancialName(personName);
    }
}
