package com.dgsoft.house.owner.model;
// Generated Oct 15, 2014 10:41:24 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OtherPowerCard generated by hbm2java
 */
@Entity
@Table(name = "OTHER_POWER_CARD", catalog = "HOUSE_OWNER_RECORD")
public class OtherPowerCard implements java.io.Serializable {

	private String id;
	private MakeCard makeCardByCard;
	private MakeCard makeCardByOwnerCard;
    private String financialName;
    private String financialCode;
    private String financialPhone;

	public OtherPowerCard() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD", nullable = false)
	@NotNull
	public MakeCard getMakeCardByCard() {
		return this.makeCardByCard;
	}

	public void setMakeCardByCard(MakeCard makeCardByCard) {
		this.makeCardByCard = makeCardByCard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OWNER_CARD", nullable = false)
	@NotNull
	public MakeCard getMakeCardByOwnerCard() {
		return this.makeCardByOwnerCard;
	}

	public void setMakeCardByOwnerCard(MakeCard makeCardByOwnerCard) {
		this.makeCardByOwnerCard = makeCardByOwnerCard;
	}

    @Column(name = "FINANCIAL_NAME",nullable = false,length = 120)
    @Size(max = 120)
    @NotNull
    public String getFinancialName() {
        return financialName;
    }

    public void setFinancialName(String financialName) {
        this.financialName = financialName;
    }

    @Column(name = "FINANCIAL_CODE",nullable = false,length = 100)
    @Size(max = 100)
    @NotNull
    public String getFinancialCode() {
        return financialCode;
    }

    public void setFinancialCode(String financialCode) {
        this.financialCode = financialCode;
    }

    @Column(name = "FINANCIAL_PHONE",nullable = true,length = 15)
    @Size(max = 15)
    public String getFinancialPhone() {
        return financialPhone;
    }

    public void setFinancialPhone(String financialPhone) {
        this.financialPhone = financialPhone;
    }
}
