package com.dgsoft.house.owner.model;
// Generated Oct 11, 2014 3:13:15 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ProjectRecord generated by hbm2java
 */
@Entity
@Table(name = "PROJECT_RECORD", catalog = "HOUSE_OWNER_RECORD", uniqueConstraints = @UniqueConstraint(columnNames = "PROJECT_CODE"))
public class ProjectRecord implements java.io.Serializable {

	private ProjectSellCard projectSellCard;
	private String projectCode;
	private Set<ProjectRecordStore> projectRecordStores = new HashSet<ProjectRecordStore>(0);

	public ProjectRecord() {
	}



	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SALE_CARD")
	public ProjectSellCard getProjectSellCard() {
		return this.projectSellCard;
	}

	public void setProjectSellCard(ProjectSellCard projectSellCard) {
		this.projectSellCard = projectSellCard;
	}

    @Id
	@Column(name = "PROJECT_CODE", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectRecord")
	public Set<ProjectRecordStore> getProjectRecordStores() {
		return this.projectRecordStores;
	}

	public void setProjectRecordStores(
			Set<ProjectRecordStore> projectRecordStores) {
		this.projectRecordStores = projectRecordStores;
	}
}
