package com.dgsoft.house.owner.model;
// Generated Oct 11, 2014 3:13:15 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ProjectRecordStore generated by hbm2java
 */
@Entity
@Table(name = "PROJECT_RECORD_STORE", catalog = "HOUSE_OWNER_RECORD")
public class ProjectRecordStore implements java.io.Serializable {

	private String id;
	private BusinessProject businessProject;
	private ProjectRecord projectRecord;
	private String frame;
	private String cabinet;
	private String box;

	public ProjectRecordStore() {
	}

	public ProjectRecordStore(String id, BusinessProject businessProject,
			ProjectRecord projectRecord, String frame, String cabinet,
			String box) {
		this.id = id;
		this.businessProject = businessProject;
		this.projectRecord = projectRecord;
		this.frame = frame;
		this.cabinet = cabinet;
		this.box = box;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS", nullable = false)
	@NotNull
	public BusinessProject getBusinessProject() {
		return this.businessProject;
	}

	public void setBusinessProject(BusinessProject businessProject) {
		this.businessProject = businessProject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RECORD", nullable = false)
	@NotNull
	public ProjectRecord getProjectRecord() {
		return this.projectRecord;
	}

	public void setProjectRecord(ProjectRecord projectRecord) {
		this.projectRecord = projectRecord;
	}

	@Column(name = "FRAME", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getFrame() {
		return this.frame;
	}

	public void setFrame(String frame) {
		this.frame = frame;
	}

	@Column(name = "CABINET", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getCabinet() {
		return this.cabinet;
	}

	public void setCabinet(String cabinet) {
		this.cabinet = cabinet;
	}

	@Column(name = "BOX", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getBox() {
		return this.box;
	}

	public void setBox(String box) {
		this.box = box;
	}

}
