package com.dgsoft.common.system.model;
// Generated Apr 28, 2013 11:02:59 AM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE")
public class Employee implements java.io.Serializable {

    private String id;
    private Organization organization;
    private String Job;
    private Date joinDate;
    private String EMail;
    private String password;
    private boolean enable;
    private String memo;
    private Set<Role> roles = new HashSet<Role>(0);
    private String phone;
    private String credentialsType;
    private String credentialsNumber;
    private String name;

    public Employee() {
        enable = true;
    }

    public Employee(String id) {
        enable = true;
        this.id = id;
    }


    public Employee(Organization organization) {
        enable = true;
        this.organization = organization;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 32)
    @NotNull
    @Size(max = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ORGANIZATION")
    @NotNull
    public Organization getOrganization() {
        return this.organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }


    @Column(name = "JOB", length = 32)
    @Size(max = 32)
    public String getJob() {
        return this.Job;
    }

    public void setJob(String Job) {
        this.Job = Job;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "JOIN_DATE", nullable = false, length = 19, columnDefinition = "DATETIME")
    @NotNull
    public Date getJoinDate() {
        return this.joinDate;
    }

    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    @Column(name = "E_MAIL", length = 20)
    @Size(max = 20)
    public String getEMail() {
        return this.EMail;
    }

    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    @Column(name = "PASSWORD", length = 100)
    @Size(max = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "ENABLE", nullable = false)
    public boolean isEnable() {
        return enable;
    }

    public void setEnable(boolean enable) {
        this.enable = enable;
    }

    @Column(name = "MEMO", length = 100)
    @Size(max = 100)
    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    @ManyToMany(fetch = FetchType.LAZY, targetEntity = Role.class)
    @JoinTable(name = "ROLE_EMP", joinColumns = @JoinColumn(name = "EMP_ID"), inverseJoinColumns = @JoinColumn(name = "ROL_ID"))
    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumns({
//            @JoinColumn(name = "CREDENTIALS_TYPE", referencedColumnName = "CREDENTIALS_TYPE", nullable = false),
//            @JoinColumn(name = "CREDENTIALS_NUMBER", referencedColumnName = "CREDENTIALS_NUMBER", nullable = false)})
//    @NotNull
//    public Person getPerson() {
//        return this.person;
//    }
//
//    public void setPerson(Person person) {
//        this.person = person;
//    }


    @Column(name = "PHONE", length = 20)
    @Size(max = 20)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "CREDENTIALS_TYPE", length = 32)
    @Size(max = 32)
    public String getCredentialsType() {
        return this.credentialsType;
    }

    public void setCredentialsType(String credentialsType) {
        this.credentialsType = credentialsType;
    }

    @Column(name = "CREDENTIALS_NUMBER", length = 100)
    @Size(max = 100)
    public String getCredentialsNumber() {
        return this.credentialsNumber;
    }

    public void setCredentialsNumber(String credentialsNumber) {
        this.credentialsNumber = credentialsNumber;
    }

    @Column(name = "NAME", nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof Employee)) {
            return false;
        }


        if (((Employee)obj).getId().equals(getId())){
            return true;
        }else
            return false;
    }

    @Override
    public int hashCode(){
        return getId().hashCode();
    }

}
