package com.dgsoft.common.system.model;
// Generated Aug 19, 2014 10:57:39 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * FileSubscribe generated by hbm2java
 */
@Entity
@Table(name = "FILE_SUBSCRIBE", catalog = "DB_PLAT_SYSTEM", uniqueConstraints = @UniqueConstraint(columnNames = {
		"NAME", "BUSINESS_DEFINE"}))
public class FileSubscribe implements java.io.Serializable {

	private String id;
	private BusinessDefine businessDefine;
	private String name;
	private boolean required;
	private int priority;
	private String type;

	public FileSubscribe() {
	}

	public FileSubscribe(String id, BusinessDefine businessDefine, String name,
			boolean required, int priority, String type) {
		this.id = id;
		this.businessDefine = businessDefine;
		this.name = name;
		this.required = required;
		this.priority = priority;
		this.type = type;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUSINESS_DEFINE", nullable = false)
	@NotNull
	public BusinessDefine getBusinessDefine() {
		return this.businessDefine;
	}

	public void setBusinessDefine(BusinessDefine businessDefine) {
		this.businessDefine = businessDefine;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "REQUIRED", nullable = false)
	public boolean isRequired() {
		return this.required;
	}

	public void setRequired(boolean required) {
		this.required = required;
	}

	@Column(name = "PRIORITY", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "TYPE", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
