package com.dgsoft.common.system.model;
// Generated Aug 19, 2014 10:57:39 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "PERSON", catalog = "DB_PLAT_SYSTEM")
public class Person implements java.io.Serializable {

    public enum Sex{
       FEMALE, MALE;
    }

	private PersonId id;
	private String name;
	private String credentialsOrgan;
	private String sex;
	private String ethnic;
	private Date dateOfBirth;
	private String address;
	private Date readTime;

	public Person() {
	}

	public Person(PersonId id, String name, Date readTime) {
		this.id = id;
		this.name = name;
		this.readTime = readTime;
	}


	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "credentialsType", column = @Column(name = "CREDENTIALS_TYPE", nullable = false, length = 32)),
			@AttributeOverride(name = "credentialsNumber", column = @Column(name = "CREDENTIALS_NUMBER", nullable = false, length = 100))})
	@NotNull
	public PersonId getId() {
		return this.id;
	}

	public void setId(PersonId id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CREDENTIALS_ORGAN", length = 100)
	@Size(max = 100)
	public String getCredentialsOrgan() {
		return this.credentialsOrgan;
	}

	public void setCredentialsOrgan(String credentialsOrgan) {
		this.credentialsOrgan = credentialsOrgan;
	}

	@Column(name = "SEX", length = 32)
	@Size(max = 32)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "ETHNIC", length = 20)
	@Size(max = 20)
	public String getEthnic() {
		return this.ethnic;
	}

	public void setEthnic(String ethnic) {
		this.ethnic = ethnic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_BIRTH", length = 19)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "ADDRESS", length = 200)
	@Size(max = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "READ_TIME", nullable = false, length = 19)
	@NotNull
	public Date getReadTime() {
		return this.readTime;
	}

	public void setReadTime(Date readTime) {
		this.readTime = readTime;
	}



}
