SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS CITY_CONSTRUCT.AGENT;
DROP TABLE IF EXISTS CITY_CONSTRUCT.JOIN_PERSON;
DROP TABLE IF EXISTS CITY_CONSTRUCT.CORP_AND_PERSON;
DROP TABLE IF EXISTS CITY_CONSTRUCT.CONSTRUCT_PERSON_REG;
DROP TABLE IF EXISTS CITY_CONSTRUCT.BUSINESS_EMP;
DROP TABLE IF EXISTS CITY_CONSTRUCT.PROJECT_REG;
DROP TABLE IF EXISTS CITY_CONSTRUCT.MAKE_CARD;
DROP TABLE IF EXISTS CITY_CONSTRUCT.PROJECT_LICENSE;
DROP TABLE IF EXISTS CITY_CONSTRUCT.BUSINESS_LOG;
DROP TABLE IF EXISTS CITY_CONSTRUCT.CONSTRUCT_PERSON;
DROP TABLE IF EXISTS CITY_CONSTRUCT.CONSTRUCT_PERSON_INFO;
DROP TABLE IF EXISTS CITY_CONSTRUCT.CORP_REG_BUSINESS;
DROP TABLE IF EXISTS CITY_CONSTRUCT.CORP_INFO_BUSINESS;
DROP TABLE IF EXISTS CITY_CONSTRUCT.BUSINESS;
DROP TABLE IF EXISTS CITY_CONSTRUCT.CONSTRUCT_CORP;
DROP TABLE IF EXISTS CITY_CONSTRUCT.JOIN_CORP;
DROP TABLE IF EXISTS CITY_CONSTRUCT.CONSTRUCT_CORP_INFO;
DROP TABLE IF EXISTS CITY_CONSTRUCT.CONSTRUCT_CORP_REG;
DROP TABLE IF EXISTS CITY_CONSTRUCT.RIGHT_CORP_TYPE;
DROP TABLE IF EXISTS CITY_CONSTRUCT.RIGHT_PROJECT_JOIN_TYPE;
DROP TABLE IF EXISTS CITY_CONSTRUCT.PERSON_RIGHT_TYPE;
DROP TABLE IF EXISTS CITY_CONSTRUCT.PROJECT;
DROP TABLE IF EXISTS CITY_CONSTRUCT.PROJECT_INFO;




/* Create Tables */

CREATE TABLE CITY_CONSTRUCT.AGENT
(
	ID varchar(32) NOT NULL,
	DEPARTMENT varchar(16),
	POST varchar(16),
	TEL varchar(16),
	BUSINESS varchar(32) NOT NULL,
	TYPE varchar(16),
	NAME varchar(64) NOT NULL,
	IDENTIFY_NUMBER varchar(32),
	IDENTIFY_TYPE varchar(16),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.BUSINESS
(
	ID varchar(32) NOT NULL,
	VERSION int NOT NULL,
	SOURCE varchar(20) NOT NULL,
	MEMO varchar(256),
	DEFINE_NAME varchar(50) NOT NULL,
	DEFINE_ID varchar(32) NOT NULL,
	DEFINE_VERSION int NOT NULL,
	DATA_TIME timestamp NOT NULL,
	-- 运行中
	-- 已完成
	-- 已删除
	STATUS varchar(8) NOT NULL COMMENT '运行中
已完成
已删除',
	REG boolean NOT NULL,
	REG_TIME datetime,
	SEARCH_KEY varchar(16384),
	SUMMARY text,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.BUSINESS_EMP
(
	ID varchar(32) NOT NULL,
	TYPE varchar(16) NOT NULL,
	EMP_CODE varchar(32) NOT NULL,
	EMP_NAME varchar(64) NOT NULL,
	OPER_TIME datetime NOT NULL,
	BUSINESS varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.BUSINESS_LOG
(
	ID bigint NOT NULL AUTO_INCREMENT,
	-- CREATE_BIZ
	TYPE varchar(16) NOT NULL COMMENT 'CREATE_BIZ',
	EMP_CODE varchar(32) NOT NULL,
	EMP_NAME varchar(64) NOT NULL,
	OPER_TIME datetime NOT NULL,
	COMMENTS varchar(512),
	BUSINESS varchar(32) NOT NULL,
	TASK_NAME varchar(128),
	TASK_DESCRIPTION varchar(512),
	TASK_ID bigint,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.CONSTRUCT_CORP
(
	CORP_CODE varchar(32) NOT NULL,
	CORP varchar(32) NOT NULL,
	DATA_TIME timestamp NOT NULL,
	VERSION int NOT NULL,
	ENABLE boolean NOT NULL,
	PRIMARY KEY (CORP_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.CONSTRUCT_CORP_INFO
(
	ID varchar(32) NOT NULL,
	NAME varchar(128) NOT NULL,
	REG_ID_TYPE varchar(16) NOT NULL,
	REG_ID_NUMBER varchar(32) NOT NULL,
	OWNER_NAME varchar(64) NOT NULL,
	OWNER_ID_TYPE varchar(16) NOT NULL,
	OWNER_ID_NUMBER varchar(32) NOT NULL,
	ADDRESS varchar(256),
	TEL varchar(16),
	CORP_CODE varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.CONSTRUCT_CORP_REG
(
	ID varchar(32) NOT NULL,
	CORP_TYPE varchar(16) NOT NULL,
	REG_DATE date,
	REG_DATE_TO date,
	LEVEL varchar(8) NOT NULL,
	LEVEL_NUMBER varchar(32) NOT NULL,
	STATUS varchar(16) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.CONSTRUCT_PERSON
(
	PERSON_CODE varchar(32) NOT NULL,
	ENABLE boolean NOT NULL,
	VERSION int NOT NULL,
	DATA_TIME timestamp NOT NULL,
	PERSON_INFO varchar(32) NOT NULL,
	PRIMARY KEY (PERSON_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.CONSTRUCT_PERSON_INFO
(
	ID varchar(32) NOT NULL,
	NAME varchar(64) NOT NULL,
	IDENTIFY_TYPE varchar(16) NOT NULL,
	IDENTIFY_NUMBER varchar(32) NOT NULL,
	TEL varchar(16),
	SEX varchar(6),
	BIRTH_DATE date,
	NATION varchar(16),
	NATIONALITY varchar(16),
	ADDRESS varchar(256),
	REG_ADDRESS varchar(16),
	TITLE varchar(8),
	PERSON_CODE varchar(32) NOT NULL,
	BUSINESS varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.CONSTRUCT_PERSON_REG
(
	ID varchar(32) NOT NULL,
	PERSON varchar(32) NOT NULL,
	REG_NUMBER varchar(32),
	BUSINESS varchar(32) NOT NULL,
	STATUS varchar(16) NOT NULL,
	REG_RIGHT varchar(32),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.CORP_AND_PERSON
(
	CORP_CODE varchar(32) NOT NULL,
	PERSON_REG varchar(32) NOT NULL,
	PRIMARY KEY (CORP_CODE, PERSON_REG)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.CORP_INFO_BUSINESS
(
	ID varchar(32) NOT NULL,
	BEFORE_INFO varchar(32),
	AFTER_INFO varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.CORP_REG_BUSINESS
(
	ID varchar(32) NOT NULL,
	BEFORE_REG varchar(32),
	AFTER_REG varchar(32) NOT NULL,
	BUSINESS varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.JOIN_CORP
(
	ID varchar(32) NOT NULL,
	CORP varchar(32) NOT NULL,
	OUTSIDE_TEAM_FILE varchar(32),
	PROJECT_CODE varchar(32) NOT NULL,
	PROJECT varchar(32) NOT NULL,
	CORP_CODE varchar(32) NOT NULL,
	OUT_LEVEL boolean NOT NULL,
	OUT_LEVEL_FILE varchar(32),
	CORP_INFO varchar(32) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT ONE_CORP_REG_UNIQUE UNIQUE (CORP, PROJECT, CORP_INFO)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.JOIN_PERSON
(
	ID varchar(32) NOT NULL,
	CORP varchar(32) NOT NULL,
	PERSON varchar(32) NOT NULL,
	JOIN_TYPE varchar(16) NOT NULL,
	PERSON_CODE varchar(32) NOT NULL,
	LEVEL varchar(8),
	JOB varchar(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.MAKE_CARD
(
	ID varchar(32) NOT NULL,
	ENABLE boolean NOT NULL,
	LICENSING_GOV varchar(32) NOT NULL,
	REG_DATE date NOT NULL,
	REG_NUMBER varchar(32) NOT NULL,
	YEAR_NUMBER varchar(4) NOT NULL,
	MEMO varchar(512),
	BUSINESS varchar(32) NOT NULL,
	TYPE varchar(16) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.PERSON_RIGHT_TYPE
(
	ID varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	ENABLE boolean NOT NULL,
	PRI int NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.PROJECT
(
	PROJECT_CODE varchar(32) NOT NULL,
	PROJECT varchar(32) NOT NULL,
	STATUS varchar(8) NOT NULL,
	DATA_TIME timestamp NOT NULL,
	VERSION int NOT NULL,
	PRIMARY KEY (PROJECT_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.PROJECT_INFO
(
	ID varchar(32) NOT NULL,
	PROJECT_CODE varchar(32) NOT NULL,
	NAME varchar(256) NOT NULL,
	ADDRESS varchar(512),
	TYPE varchar(32),
	PROPERTY varchar(32),
	AREA decimal(18,2),
	GROUND_FLOOR_COUNT int,
	UNDER_FLOOR_COUNT int,
	BEGIN_DATE date,
	COMPLETED_DATE date,
	TENDER varchar(32),
	STRUCTURE varchar(32),
	COSTS decimal(18,2),
	MAIN_PROJECT boolean,
	MAIN_PROJECT_LEVEL varchar(16),
	MAIN_PROJECT_FILE varchar(32),
	MEMO varchar(512),
	REG_TIME datetime,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.PROJECT_LICENSE
(
	ID varchar(32) NOT NULL,
	PROJECT_CODE varchar(32),
	PROJECT varchar(32) NOT NULL,
	STATUS varchar(8) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.PROJECT_REG
(
	ID varchar(32) NOT NULL,
	PROJECT varchar(32) NOT NULL,
	PROJECT_CODE varchar(32) NOT NULL,
	STATUS varchar(16) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.RIGHT_CORP_TYPE
(
	CORP_TYPE varchar(16) NOT NULL,
	TYPE varchar(32) NOT NULL,
	PRIMARY KEY (CORP_TYPE, TYPE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CITY_CONSTRUCT.RIGHT_PROJECT_JOIN_TYPE
(
	JOIN_TYPE varchar(16) NOT NULL,
	CORP_TYPE varchar(32) NOT NULL,
	PRIMARY KEY (JOIN_TYPE, CORP_TYPE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE CITY_CONSTRUCT.CONSTRUCT_PERSON_REG
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES CITY_CONSTRUCT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.BUSINESS_EMP
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES CITY_CONSTRUCT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.AGENT
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES CITY_CONSTRUCT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.PROJECT_REG
	ADD FOREIGN KEY (ID)
	REFERENCES CITY_CONSTRUCT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.PROJECT_LICENSE
	ADD FOREIGN KEY (ID)
	REFERENCES CITY_CONSTRUCT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.BUSINESS_LOG
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES CITY_CONSTRUCT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CONSTRUCT_PERSON_INFO
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES CITY_CONSTRUCT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CORP_INFO_BUSINESS
	ADD FOREIGN KEY (ID)
	REFERENCES CITY_CONSTRUCT.BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CORP_AND_PERSON
	ADD FOREIGN KEY (CORP_CODE)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_CORP (CORP_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CONSTRUCT_CORP
	ADD FOREIGN KEY (CORP)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_CORP_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CORP_INFO_BUSINESS
	ADD FOREIGN KEY (BEFORE_INFO)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_CORP_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CORP_INFO_BUSINESS
	ADD FOREIGN KEY (AFTER_INFO)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_CORP_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.JOIN_CORP
	ADD FOREIGN KEY (CORP_INFO)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_CORP_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.JOIN_CORP
	ADD FOREIGN KEY (CORP)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_CORP_REG (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CORP_REG_BUSINESS
	ADD FOREIGN KEY (BEFORE_REG)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_CORP_REG (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CORP_REG_BUSINESS
	ADD FOREIGN KEY (AFTER_REG)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_CORP_REG (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CONSTRUCT_PERSON_REG
	ADD FOREIGN KEY (PERSON)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_PERSON_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CONSTRUCT_PERSON
	ADD FOREIGN KEY (PERSON_INFO)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_PERSON_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.JOIN_PERSON
	ADD FOREIGN KEY (PERSON)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_PERSON_REG (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CORP_AND_PERSON
	ADD FOREIGN KEY (PERSON_REG)
	REFERENCES CITY_CONSTRUCT.CONSTRUCT_PERSON_REG (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CORP_REG_BUSINESS
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES CITY_CONSTRUCT.CORP_INFO_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.JOIN_PERSON
	ADD FOREIGN KEY (CORP)
	REFERENCES CITY_CONSTRUCT.JOIN_CORP (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.RIGHT_CORP_TYPE
	ADD FOREIGN KEY (TYPE)
	REFERENCES CITY_CONSTRUCT.PERSON_RIGHT_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.RIGHT_PROJECT_JOIN_TYPE
	ADD FOREIGN KEY (CORP_TYPE)
	REFERENCES CITY_CONSTRUCT.PERSON_RIGHT_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.CONSTRUCT_PERSON_REG
	ADD FOREIGN KEY (REG_RIGHT)
	REFERENCES CITY_CONSTRUCT.PERSON_RIGHT_TYPE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.PROJECT
	ADD FOREIGN KEY (PROJECT)
	REFERENCES CITY_CONSTRUCT.PROJECT_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.PROJECT_LICENSE
	ADD FOREIGN KEY (PROJECT)
	REFERENCES CITY_CONSTRUCT.PROJECT_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.PROJECT_REG
	ADD FOREIGN KEY (PROJECT)
	REFERENCES CITY_CONSTRUCT.PROJECT_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.JOIN_CORP
	ADD FOREIGN KEY (PROJECT)
	REFERENCES CITY_CONSTRUCT.PROJECT_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITY_CONSTRUCT.MAKE_CARD
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES CITY_CONSTRUCT.PROJECT_LICENSE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



