SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS CONTRACT.ARTICLE;
DROP TABLE IF EXISTS CONTRACT.ARTICLE_CATEGORY;
DROP TABLE IF EXISTS CONTRACT.BUSINESS_POOL;
DROP TABLE IF EXISTS CONTRACT.CONTRACT_NUMBER;
DROP TABLE IF EXISTS CONTRACT.CONTRACT_OWNER;
DROP TABLE IF EXISTS CONTRACT.CONTRACT_TEMPLATE;
DROP TABLE IF EXISTS CONTRACT.SALE_PROXY_PERSON;
DROP TABLE IF EXISTS CONTRACT.HOUSE_CONTRACT;
DROP TABLE IF EXISTS CONTRACT.NUMBER_POOL;
DROP TABLE IF EXISTS CONTRACT.PROJECT_NUMBER_POOL;
DROP TABLE IF EXISTS CONTRACT.SCHOOL_AREA;
DROP TABLE IF EXISTS CONTRACT.SELL_AREA;
DROP TABLE IF EXISTS CONTRACT.SYSTEM_PARAM;




/* Create Tables */

CREATE TABLE CONTRACT.ARTICLE
(
	ID varchar(32) NOT NULL,
	MAIN_TITLE varchar(256) NOT NULL,
	SUB_TITLE varchar(512),
	CATEGORY varchar(32) NOT NULL,
	PUBLISH_TIME timestamp NOT NULL,
	CONTEXT longtext,
	FIX_TOP boolean NOT NULL,
	VIEW_TYPE varchar(16) NOT NULL,
	RESOURCE longblob,
	COVER_IMG longtext,
	SUMMARY varchar(1024),
	ON_FLOW boolean NOT NULL,
	RESOURCE_CONTENT_TYPE varchar(32),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.ARTICLE_CATEGORY
(
	ID varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	PRI int NOT NULL,
	TYPE varchar(16) NOT NULL,
	DESCRIPTION varchar(512),
	PRIMARY KEY (ID),
	UNIQUE (NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.BUSINESS_POOL
(
	ID varchar(32) NOT NULL,
	NAME varchar(50) NOT NULL,
	ID_TYPE varchar(32) NOT NULL,
	ID_NO varchar(100) NOT NULL,
	POOL_AREA decimal(19,4),
	RELATION varchar(32),
	PERC varchar(10),
	PHONE varchar(15),
	LEGAL_PERSON varchar(50),
	CONTRACT varchar(32) NOT NULL,
	LEGAL_TYPE varchar(20),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.CONTRACT_NUMBER
(
	CONTRACT_NUMBER varchar(32) NOT NULL,
	CONTRACT_ID varchar(32) NOT NULL,
	OWNER_NAME varchar(64),
	PASSWORD varchar(64),
	PRIMARY KEY (CONTRACT_NUMBER)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.CONTRACT_OWNER
(
	ID varchar(32) NOT NULL,
	NAME varchar(50) NOT NULL,
	ID_TYPE varchar(32) NOT NULL,
	ID_NO varchar(100) NOT NULL,
	PHONE varchar(15),
	ROOT_ADDRESS varchar(50),
	LEGAL_PERSON varchar(50),
	ADDRESS varchar(200),
	LEGAL_TYPE varchar(20),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.CONTRACT_TEMPLATE
(
	PROJECT_ID varchar(32) NOT NULL,
	TYPE varchar(20) NOT NULL,
	CONTRACT longtext NOT NULL,
	CONTRACT_VERSION int NOT NULL,
	ID varchar(32) NOT NULL,
	NAME varchar(50) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.HOUSE_CONTRACT
(
	ID varchar(32) NOT NULL,
	GROUP_ID varchar(32) NOT NULL,
	PROJECT_ID varchar(32),
	HOUSE_CODE varchar(32) NOT NULL,
	TYPE varchar(20) NOT NULL,
	CREATE_TIME timestamp NOT NULL,
	STATUS varchar(20) NOT NULL,
	ATTACH_EMP_ID varchar(32) NOT NULL,
	CONTRACT_PRICE decimal(21,3) NOT NULL,
	ATTACH_EMP_NAME varchar(50) NOT NULL,
	CONTRACT longtext,
	CONTRACT_VERSION int,
	VERSION int NOT NULL,
	POOL_TYPE varchar(32) NOT NULL,
	HOUSE_DESCRIPTION varchar(512) NOT NULL,
	SALE_PAY_TYPE varchar(32) NOT NULL,
	PROJECT_CER_NUMBER varchar(100),
	PRIMARY KEY (ID),
	UNIQUE (HOUSE_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.NUMBER_POOL
(
	TYPE varchar(50) NOT NULL,
	NUMBER bigint NOT NULL,
	PROJECT_CODE varchar(32) NOT NULL,
	ID varchar(32) NOT NULL,
	VERSION bigint NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT TYPE_PROJECT_UNIQUE UNIQUE (TYPE, PROJECT_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.PROJECT_NUMBER_POOL
(
	PROJECT_CODE varchar(32) NOT NULL,
	NUMBER bigint NOT NULL,
	PRIMARY KEY (PROJECT_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.SALE_PROXY_PERSON
(
	ID varchar(32) NOT NULL,
	ID_NO varchar(100) NOT NULL,
	ID_TYPE varchar(32) NOT NULL,
	NAME varchar(50) NOT NULL,
	PHONE varchar(15) NOT NULL,
	CREATE_DATE timestamp NOT NULL,
	DISABLED boolean NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.SCHOOL_AREA
(
	ID varchar(32) NOT NULL,
	NAME varchar(64) NOT NULL,
	DISTRICT varchar(32) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.SELL_AREA
(
	ID varchar(32) NOT NULL,
	NAME varchar(64) NOT NULL,
	DISTRICT varchar(32) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.SYSTEM_PARAM
(
	ID varchar(32) NOT NULL,
	VALUE longtext NOT NULL,
	DESCRIPTION varchar(512),
	TYPE varchar(16) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE CONTRACT.ARTICLE
	ADD FOREIGN KEY (CATEGORY)
	REFERENCES CONTRACT.ARTICLE_CATEGORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRACT.CONTRACT_NUMBER
	ADD FOREIGN KEY (CONTRACT_ID)
	REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRACT.CONTRACT_OWNER
	ADD FOREIGN KEY (ID)
	REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRACT.BUSINESS_POOL
	ADD FOREIGN KEY (CONTRACT)
	REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRACT.SALE_PROXY_PERSON
	ADD FOREIGN KEY (ID)
	REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRACT.NUMBER_POOL
	ADD FOREIGN KEY (PROJECT_CODE)
	REFERENCES CONTRACT.PROJECT_NUMBER_POOL (PROJECT_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



