

CREATE OR REPLACE VIEW I_T_HOUSEINFO AS
SELECT concat(hr.HOUSE_CODE, '210682') as HOUSEINFO_ID,hr.HOUSE_CODE as RIGHTHOUSE_ID, h.BUILD_CODE as RIGHTBUILDING_ID,
  hr.HOUSE_CODE as HOUSENUM,h.UNIT_NUMBER as BDCDYH, '210682' as REGIONCODE,
  h.DEVELOPER_NAME as DEVELOPER,h.PROJECT_NAME PROJECTNAME,

  CASE hri.HOUSE_PORPERTY
  when '812' then '0002'
  when '87' then '0003'
  when '816' then '0004'
  when '4083' then '0005'
  when '813' then '0006'
  when '814' then '0007'
  when '86' then '0010'
  else '0008' end as SALEHOUSE_TYPE,

  h.ADDRESS as HOUSESIT,h.BUILD_NAME as BUILDADDR, h.BUILD_NO as BUILDNUM, h.HOUSE_UNIT_NAME as UNITNUM,
  h.HOUSE_ORDER as ROOMNUM,h.FLOOR_COUNT as TOTALFLOORS,h.IN_FLOOR_NAME as RIGHTFLOORS,  h.HOUSE_AREA as HOUSEAREA,
  h.USE_AREA as HOUSENETAREA, h.COMM_AREA as HOUSESHAREAREA,

  CASE h.USE_TYPE
  WHEN  'DWELLING_KEY' THEN '0001'
  ELSE '0143' end as PURPOSECODE,

  CASE h.STRUCTURE
  WHEN '88' THEN 1
  WHEN '822' THEN 2
  WHEN '89' THEN 2
  WHEN '823' THEN 3
  WHEN '915' THEN 3
  WHEN '824' THEN 4
  WHEN '825' THEN 5
  ELSE 6 end as BUILDINGSTRUTURE,


  CASE h.HOUSE_TYPE
  WHEN 'GOV_GROUP_HOUSE' THEN 1
  WHEN 'GOV_SALE_HOUSE' THEN 2
  WHEN 'GOV_RENT' THEN 3
  WHEN 'GROUP_HOUSE' THEN 4
  WHEN 'LIMIT_PRICE_HOUSE' THEN 5
  WHEN 'PUBLIC_RENT' THEN 6

  ELSE 99 END as HOUSENATURECODE,


  h.COMPLETE_DATE as COMPLETEDYEAR, '210682' as  COLLECTIONCITYCODE, 0 as BLZT,
  concat(h.MAP_NUMBER,"-",h.BLOCK_NO,"-",h.BUILD_NO,'-',h.HOUSE_ORDER) as RESIDENCE_NUMBER

FROM HOUSE_RECORD hr left join HOUSE h on h.ID = hr.HOUSE left join BUSINESS_HOUSE bh on bh.AFTER_HOUSE = h.ID left join OWNER_BUSINESS ob on ob.ID = bh.BUSINESS_ID  left join HOUSE_REG_INFO hri on hri.ID = h.REG_INFO
WHERE hr.HOUSE_STATUS <> 'DESTROY' and ((ob.SOURCE <> 'BIZ_IMPORT') or (ob.DEFINE_ID = 'OR'));


CREATE OR REPLACE VIEW I_T_HOUSESYQDJ AS
SELECT hr.HOUSE_CODE as HOUSESYQDJ_ID,bh.BUSINESS_ID as DATASEQ,concat(hr.HOUSE_CODE, '210682') as HOUSEINFO_ID,hr.HOUSE_CODE as RIGHTHOUSE_ID,
  '210682' as REGIONCODE, hr.HOUSE_CODE as HOUSENUM,bh.BUSINESS_ID as RIGHTACCEPT_ID,null OWNERSHIPGETTYPE,
  (select GROUP_CONCAT(s_c.NUMBER) FROM CARD s_c WHERE s_c.TYPE = 'OWNER_RSHIP' and s_c.BUSINESS_ID = bh.BUSINESS_ID) as CERTCODE,
  (select GROUP_CONCAT(s_po.NAME) FROM POWER_OWNER s_po left JOIN HOUSE_OWNER s_ho on s_ho.POOL = s_po.ID WHERE s_po.OLD = FALSE and s_ho.HOUSE = h.ID and s_po.TYPE IN ('OWNER','INIT','PREPARE') ) as OWNER,
  (select GROUP_CONCAT(s_po.ID_NO) FROM POWER_OWNER s_po left JOIN HOUSE_OWNER s_ho on s_ho.POOL = s_po.ID WHERE s_po.OLD = FALSE and s_ho.HOUSE = h.ID and s_po.TYPE IN ('OWNER','INIT','PREPARE') ) as IDCERTIFICATECODE,

  case h.POOL_MEMO when  'TOGETHER_OWNER' then '1' when 'SHARE_OWNER' then '2' ELSE '3' end as COOWNERSHIP,
   ob.REG_TIME as REGISTDATE,'210682' as COLLECTIONCITYCODE,
  concat(h.MAP_NUMBER,"-",h.BLOCK_NO,"-",h.BUILD_NO,'-',h.HOUSE_ORDER) as RESIDENCE_NUMBER

FROM HOUSE_RECORD hr left join HOUSE h on h.ID = hr.HOUSE left join BUSINESS_HOUSE bh on bh.AFTER_HOUSE = h.ID
  left JOIN OWNER_BUSINESS ob on ob.ID = bh.BUSINESS_ID
WHERE hr.HOUSE_STATUS in ('OWNERED','INIT_REG') and ((ob.SOURCE <> 'BIZ_IMPORT') or (ob.DEFINE_ID = 'OR'));




CREATE OR REPLACE VIEW I_T_COMPACT AS
SELECT ob.ID as COMPACT_ID,concat(h.HOUSE_CODE, '210681') as HOUSEINFO_ID ,
  h.HOUSE_CODE as RIGHTHOUSE_ID, hc.CONTRACT_NUMBER as COMPACT_CODE,
  IF((ob.STATUS = 'COMPLETE'),6000 ,4000) as COMPACT_STATUS,
  IF((hc.TYPE = 'NOW_SELL'),3001,2001) as COMPACT_TYPE,
  si.SUM_PRICE as COMPACT_PRICE,h.DEVELOPER_CODE as REALTYDEALER_ID,h.PROJECT_CODE as PROJECT_ID,
  h.HOUSE_CODE as HOUSE_CODE,h.HOUSE_ORDER as HOUSE_NUMBER,h.ADDRESS as HOUSE_ADDRESS, h.HOUSE_AREA as COMPACT_AREA,
  CASE h.USE_TYPE
  WHEN  'DWELLING_KEY' THEN '0001'
  ELSE '0143' end as PLANNING_USE,
  hc.PROJECT_RSHIP_NUMBER as COMPACT_NAME,'210681' as REGIONCODE,
  (select GROUP_CONCAT(s_po.NAME) FROM POWER_OWNER s_po left JOIN HOUSE_OWNER s_ho on s_ho.POOL = s_po.ID WHERE s_po.OLD = FALSE and s_ho.HOUSE = h.ID and s_po.TYPE = 'CONTRACT' ) as BUYER_NAME,
  (select GROUP_CONCAT(s_po.ID_NO) FROM POWER_OWNER s_po left JOIN HOUSE_OWNER s_ho on s_ho.POOL = s_po.ID WHERE s_po.OLD = FALSE and s_ho.HOUSE = h.ID and s_po.TYPE = 'CONTRACT' ) as BUYER_CODE,
  ob.APPLY_TIME as COMPACT_SIGNDATE, ob.REG_TIME as COMPACT_DATE,hc.CONTRACT_NUMBER as COMPACTRECORD_CODE,
  ob.REG_TIME as COMPACTRECORD_DATE , ob.APPLY_TIME as CREATE_DATE,'1' as STATUS_FLAG,
  h.DEVELOPER_NAME as REALTYDEALER_NAME,
  concat(h.MAP_NUMBER,"-",h.BLOCK_NO,"-",h.BUILD_NO,'-',h.HOUSE_ORDER) as RESIDENCE_NUMBER,h.PROJECT_NAME as PROJECTNAMES

FROM BUSINESS_HOUSE bh LEFT JOIN OWNER_BUSINESS ob on ob.ID = bh.BUSINESS_ID
  LEFT JOIN HOUSE h on h.ID = bh.AFTER_HOUSE
  LEFT JOIN HOUSE_CONTRACT hc on hc.ID = h.SALE_CONTRACT
  LEFT JOIN SALE_INFO si on si.HOUSEID = h.ID
WHERE ob.DEFINE_ID = 'WP42' and ob.STATUS in ('COMPLETE','RUNNING');


DROP TABLE IF EXISTS HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY;

CREATE TABLE HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY
(
	SJTS_LOG_ID int  NOT NULL AUTO_INCREMENT,
	TABLE_NAME VARCHAR(1) NULL,
  OUT_HOUSE_ID VARCHAR(38) NULL,
	HOUSE_CODE VARCHAR(32) NOT NULL,
  STATE int NOT NULL,
  ADD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UNIQUE_I_SJTS_LOG_HISTORY_HOUSE_CODE UNIQUE (HOUSE_CODE,TABLE_NAME,STATE),
	PRIMARY KEY (SJTS_LOG_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



DROP TRIGGER IF EXISTS HOUSE_OWNER_RECORD.UPDATE_RECORD;
DROP TRIGGER IF EXISTS HOUSE_OWNER_RECORD.INSERT_RECORD;

DELIMITER $$

CREATE TRIGGER HOUSE_OWNER_RECORD.INSERT_RECORD
AFTER INSERT ON HOUSE_OWNER_RECORD.HOUSE_RECORD
FOR EACH ROW
BEGIN

  IF NEW.HOUSE_STATUS = 'DESTROY' THEN
    DELETE FROM HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY WHERE HOUSE_CODE = NEW.HOUSE_CODE and STATE = 1;
    INSERT HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY(HOUSE_CODE,TABLE_NAME,STATE,OUT_HOUSE_ID) VALUES(NEW.HOUSE_CODE,'A',1,concat(NEW.HOUSE_CODE,'210682')),(NEW.HOUSE_CODE,'B',1,concat(NEW.HOUSE_CODE,'210682'));
  ELSE
    DELETE FROM HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY WHERE HOUSE_CODE = NEW.HOUSE_CODE and STATE = 0;

    INSERT HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY(HOUSE_CODE,TABLE_NAME,STATE,OUT_HOUSE_ID) VALUES(NEW.HOUSE_CODE,'A',0,concat(NEW.HOUSE_CODE,'210682')),(NEW.HOUSE_CODE,'B',0,concat(NEW.HOUSE_CODE,'210682')),(NEW.HOUSE_CODE,'C',0,concat(NEW.HOUSE_CODE,'210682'));
  END IF;


END $$

CREATE TRIGGER HOUSE_OWNER_RECORD.UPDATE_RECORD
AFTER UPDATE ON HOUSE_OWNER_RECORD.HOUSE_RECORD
FOR EACH ROW
BEGIN
  IF NEW.HOUSE_STATUS = 'DESTROY' THEN
    DELETE FROM HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY WHERE HOUSE_CODE = NEW.HOUSE_CODE and STATE = 1;
    INSERT HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY(HOUSE_CODE,TABLE_NAME,STATE,OUT_HOUSE_ID) VALUES(NEW.HOUSE_CODE,'A',1,concat(NEW.HOUSE_CODE,'210682')),(NEW.HOUSE_CODE,'B',1,concat(NEW.HOUSE_CODE,'210682'));
  ELSE
    DELETE FROM HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY WHERE HOUSE_CODE = NEW.HOUSE_CODE and STATE = 0;

    INSERT HOUSE_OWNER_RECORD.I_SJTS_LOG_HISTORY(HOUSE_CODE,TABLE_NAME,STATE,OUT_HOUSE_ID) VALUES(NEW.HOUSE_CODE,'A',0,concat(NEW.HOUSE_CODE,'210682')),(NEW.HOUSE_CODE,'B',0,concat(NEW.HOUSE_CODE,'210682')),(NEW.HOUSE_CODE,'C',0,concat(NEW.HOUSE_CODE,'210682'));
  END IF;
END $$


DELIMITER ;


CREATE OR REPLACE VIEW C_T_HOUSEINTO AS
SELECT islh.SJTS_LOG_ID,islh.OUT_HOUSE_ID as HOUSEINFO_ID,hr.HOUSE_CODE as RIGHTHOUSE_ID, h.BUILD_CODE as RIGHTBUILDING_ID,
  hr.HOUSE_CODE as HOUSENUM,h.UNIT_NUMBER as BDCDYH, '210682' as REGIONCODE,
  h.DEVELOPER_NAME as DEVELOPER,h.PROJECT_NAME PROJECTNAME,

  CASE hri.HOUSE_PORPERTY
  when '812' then '0002'
  when '87' then '0003'
  when '816' then '0004'
  when '4083' then '0005'
  when '813' then '0006'
  when '814' then '0007'
  when '86' then '0010'
  else '0008' end as SALEHOUSE_TYPE,

  h.ADDRESS as HOUSESIT,h.BUILD_NAME as BUILDADDR, h.BUILD_NO as BUILDNUM, h.HOUSE_UNIT_NAME as UNITNUM,
  h.HOUSE_ORDER as ROOMNUM,h.FLOOR_COUNT as TOTALFLOORS,h.IN_FLOOR_NAME as RIGHTFLOORS,  h.HOUSE_AREA as HOUSEAREA,
  h.USE_AREA as HOUSENETAREA, h.COMM_AREA as HOUSESHAREAREA,

  CASE h.USE_TYPE
  WHEN  'DWELLING_KEY' THEN '0001'
  ELSE '0143' end as PURPOSECODE,

  CASE h.STRUCTURE
  WHEN '88' THEN 1
  WHEN '822' THEN 2
  WHEN '89' THEN 2
  WHEN '823' THEN 3
  WHEN '915' THEN 3
  WHEN '824' THEN 4
  WHEN '825' THEN 5
  ELSE 6 end as BUILDINGSTRUTURE,

  CASE h.HOUSE_TYPE
  WHEN 'GOV_GROUP_HOUSE' THEN 1
  WHEN 'GOV_SALE_HOUSE' THEN 2
  WHEN 'GOV_RENT' THEN 3
  WHEN 'GROUP_HOUSE' THEN 4
  WHEN 'LIMIT_PRICE_HOUSE' THEN 5
  WHEN 'PUBLIC_RENT' THEN 6

  ELSE 99 END as HOUSENATURECODE,


  h.COMPLETE_DATE as COMPLETEDYEAR, '210682' as  COLLECTIONCITYCODE, 0 as BLZT,
  concat(h.MAP_NUMBER,"-",h.BLOCK_NO,"-",h.BUILD_NO,'-',h.HOUSE_ORDER) as RESIDENCE_NUMBER

FROM I_SJTS_LOG_HISTORY islh left join HOUSE_RECORD hr on hr.HOUSE_CODE = islh.HOUSE_CODE
left join HOUSE h on h.ID = hr.HOUSE left join HOUSE_REG_INFO hri on hri.ID = h.REG_INFO
WHERE hr.HOUSE_STATUS <> 'DESTROY' and islh.TABLE_NAME = 'A'  and islh.STATE = 0;



CREATE OR REPLACE VIEW C_T_HOUSESYQDJ AS
SELECT islh.SJTS_LOG_ID, hr.HOUSE_CODE as HOUSESYQDJ_ID,bh.BUSINESS_ID as DATASEQ,concat(hr.HOUSE_CODE, '210682') as HOUSEINFO_ID,hr.HOUSE_CODE as RIGHTHOUSE_ID,
  '210682' as REGIONCODE, hr.HOUSE_CODE as HOUSENUM,bh.BUSINESS_ID as RIGHTACCEPT_ID,null OWNERSHIPGETTYPE,
  c.NUMBER as CERTCODE,
  (select GROUP_CONCAT(s_po.NAME) FROM POWER_OWNER s_po left JOIN HOUSE_OWNER s_ho on s_ho.POOL = s_po.ID WHERE s_po.OLD = FALSE and s_ho.HOUSE = h.ID and s_po.TYPE IN ('OWNER','INIT','PREPARE') ) as OWNER,
  (select GROUP_CONCAT(s_po.ID_NO) FROM POWER_OWNER s_po left JOIN HOUSE_OWNER s_ho on s_ho.POOL = s_po.ID WHERE s_po.OLD = FALSE and s_ho.HOUSE = h.ID and s_po.TYPE IN ('OWNER','INIT','PREPARE') ) as IDCERTIFICATECODE,

  case h.POOL_MEMO when  'TOGETHER_OWNER' then '1' when 'SHARE_OWNER' then '2' ELSE '3' end as COOWNERSHIP,
   ob.REG_TIME as REGISTDATE,'210682' as COLLECTIONCITYCODE,
  concat(h.MAP_NUMBER,"-",h.BLOCK_NO,"-",h.BUILD_NO,'-',h.HOUSE_ORDER) as RESIDENCE_NUMBER

FROM I_SJTS_LOG_HISTORY islh left join HOUSE_RECORD hr on hr.HOUSE_CODE = islh.HOUSE_CODE
  left join HOUSE h on h.ID = hr.HOUSE left join BUSINESS_HOUSE bh on bh.AFTER_HOUSE = h.ID
  left JOIN OWNER_BUSINESS ob on ob.ID = bh.BUSINESS_ID
  left JOIN CARD c on (c.BUSINESS_ID = bh.BUSINESS_ID and c.TYPE = 'OWNER_RSHIP')
WHERE hr.HOUSE_STATUS in ('OWNERED','INIT_REG')  and islh.TABLE_NAME = 'B'  and islh.STATE = 0;


CREATE OR REPLACE VIEW C_T_COMPACT AS
SELECT islh.SJTS_LOG_ID,
  ob.ID as COMPACT_ID,concat(h.HOUSE_CODE, '210681') as HOUSEINFO_ID ,
                      h.HOUSE_CODE as RIGHTHOUSE_ID, hc.CONTRACT_NUMBER as COMPACT_CODE,
                      IF((ob.STATUS = 'COMPLETE'),6000 ,4000) as COMPACT_STATUS,
                      IF((hc.TYPE = 'NOW_SELL'),3001,2001) as COMPACT_TYPE,
                      si.SUM_PRICE as COMPACT_PRICE,h.DEVELOPER_CODE as REALTYDEALER_ID,h.PROJECT_CODE as PROJECT_ID,
                      h.HOUSE_CODE as HOUSE_CODE,h.HOUSE_ORDER as HOUSE_NUMBER,h.ADDRESS as HOUSE_ADDRESS, h.HOUSE_AREA as COMPACT_AREA,
                      CASE h.USE_TYPE
                      WHEN  'DWELLING_KEY' THEN '0001'
                      ELSE '0143' end as PLANNING_USE,
                      hc.PROJECT_RSHIP_NUMBER as COMPACT_NAME,'210681' as REGIONCODE,
                      (select GROUP_CONCAT(s_po.NAME) FROM POWER_OWNER s_po left JOIN HOUSE_OWNER s_ho on s_ho.POOL = s_po.ID WHERE s_po.OLD = FALSE and s_ho.HOUSE = h.ID and s_po.TYPE = 'CONTRACT' ) as BUYER_NAME,
                      (select GROUP_CONCAT(s_po.ID_NO) FROM POWER_OWNER s_po left JOIN HOUSE_OWNER s_ho on s_ho.POOL = s_po.ID WHERE s_po.OLD = FALSE and s_ho.HOUSE = h.ID and s_po.TYPE = 'CONTRACT' ) as BUYER_CODE,
                      ob.APPLY_TIME as COMPACT_SIGNDATE, ob.REG_TIME as COMPACT_DATE,hc.CONTRACT_NUMBER as COMPACTRECORD_CODE,
                      ob.REG_TIME as COMPACTRECORD_DATE , ob.APPLY_TIME as CREATE_DATE,'1' as STATUS_FLAG,
                      h.DEVELOPER_NAME as REALTYDEALER_NAME,
                      concat(h.MAP_NUMBER,"-",h.BLOCK_NO,"-",h.BUILD_NO,'-',h.HOUSE_ORDER) as RESIDENCE_NUMBER,h.PROJECT_NAME as PROJECTNAMES

FROM I_SJTS_LOG_HISTORY islh left join BUSINESS_HOUSE bh on bh.HOUSE_CODE = islh.HOUSE_CODE
  LEFT JOIN OWNER_BUSINESS ob on ob.ID = bh.BUSINESS_ID
  LEFT JOIN HOUSE h on h.ID = bh.AFTER_HOUSE
  LEFT JOIN HOUSE_CONTRACT hc on hc.ID = h.SALE_CONTRACT
  LEFT JOIN SALE_INFO si on si.HOUSEID = h.ID
WHERE ob.DEFINE_ID = 'WP42' and ob.STATUS in ('COMPLETE','RUNNING') and islh.TABLE_NAME = 'C'  and islh.STATE = 0;



