SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE BUSINESS_HOUSE_MONEY;
DROP TABLE BUSINESS_PERSION;
DROP TABLE CARD;
DROP TABLE HOUSE_POOL;
DROP TABLE BUSINESS_HOUSE;
DROP TABLE BUSINESS_POOL;
DROP TABLE CHANGE_REGISTE;
DROP TABLE CLOSE_HOUSE;
DROP TABLE FIRST_REGISTE;
DROP TABLE HOUSE_CLOSE_CANCEL;
DROP TABLE MORTGAEGE_REGISTE;
DROP TABLE NEW_HOUSE_CONTRACT;
DROP TABLE SALE_INFO;
DROP TABLE HOUSE_BUSINESS;
DROP TABLE OTHER_REGISTE;
DROP TABLE PROJECT_BUSINESS;
DROP TABLE REASON;
DROP TABLE BUSINESS;
DROP TABLE PROJECT_HISTORY;
DROP TABLE LAND_INFO;




/* Create Tables */

CREATE TABLE BUSINESS
(
	-- 倒库导入原库的NO
	ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	-- 倒库导入原库的NO
	BEFORE_BUSINESS_ID VARCHAR(32) COMMENT '倒库导入原库的NO',
	SOURCE INT NOT NULL,
	RECORD_TIME TIMESTAMP NOT NULL,
	ADD_BIZ_TIME TIMESTAMP,
	PROCESS_MESSAGE VARCHAR(400),
	ENABLE BOOLEAN NOT NULL,
	MAPPING_COMPANY VARCHAR(32),
	EVALUATE_COMPANY VARCHAR(32),
	MEMO VARCHAR(200),
	VERSION INT,
	PRIMARY KEY (ID)
);


CREATE TABLE BUSINESS_HOUSE
(
	ID VARCHAR(32) NOT NULL,
	BUILD_NO VARCHAR(32) NOT NULL,
	HOUSE_NUMBER VARCHAR(50),
	HOUSE_ORDER VARCHAR(20) NOT NULL,
	HOUSE_UNIT_NAME VARCHAR(20),
	IN_FLOOR_NAME VARCHAR(50),
	HOUSE_AREA DECIMAL(18,3) NOT NULL,
	PREPARE_AREA DECIMAL(18,3),
	TEMP_AREA DECIMAL(18,3),
	USE_AREA DECIMAL(18,3),
	COMM_AREA DECIMAL(18,3),
	SHINE_AREA DECIMAL(18,10),
	LOFT_AREA DECIMAL(18,3),
	COMM_PARAM DECIMAL(18,3),
	PRIVATE_AREA DECIMAL(18,3),
	HOUSE_STATE INT NOT NULL,
	DOOR_NO VARCHAR(20),
	HOUSE_TYPE VARCHAR(32),
	USE_TYPE VARCHAR(32),
	HOUSE_PORPERTY VARCHAR(32),
	STRUCTURE VARCHAR(32),
	KNOT_SIZE VARCHAR(32),
	HOUSE_FROM VARCHAR(32),
	HOUSE_STATION VARCHAR(200),
	LAND_INFO VARCHAR(32),
	EAST_WALL VARCHAR(32),
	WEST_WALL VARCHAR(32),
	SOUTH_WALL VARCHAR(32),
	NORTH_WALL VARCHAR(32),
	MAP_TIME TIMESTAMP,
	DIRECTION VARCHAR(32),
	INIT_REGISTER BOOLEAN NOT NULL,
	FIRMLY_POWER BOOLEAN NOT NULL,
	OUT_PLAN BOOLEAN NOT NULL,
	SUM_PRICE DECIMAL(18,3),
	PAY_TYPE VARCHAR(32),
	OWNER_NAME VARCHAR(32),
	ID_NO VARCHAR(100),
	ID_TYPE VARCHAR(32),
	BUSINESS_ID VARCHAR(32) NOT NULL,
	TYPE VARCHAR(10),
	PROJECT_ID VARCHAR(32) NOT NULL,
	LAND_ID VARCHAR(32) NOT NULL,
	CONSTRAINT PK_HOUSE PRIMARY KEY (ID)
);


CREATE TABLE BUSINESS_HOUSE_MONEY
(
	ID VARCHAR(32) NOT NULL,
	MONEY_TYPE_ID VARCHAR(20),
	SHOULD_MONEY DECIMAL(18,3),
	FACT_MONEY DECIMAL(18,3),
	CHARGE_DETAILS VARCHAR(200),
	MEMO VARCHAR(200),
	-- 倒库导入原库的NO
	BUSINESS VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	PRIMARY KEY (ID)
);


CREATE TABLE BUSINESS_PERSION
(
	ID VARCHAR(32) NOT NULL,
	ID_NO VARCHAR(100) NOT NULL,
	ID_TYPE VARCHAR(32) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	TYPE VARCHAR(10) NOT NULL,
	-- 倒库导入原库的NO
	BUSINESS_ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	PRIMARY KEY (ID)
);


CREATE TABLE BUSINESS_POOL
(
	ID VARCHAR(32) NOT NULL,
	-- 原共有权人，现共有权人，备案共有权人
	TYPE VARCHAR(10) NOT NULL COMMENT '原共有权人，现共有权人，备案共有权人',
	NAME VARCHAR(50) NOT NULL,
	ID_TYPE VARCHAR(32) NOT NULL,
	ID_NO VARCHAR(100) NOT NULL,
	RELATION VARCHAR(32) NOT NULL,
	POOL_AREA DECIMAL(19,4) NOT NULL,
	PERC VARCHAR(10) NOT NULL,
	MEMO VARCHAR(100),
	BUSINESS_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);


-- 记录业务关联时，权证号，和同同，法律文件号，等相关证件的正价编号
CREATE TABLE CARD
(
	ID VARCHAR(32) NOT NULL,
	TYPE VARCHAR(10) NOT NULL,
	NUMBER VARCHAR(100) NOT NULL,
	-- 倒库导入原库的NO
	BUSINESS_ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	PRIMARY KEY (ID)
) COMMENT = '记录业务关联时，权证号，和同同，法律文件号，等相关证件的正价编号';


CREATE TABLE CHANGE_REGISTE
(
	EVALUATE_CORP_NAME VARCHAR(60),
	EVALUATE_CORP_N0 VARCHAR(32),
	ASSESSMENT_PRICE DECIMAL(19,4) NOT NULL,
	ID VARCHAR(32) NOT NULL,
	BUSINESS_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE CLOSE_HOUSE
(
	ID VARCHAR(32) NOT NULL,
	CLOSE_DOWN_CLOUR VARCHAR(32) NOT NULL,
	ACTION VARCHAR(100),
	CLOSE_DATE DATETIME NOT NULL,
	TO_DATE DATETIME,
	BUSINESS_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE FIRST_REGISTE
(
	MAPPING_COR_NAME VARCHAR(60) NOT NULL,
	MAPPING_COR_NO VARCHAR(32) NOT NULL,
	ID VARCHAR(32) NOT NULL,
	BUSINESS_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE HOUSE_BUSINESS
(
	ID VARCHAR(32) NOT NULL,
	-- 倒库导入原库的NO
	BUSINESS_ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	PRIMARY KEY (ID)
);


CREATE TABLE HOUSE_CLOSE_CANCEL
(
	ID VARCHAR(32) NOT NULL,
	CANCEL_DATE DATETIME NOT NULL,
	BUSINESS_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE HOUSE_POOL
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	ID_TYPE VARCHAR(32) NOT NULL,
	ID_NO VARCHAR(100) NOT NULL,
	RELATION VARCHAR(32) NOT NULL,
	POOL_AREA DECIMAL(19,4) NOT NULL,
	PERC VARCHAR(10) NOT NULL,
	MEMO VARCHAR(100),
	HOUSE_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE LAND_INFO
(
	ID VARCHAR(32) NOT NULL,
	LAND_CARD_NO VARCHAR(50),
	NUMBER VARCHAR(50),
	LAND_PROPERTY VARCHAR(32),
	BEGIN_USE_TIME TIMESTAMP,
	END_USE_TIME TIMESTAMP,
	AREA DECIMAL(18,3),
	LAND_GET_MODE VARCHAR(32),
	MEMO VARCHAR(200),
	CONSTRAINT PK_LANDINFO PRIMARY KEY (ID)
);


CREATE TABLE MORTGAEGE_REGISTE
(
	EVALUATE_CORP_NAME VARCHAR(60),
	EVALUATE_CORP_N0 VARCHAR(32),
	ASSESSMENT_PRICE DECIMAL(19,4) NOT NULL,
	HIGHEST_MOUNT_MONEY DECIMAL(19,4) NOT NULL,
	WARRANT_SCOPE VARCHAR(100) NOT NULL,
	INTEREST_TYPE VARCHAR(32) NOT NULL,
	MORTGAGE_DUE_TIME_S DATETIME NOT NULL,
	MORTGAGE_DUE_TIME_E DATETIME NOT NULL,
	MORTGAGE_AREA DECIMAL(19,4) NOT NULL,
	DEPT_SURE_FACT VARCHAR(200),
	BUSINESS_ID VARCHAR(32) NOT NULL
);


CREATE TABLE NEW_HOUSE_CONTRACT
(
	ID VARCHAR(32) NOT NULL,
	POOL_MEMO VARCHAR(32) NOT NULL,
	HOUSE_PORPERTY VARCHAR(32) NOT NULL,
	HOUSE_FROM VARCHAR(32) NOT NULL,
	COMPACT_NO VARCHAR(30) NOT NULL,
	SIGN_DATE DATETIME NOT NULL,
	RECORD_DATE DATETIME NOT NULL,
	BUSINESS_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE OTHER_REGISTE
(
	ID VARCHAR(32) NOT NULL,
	-- 倒库导入原库的NO
	BUSINESS_ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	PRIMARY KEY (ID)
);


CREATE TABLE PROJECT_BUSINESS
(
	ID VARCHAR(32) NOT NULL,
	-- 倒库导入原库的NO
	BUSINESS_ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	PROJECT_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE PROJECT_HISTORY
(
	ID VARCHAR(32) NOT NULL,
	PROJECT_NO VARCHAR(32) NOT NULL,
	SECTION_NAME VARCHAR(100) NOT NULL,
	SECTION_NO VARCHAR(32) NOT NULL,
	DISTRICT_NO VARCHAR(32) NOT NULL,
	LAND_ID VARCHAR(32) NOT NULL,
	PROJECT_NAME VARCHAR(32),
	PRIMARY KEY (ID)
);


-- 记录注销原因，更正前，更正后，变更前，变更后等事由信息
CREATE TABLE REASON
(
	ID VARCHAR(32) NOT NULL,
	TYPE VARCHAR(10) NOT NULL,
	REASON VARCHAR(200) NOT NULL,
	-- 倒库导入原库的NO
	BUISINESS_ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	PRIMARY KEY (ID)
) COMMENT = '记录注销原因，更正前，更正后，变更前，变更后等事由信息';


CREATE TABLE SALE_INFO
(
	ID VARCHAR(32) NOT NULL,
	PAY_TYPE VARCHAR(32),
	SUM_PRICE DECIMAL(19,4) NOT NULL,
	BUSINESS_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE BUSINESS
	ADD FOREIGN KEY (BEFORE_BUSINESS_ID)
	REFERENCES BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_HOUSE_MONEY
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_PERSION
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CARD
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_BUSINESS
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OTHER_REGISTE
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJECT_BUSINESS
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE REASON
	ADD FOREIGN KEY (BUISINESS_ID)
	REFERENCES BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_POOL
	ADD FOREIGN KEY (HOUSE_ID)
	REFERENCES BUSINESS_HOUSE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_HOUSE
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_POOL
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CHANGE_REGISTE
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CLOSE_HOUSE
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FIRST_REGISTE
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_CLOSE_CANCEL
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MORTGAEGE_REGISTE
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE NEW_HOUSE_CONTRACT
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SALE_INFO
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_HOUSE
	ADD FOREIGN KEY (LAND_ID)
	REFERENCES LAND_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJECT_HISTORY
	ADD FOREIGN KEY (LAND_ID)
	REFERENCES LAND_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_HOUSE
	ADD FOREIGN KEY (PROJECT_ID)
	REFERENCES PROJECT_HISTORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJECT_BUSINESS
	ADD FOREIGN KEY (PROJECT_ID)
	REFERENCES PROJECT_HISTORY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



