
-- ROLE
INSERT DB_PLAT_SYSTEM.ROLE(ID,NAME,DESCRIPTION, PRIORITY) VALUES("check","产权业务审核","",20);
INSERT DB_PLAT_SYSTEM.ROLE(ID,NAME,DESCRIPTION, PRIORITY) VALUES("Money","产权业务收费","",20);
INSERT DB_PLAT_SYSTEM.ROLE(ID,NAME,DESCRIPTION, PRIORITY) VALUES("RecordFile","产权业务登薄","",20);
INSERT DB_PLAT_SYSTEM.ROLE(ID,NAME,DESCRIPTION, PRIORITY) VALUES("PrintCard","产权业务缮证","",20);
INSERT DB_PLAT_SYSTEM.ROLE(ID,NAME,DESCRIPTION, PRIORITY) VALUES("RecordSave","产权业务归档","",20);
