SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS HOUSE_INFO.CONTRACT_MORTGAGE;
DROP TABLE IF EXISTS HOUSE_INFO.NEW_HOUSE_CONTRACT_PRESALE;
DROP TABLE IF EXISTS HOUSE_INFO.NEW_HOUSE_CONTRACT_SALE;
DROP TABLE IF EXISTS HOUSE_INFO.HOUSE_COMMERCI_CONTRACT;
DROP TABLE IF EXISTS HOUSE_INFO.DEMPLOYEE;
DROP TABLE IF EXISTS HOUSE_INFO.PROJECT_BUILD_PROCESS;
DROP TABLE IF EXISTS HOUSE_INFO.POOL_OWNER;
DROP TABLE IF EXISTS HOUSE_INFO.OLDHOUSECONTRACT;
DROP TABLE IF EXISTS HOUSE_INFO.HOUSE_CONTRACT;
DROP TABLE IF EXISTS HOUSE_INFO.HOUSE;
DROP TABLE IF EXISTS HOUSE_INFO.GRID_BLOCK;
DROP TABLE IF EXISTS HOUSE_INFO.GRID_ROW;
DROP TABLE IF EXISTS HOUSE_INFO.HOUSE_GRID_TITLE;
DROP TABLE IF EXISTS HOUSE_INFO.BUILD_GRID_MAP;
DROP TABLE IF EXISTS HOUSE_INFO.BUILD;
DROP TABLE IF EXISTS HOUSE_INFO.PROJECT;
DROP TABLE IF EXISTS HOUSE_INFO.DEVELOPER;
DROP TABLE IF EXISTS HOUSE_INFO.EVALUATE_CORPORATION;
DROP TABLE IF EXISTS HOUSE_INFO.SMSUBCOMPANY;
DROP TABLE IF EXISTS HOUSE_INFO.MCOMPANY;
DROP TABLE IF EXISTS HOUSE_INFO.SELL_EMPLOYEE;
DROP TABLE IF EXISTS HOUSE_INFO.HOUSE_SELL_COMPANY;
DROP TABLE IF EXISTS HOUSE_INFO.ORG_ATTACH_ACTION;
DROP TABLE IF EXISTS HOUSE_INFO.MAPPING_CORPORATION;
DROP TABLE IF EXISTS HOUSE_INFO.ATTACH_CORPORATION;
DROP TABLE IF EXISTS HOUSE_INFO.EMPLOYEE_ATTACH_ACTION;
DROP TABLE IF EXISTS HOUSE_INFO.ATTACH_EMPLOYEE;
DROP TABLE IF EXISTS HOUSE_INFO.OWNER_GROUP;
DROP TABLE IF EXISTS HOUSE_INFO.POOL_BUILD;
DROP TABLE IF EXISTS HOUSE_INFO.SECTION;
DROP TABLE IF EXISTS HOUSE_INFO.DISTRICT;
DROP TABLE IF EXISTS HOUSE_INFO.NUMBER_POOL;




/* Create Tables */

CREATE TABLE HOUSE_INFO.ATTACH_CORPORATION
(
	ID VARCHAR(32) NOT NULL,
	RECORD_DATE TIMESTAMP,
	ADDRESS VARCHAR(100),
	PHONE VARCHAR(200),
	OWNER_NAME VARCHAR(20),
	OWNER_CARD VARCHAR(50),
	FAX VARCHAR(50),
	EMAIL VARCHAR(50),
	MEMO VARCHAR(200),
	PASSWORD VARCHAR(50),
	POST_CODE VARCHAR(50),
	ENABLE BIT(1) NOT NULL,
	LICENSE_NUMBER VARCHAR(100),
	TAX_LICENSE VARCHAR(100),
	COMPANY_CODE VARCHAR(100),
	COMPANY_TYPE VARCHAR(32),
	REGISTER_MONEY DECIMAL(19,4),
	LEVEL VARCHAR(32),
	DATE_TO TIMESTAMP,
	MANAGER VARCHAR(20),
	LOGIN_ID VARCHAR(50),
	CONSTRAINT PK_INTERMEDIARY PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.ATTACH_EMPLOYEE
(
	ID VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	LICENSE_LEVE VARCHAR(32),
	LICENSE_NUMBER VARCHAR(50),
	LICENSE_TIME_TO TIMESTAMP,
	PHONE VARCHAR(20),
	DEUCATION VARCHAR(32),
	NAME VARCHAR(50) NOT NULL,
	CREDENTIALS_TYPE VARCHAR(32),
	CREDENTIALS_NUMBER VARCHAR(100),
	ENABLE BIT(1),
	CREATE_TIME TIMESTAMP,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.BUILD
(
	ID VARCHAR(32) NOT NULL,
	MAP_NUMBER VARCHAR(4),
	BLOCK_NO VARCHAR(10) NOT NULL,
	BUILD_NO VARCHAR(4) NOT NULL,
	STREET_CODE VARCHAR(4),
	NAME VARCHAR(100) NOT NULL UNIQUE,
	COMPLETE_DATE VARCHAR(6),
	PROJECT_ID VARCHAR(32) NOT NULL,
	DOOR_NO VARCHAR(10),
	UNINT_COUNT INT,
	HOUSE_COUNT INT,
	AREA DECIMAL(18,3),
	LNG DECIMAL(18,14),
	LAT DECIMAL(18,14),
	ZOOM INT,
	BUILD_TYPE VARCHAR(32),
	STRUCTURE VARCHAR(32) NOT NULL,
	VERSION INT,
	MEMO VARCHAR(200),
	NEXT_HOUSE_ORDER INT NOT NULL,
	UP_FLOOR_COUNT INT NOT NULL,
	DOWN_FLOOR_COUNT INT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	DEVELOPER_NUMBER VARCHAR(20),
	CONSTRAINT PK_BUILD PRIMARY KEY (ID),
	CONSTRAINT MAP_BLOCK_BUILD_UNIQUE UNIQUE (MAP_NUMBER, BLOCK_NO, BUILD_NO)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.BUILD_GRID_MAP
(
	ID VARCHAR(32) NOT NULL,
	BUILD_ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	_ORDER INT NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT BUILD_GRID_PAGE UNIQUE (BUILD_ID, _ORDER)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.CONTRACT_MORTGAGE
(
	ID VARCHAR(32) NOT NULL,
	IS_MORTGAGE VARCHAR(32),
	MORTGAGE_TYPE VARCHAR(60),
	MORTGAGE_PEOPRE VARCHAR(60),
	MORTGAGE_OBLIGEE VARCHAR(100),
	MORTGAGE_REGISTER VARCHAR(100),
	MORTGAGE_TIME VARCHAR(100),
	ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID, ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.DEMPLOYEE
(
	ID VARCHAR(32) NOT NULL,
	DEVELOPER VARCHAR(32) NOT NULL,
	ATTACH_EMPLOYEE_ID VARCHAR(32) NOT NULL,
	MEMO VARCHAR(200),
	CONSTRAINT PK_DEMPLOYEE PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.DEVELOPER
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PYCODE VARCHAR(100),
	VERSION INT NOT NULL,
	ATTACH_ID VARCHAR(32),
	DESTROYED BOOLEAN NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	DESCRIPTION VARCHAR(200),
	CONSTRAINT PK_DEVELOPER PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.DISTRICT
(
	ID VARCHAR(9) NOT NULL,
	NAME VARCHAR(100) NOT NULL UNIQUE,
	SHORT_NAME VARCHAR(10) NOT NULL,
	VERSION INT,
	CREATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT PK_DISTRICT PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.EMPLOYEE_ATTACH_ACTION
(
	ID VARCHAR(32) NOT NULL,
	TYPE INT NOT NULL,
	CONTEXT VARCHAR(200),
	CREATE_TIME TIMESTAMP,
	COMMIT_PERSION VARCHAR(50),
	ATTACH_EMPLOYEE_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.EVALUATE_CORPORATION
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PYCODE VARCHAR(100),
	VERSION INT NOT NULL,
	ATTACH_ID VARCHAR(32),
	DESTROYED BOOLEAN NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT PK_EVALUATECORPORATION PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.GRID_BLOCK
(
	ID VARCHAR(32) NOT NULL,
	ROW_ID VARCHAR(32) NOT NULL,
	_ORDER INT NOT NULL,
	COLSPAN INT NOT NULL,
	ROWSPAN INT NOT NULL,
	AREA DECIMAL(18,3),
	USE_AREA DECIMAL(18,3),
	COMM_AREA DECIMAL(18,3),
	SHINE_AREA DECIMAL(18,3),
	LOFT_AREA DECIMAL(18,3),
	COMM_PARAM DECIMAL(18,3),
	USE_TYPE VARCHAR(32),
	STRUCTURE VARCHAR(32),
	HOUSE_TYPE VARCHAR(32),
	UNIT_INDEX INT NOT NULL,
	UNIT_NAME VARCHAR(32) NOT NULL,
	HOUSE_ORDER VARCHAR(20),
	DIRECTION VARCHAR(32),
	EAST_WALL VARCHAR(32),
	WEST_WALL VARCHAR(32),
	SOUTH_WALL VARCHAR(32),
	NORTH_WALL VARCHAR(32),
	KNOT_SIZE VARCHAR(32),
	HAVE_DOWN_ROOM BOOLEAN NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.GRID_ROW
(
	ID VARCHAR(32) NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	_ORDER INT NOT NULL,
	GRID_ID VARCHAR(32) NOT NULL,
	FLOOR_INDEX INT NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.HOUSE
(
	ID VARCHAR(32) NOT NULL,
	BUILDID VARCHAR(32) NOT NULL,
	HOUSE_ORDER VARCHAR(20) NOT NULL,
	HOUSE_UNIT_NAME VARCHAR(20),
	IN_FLOOR_NAME VARCHAR(50) NOT NULL,
	HOUSE_AREA DECIMAL(18,3) NOT NULL,
	USE_AREA DECIMAL(18,3),
	COMM_AREA DECIMAL(18,3),
	SHINE_AREA DECIMAL(18,10),
	LOFT_AREA DECIMAL(18,3),
	COMM_PARAM DECIMAL(18,3),
	HOUSE_TYPE VARCHAR(32),
	USE_TYPE VARCHAR(32) NOT NULL,
	STRUCTURE VARCHAR(32) NOT NULL,
	KNOT_SIZE VARCHAR(32),
	ADDRESS VARCHAR(200) NOT NULL,
	DATA_SOURCE VARCHAR(32) NOT NULL,
	EAST_WALL VARCHAR(32),
	WEST_WALL VARCHAR(32),
	SOUTH_WALL VARCHAR(32),
	NORTH_WALL VARCHAR(32),
	MAP_TIME TIMESTAMP,
	DIRECTION VARCHAR(32),
	VERSION INT,
	MEMO VARCHAR(200),
	HAVE_DOWN_ROOM BOOLEAN NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	GRID_BLOCK_ID VARCHAR(32),
	CONSTRAINT PK_HOUSE PRIMARY KEY (ID),
	CONSTRAINT HOUSE_ORDER_BUILD_UNIQUE UNIQUE (BUILDID, HOUSE_ORDER)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.HOUSE_COMMERCI_CONTRACT
(
	ID VARCHAR(32) NOT NULL,
	COMMERCI_TYPE VARCHAR(32) NOT NULL,
	HTDSR_CMR VARCHAR(100) NOT NULL,
	HTDSR_CMR_DZ VARCHAR(100) NOT NULL,
	HTDSR_CMR_YB VARCHAR(15),
	HTDSR_CMR_YYZZ VARCHAR(30) NOT NULL,
	HTDSR_CMR_QYZSH VARCHAR(30) NOT NULL,
	HTDSR_CMR_FDDBR VARCHAR(10) NOT NULL,
	HTDSR_CMR_FDDBRDH VARCHAR(15) NOT NULL,
	HTDSR_CMR_WTDLR VARCHAR(10),
	HTDSR_CMR_WTDLRDH VARCHAR(15),
	XMJSYJ_TDQDFS VARCHAR(32) NOT NULL,
	XMJSYJ_TDZL VARBINARY(50) NOT NULL,
	XMJSYJ_TDSQQQLX VARCHAR(32) NOT NULL,
	XMJSYJ_TDQZH VARCHAR(30) NOT NULL UNIQUE,
	XMJSYJ_TDMJ DECIMAL(18,3) NOT NULL,
	XMJSYJ_TDYT VARCHAR(20) NOT NULL,
	XMJSYJ_TDSYQZZSJ TIMESTAMP NOT NULL,
	XMJSYJ_XMMC VARCHAR(100) NOT NULL,
	XMJSYJ_JSGCGHXKZH VARCHAR(50) NOT NULL,
	XMJSYJ_JZGCSGXUKZH VARCHAR(50) NOT NULL,
	SPFJBQK_FWSJYT VARCHAR(32) NOT NULL,
	SPFJBQK_FWJG VARCHAR(32) NOT NULL,
	SPFJBQK_FWJZZCS INT NOT NULL,
	SPFJBQK_FWJZDSCS INT NOT NULL,
	SPFJBQK_FWJZDXCS INT NOT NULL,
	SPFJBQK_ZH VARCHAR(20) NOT NULL,
	SPFJBQK_ZUOHAO VARCHAR(20),
	SPFJBQK_DYH VARCHAR(10) NOT NULL,
	SPFJBQK_CH VARCHAR(10) NOT NULL,
	SPFJBQK_CHJG VARCHAR(50) NOT NULL,
	SPFJBQK_JZMJ DECIMAL(18,3) NOT NULL,
	SPFJBQK_TNMJ DECIMAL(18,3) NOT NULL,
	SPFJBQK_FTMJ DECIMAL(18,3) NOT NULL,
	CGW DECIMAL(8,3) NOT NULL,
	YGYT INT NOT NULL,
	YJGFBYT INT NOT NULL,
	FBYTGS INT NOT NULL,
	FWQLZKQN4 VARCHAR(100),
	FWQLZKQN5 VARCHAR(100),
	AZ VARCHAR(10),
	FWQLZKCN_CFFS VARCHAR(32),
	DJZ INT,
	TNMJ_BZ1 VARCHAR(32),
	TNMJ_Y1 DECIMAL(18,3),
	TNMJ_ZJKBZ1 VARCHAR(32),
	TNMJ_ZJK1 DECIMAL(18,3),
	TNMJ_ZJKDX1 VARCHAR(50),
	JZMJ_BZ2 VARCHAR(32),
	JZMJ_Y2 DECIMAL(18,3),
	JZMJ_ZJKBZ2 VARCHAR(32),
	JZMJ_ZJK2 DECIMAL(18,3),
	ZJKDX2 VARCHAR(50),
	T_BZ3 VARCHAR(32),
	T_ZJK3 DECIMAL(18,3),
	T_ZJKDX3 VARCHAR(50),
	QT_AZJS VARCHAR(20),
	QT_BZ4 VARCHAR(32),
	QT_ZJK4 DECIMAL(18,3),
	QT_ZJKDX4 VARCHAR(50),
	FKFSJQX_BZ1 VARCHAR(32),
	FKFSJQX_ZJK1 VARCHAR(50),
	FKFSJQX_DJJFFS VARCHAR(32),
	FKFSJQX_DYSPFJK VARCHAR(32),
	DJZFKFS INT,
	YCXFK_YCXFKSJ TIMESTAMP,
	FQFK_FQFKSJ TIMESTAMP,
	FQFK_FJQ INT,
	FQFK_SQFJKBZ VARCHAR(32),
	FQFK_SQFJKY DECIMAL(18,3),
	FQFK_SQFJKDX VARCHAR(50),
	FQFK_YDY TIMESTAMP,
	FQFK_YDYBZ VARCHAR(100),
	DKFS_DKFS VARCHAR(32),
	DKFS_MSRSFSJ TIMESTAMP,
	DKFS_DKSFBZ VARCHAR(32),
	DKFS_DKSFY DECIMAL(18,3),
	DKFS_DKSFKDX VARCHAR(50),
	DKFS_ZQBFKBFB VARCHAR(10),
	DKFS_YKBZ VARCHAR(32),
	DKFS_YK DECIMAL(18,3),
	DKFS_YKDX VARCHAR(100),
	DKFS_DKJG VARCHAR(100),
	FKQTFS VARCHAR(200),
	YQFKZEFS INT,
	YQJR1 INT,
	YFKWFZJ1 DECIMAL(8,3),
	YQFKZR_YQCGJR INT,
	SDZRQ INT,
	YFKBFB DECIMAL(8,3),
	YFKWFZJ2 DECIMAL(8,3),
	YQFKZRBZ2 VARCHAR(200),
	FHTJ3 INT,
	FHTJ4 INT,
	FHTJMEMO3 VARCHAR(100),
	FHTJMEMO4 VARCHAR(100),
	JCSSSB1 VARCHAR(100),
	JCSSSB2 VARCHAR(100),
	JCSSSB3 VARCHAR(100),
	JCSSSB4 VARCHAR(100),
	AZXLDJZCL INT,
	ZFWYJ5 DECIMAL(18,3),
	ZFWYJ6 DECIMAL(18,3),
	ZFWYJ7 DECIMAL(18,3),
	YDJFRHDJR INT,
	JFSYTJMEMO2 VARCHAR(100),
	LDLSJ TIMESTAMP,
	LDLMEMO VARCHAR(50),
	SZDLSJ TIMESTAMP,
	SZDLSJMEMO VARCHAR(50),
	GHDCWSJ TIMESTAMP,
	GHDCWMEMO VARCHAR(50),
	WYFWYF TIMESTAMP,
	WYFWYFMEMO VARCHAR(50),
	YLWSJG TIMESTAMP,
	YLWSJGMEMO VARCHAR(50),
	YEY TIMESTAMP,
	YEYMEMO VARCHAR(50),
	XX TIMESTAMP,
	XXMEMO VARCHAR(50),
	GGFWJPT8 VARCHAR(100),
	GGFWJPT9 VARCHAR(100),
	XQLDPCSM VARCHAR(50),
	FSZDLPCSM VARCHAR(50),
	CWCKPCSM VARCHAR(50),
	WYFWYFSM VARCHAR(50),
	QTSSWDDSM VARCHAR(50),
	CMRJHSH TIMESTAMP,
	JMQ INT,
	JFSJHSX2 VARCHAR(100),
	CYCRQ INT,
	CYFWBZ5 VARCHAR(100),
	CYFWBZ6 VARCHAR(100),
	CYFWBZ7 VARCHAR(100),
	CYFWBZ8 VARCHAR(100),
	YQJFCLFS INT,
	YQZDJRZN INT,
	WFZJ1 DECIMAL(8,3),
	YQCGJR INT,
	YQCGAZBFB2 DECIMAL(8,3),
	FJKDBFB2 DECIMAL(8,3),
	FJKWFZJ2 DECIMAL(8,3),
	YQJFZR2BZ VARCHAR(100),
	SPFZLJBXZR_BFB1 DECIMAL(8,3),
	SPFZLJBXZR_MEMO1 VARCHAR(100),
	SPFZLJBXZR_MEMO2 VARCHAR(100),
	SPFZLJBXZR_BFB2 DECIMAL(18,3),
	SPFZLJBXZR_QT_MEMO3 VARCHAR(100),
	SPFZLJBXZR_ZXBZ2 INT,
	SPFZLJBXZR_ZXBZ3 INT,
	SPFZLJBXZR_MEMO3 VARCHAR(100),
	SPFZLJBXZR_MEMO4 VARCHAR(100),
	-- 国家，地方
	SPFZLJBXZR_KQZLBZ VARCHAR(32) COMMENT '国家，地方',
	SPFZLJBXZR_KQBZMC VARBINARY(100),
	SPFZLJBXZR_KQBZWH VARCHAR(50),
	-- 国家，地方
	SPFZLJBXZR_GYBZ VARCHAR(32) COMMENT '国家，地方',
	SPFZLJBXZR_AZ DECIMAL(8,3),
	SPFZLJBXZR_MEMO5 VARCHAR(100),
	SPFZLJBXZR_BXZE_MEMO6 VARBINARY(100),
	SPFZLJBXZR_BXZE_HMRR INT,
	SPFZLJBXZR_ZLDB_Y VARCHAR(50),
	HTBAYFWDJ_QQWYGL_MC VARCHAR(50),
	HTBAYFWDJ_QQWYGL_FWSJQ TIMESTAMP,
	HTBAYFWDJ_QQWYGL_FWSJZ TIMESTAMP,
	HTBAYFWDJ_QQWYGL_WYJFFS VARCHAR(32),
	HTBAYFWDJ_QQWYGL_MYWYF DECIMAL(10,3),
	QTSX_JZWQFSYQ_MEMO1 VARCHAR(100),
	QTSX_JZWQFSYQ_CKCW VARCHAR(50),
	QTSX_JZWQFSYQ_HS VARCHAR(100),
	QTSX_JZWQFSYQ_MEMO3 VARCHAR(100),
	QTSX_SXHSYQCN_MEMO6 VARCHAR(100),
	QTSX_SXHSYQCN_MEMO7 VARCHAR(100),
	QTSX_SD_FS VARCHAR(32),
	QTSX_SD_BGZR INT,
	QTSX_ZYJJFS_FSJW INT,
	QTSX_ZYJJFS_ZCWYHMC VARCHAR(50),
	QTSX_HTSX_BHTYS INT,
	QTSX_HTSX_HTFS INT,
	QTSX_HTSX_CMRFS INT,
	QTSX_HTSX_MSRFS INT,
	QTSX_HTSX_MC1 INT UNSIGNED ZEROFILL,
	QTSX_HTSX_FS1 INT,
	QTSX_HTSX_MC2 INT,
	QTSX_HTSX_FS2 INT,
	QDSJ TIMESTAMP,
	QDDD VARCHAR(50),
	ZSZXJXGSB_WQ VARCHAR(32),
	ZSZXJXGSB_WQBZ VARCHAR(100),
	ZSZXJXGSB_QJS_NQ VARCHAR(32),
	ZSZXJXGSB_QJS_DP VARCHAR(32),
	ZSZXJXGSB_QJS_DPBZ VARCHAR(100),
	ZSZXJXGSB_QJS_SNDM VARCHAR(32),
	ZSZXJXGSB_QJS_SNDMBZ VARCHAR(100),
	ZSZXJXGSB_CF_DM VARCHAR(32),
	ZSZXJXGSB_CF_DMBZ VARCHAR(100),
	ZSZXJXGSB_CF_QM VARCHAR(32),
	ZSZXJXGSB_CF_QMBZ VARCHAR(100),
	ZSZXJXGSB_CF_DP VARCHAR(32),
	ZSZXJXGSB_CF_DPBZ VARCHAR(100),
	ZSZXJXGSB_CF_CJ VARCHAR(200),
	ZSZXJXGSB_WSJ_DM VARCHAR(32),
	ZSZXJXGSB_WSJ_DMBZ VARBINARY(100),
	ZSZXJXGSB_WSJ_QM VARCHAR(32),
	ZSZXJXGSB_WSJ_QMBZ VARCHAR(100),
	ZSZXJXGSB_WSJ_DP VARCHAR(32),
	ZSZXJXGSB_WSJ_DPBZ VARCHAR(100),
	ZSZXJXGSB_WSJ_QJ VARCHAR(100),
	ZSZXJXGSB_YT VARCHAR(32),
	ZSZXJXGSB_YTBZ VARCHAR(100),
	ZSZXJXGSB_DT_PP VARCHAR(100),
	ZSZXJXGSB_DT_XH VARCHAR(100),
	ZSZXJXGSB_GD VARCHAR(100),
	ZSZXJXGSB_CH VARCHAR(100),
	ZSZXJXGSB_BZ9 VARCHAR(100),
	ZSZXJXGSB_BZ10 VARCHAR(100),
	BXFWQXZR_DJJCHZTJG_BXQX VARCHAR(20),
	BXFWQXZR_DJJCHZTJG_BXQXBZ VARCHAR(100),
	BXFWQXZR_FSGC_BXQX VARCHAR(20),
	BXFWQXZR_FSGC_BXQXBZ VARCHAR(100),
	BXFWQXZR_GLGR_BXQX VARCHAR(20),
	BXFWQXZR_GLGR_BXQXBZ VARCHAR(100),
	BXFWQXZR_DXGX_BXQX VARCHAR(20),
	BXFWQXZR_DXGX_BXQXBZ VARCHAR(100),
	BXFWQXZR_ZXGC_BXQX VARCHAR(20),
	BXFWQXZR_ZXGC_BXQXBZ VARCHAR(100),
	BXFWQXZR_MEMO6 VARCHAR(100),
	BXFWQXZR_MEMO7 VARCHAR(100),
	BXFWQXZR_MEMO8 VARCHAR(100),
	BXFWQXZR_QTYD VARCHAR(200),
	EMPLOYEE VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.HOUSE_CONTRACT
(
	ID VARCHAR(32) NOT NULL,
	HOUSE_ID VARCHAR(32) NOT NULL,
	TYPE VARCHAR(32),
	PASSWORD VARCHAR(50),
	PRICE DECIMAL(18,3),
	RECORD_TIME TIMESTAMP,
	PART_COUNT INT NOT NULL,
	PAY_TYPE VARCHAR(32),
	MEMO VARCHAR(200),
	OWNER VARCHAR(50) NOT NULL,
	ID_TYPE VARCHAR(32) NOT NULL,
	ID_NO VARCHAR(100) NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	SELL_CORPORATION VARCHAR(50),
	SELL_CORPORATION_ADDRESS VARCHAR(50),
	SELL_CORPORATION_POST VARCHAR(50),
	SELL_CORPORATION_CODE VARCHAR(50),
	SELL_CORPORATION_NUMBER VARCHAR(50),
	SELL_CORPORATION_LEGAL VARCHAR(50),
	SELL_CORPORATION_CALL VARCHAR(15),
	PHONE VARCHAR(15),
	BIRTHDAY TIMESTAMP,
	SEX BIT(1),
	ROOT_ADDRESS VARCHAR(50),
	ADDRESS VARCHAR(100),
	LEGAL_PERSON VARCHAR(50),
	POST_CODE VARCHAR(50),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.HOUSE_GRID_TITLE
(
	ID VARCHAR(32) NOT NULL,
	_ORDER INT NOT NULL,
	TITLE VARCHAR(32) NOT NULL,
	COLSPAN INT NOT NULL,
	GRILD_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.HOUSE_SELL_COMPANY
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	VERSION INT NOT NULL,
	ATTACH_ID VARCHAR(32) NOT NULL,
	DESTROYED BOOLEAN NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT PK_INTERMEDIARY PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.MAPPING_CORPORATION
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PYCODE VARCHAR(100),
	VERSION INT NOT NULL,
	ATTACH_ID VARCHAR(32),
	DESTROYED BOOLEAN NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT PK_MAPPINGCORPORATION PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.MCOMPANY
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PYCODE VARCHAR(50),
	VERSION INT NOT NULL,
	ATTACH_ID VARCHAR(32),
	DESTROYED BOOLEAN NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT PK_MCOMPANY PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.NEW_HOUSE_CONTRACT_PRESALE
(
	VERSION INT NOT NULL,
	YSYJ_YSJG VARCHAR(100) NOT NULL,
	YSYJ_YSXKZH VARCHAR(50) NOT NULL,
	YSZJJGJG VARCHAR(100),
	YSJZJGZHMC VARCHAR(100),
	YSZJJGJGZH VARCHAR(100),
	MJCYCLFS INT,
	MJCY_AZBFB1 DECIMAL(8,3),
	MJCY_AZBFB2 DECIMAL(8,3),
	MJCYMEMO3 VARCHAR(100),
	MJCLCLMEMO4 VARCHAR(100),
	GHSJ_BFB1 DECIMAL(8,3),
	GHSJ_FJKBFB1 DECIMAL(8,3),
	GHSJ_MEMO1 VARCHAR(100),
	GHSJ_MEMO3 VARCHAR(100),
	GHSJ_MEMO4 VARCHAR(4),
	GHSJ_MEMO5 VARCHAR(100),
	GHSJ_BFB2 DECIMAL(8,3),
	GHSJ_FJKBFB2 DECIMAL(8,3),
	GHSJ_MEMO6 VARCHAR(100),
	HTBAYFWDJ_BASJ INT,
	HTBAYFWDJ_BASJ_QTYD VARCHAR(150),
	HTBAYFWDJ_FWDJ_FJZRQN INT,
	HTBAYFWDJ_FWDJ_CLFS INT,
	HTBAYFWDJ_FWDJ_AZBFB DECIMAL(8,3),
	HTBAYFWDJ_FWDJ_WFZJ DECIMAL(8,3),
	HTBAYFWDJ_FWDJ_MEMO1 VARCHAR(100),
	QTSX_SF_YCD VARCHAR(50),
	ID VARCHAR(32) NOT NULL,
	CONSTRAINT PK_NEWHOUSECONTRACT PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.NEW_HOUSE_CONTRACT_SALE
(
	SSYJ_ZJLX VARCHAR(32),
	SSYJ_QZH VARCHAR(30),
	SSYJ_JGMC VARCHAR(32),
	SSYJ_DJJG VARCHAR(50),
	SSYJ_SFCZ VARCHAR(32),
	SSYJ_ZLQXS TIMESTAMP,
	SSYJ_ZLQXZ TIMESTAMP,
	SSYJ_BZ VARCHAR(100),
	ZHMC VARCHAR(50),
	KHYH VARCHAR(100),
	ZK VARCHAR(50),
	ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.NUMBER_POOL
(
	ID VARCHAR(32) NOT NULL,
	NUMBER BIGINT UNSIGNED NOT NULL,
	VERSION INT,
	TYPE VARCHAR(20) NOT NULL,
	USE_TIME TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.OLDHOUSECONTRACT
(
	ID VARCHAR(32) NOT NULL,
	IEMPLOYEE VARCHAR(32) NOT NULL,
	CONTRACT_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	CONSTRAINT PK_OLDHOUSECONTRACT PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.ORG_ATTACH_ACTION
(
	ID VARCHAR(32) NOT NULL,
	TYPE INT NOT NULL,
	CONTEXT VARCHAR(200),
	CREATE_TIME TIMESTAMP,
	COMMIT_PERSION VARCHAR(50),
	CORPORATION_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.OWNER_GROUP
(
	ID VARCHAR(32) NOT NULL,
	SECTION VARCHAR(32) NOT NULL,
	NUMBER VARCHAR(50) NOT NULL UNIQUE,
	NAME VARCHAR(50) NOT NULL,
	PHONE VARCHAR(50),
	ADDRESS VARCHAR(200),
	REGISTER_TIME TIMESTAMP,
	MANAGER VARCHAR(50),
	TOTALCOUNT INT,
	MEMO VARCHAR(200),
	CREATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT PK_OWNERGROUP PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.POOL_BUILD
(
	ID VARCHAR(32) NOT NULL,
	MAP_NUMBER VARCHAR(50) NOT NULL,
	BLOCK_NO VARCHAR(10) NOT NULL,
	BUILD_NO VARCHAR(4) NOT NULL,
	HOUSE_NUMBER VARCHAR(50) NOT NULL,
	BUILD_NAME VARCHAR(50) NOT NULL,
	STRUCTURE VARCHAR(32) NOT NULL,
	ADDRESS VARCHAR(200),
	AREA DECIMAL(18,3) NOT NULL,
	MEMO VARCHAR(200),
	REG_TIME TIMESTAMP,
	FLOOR_COUNT INT NOT NULL,
	SECTION_ID VARCHAR(32) NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT PK_POOLBUILD PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.POOL_OWNER
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	ID_TYPE VARCHAR(32) NOT NULL,
	ID_NO VARCHAR(100) NOT NULL,
	RELATION VARCHAR(32),
	POOL_AREA DECIMAL(19,4),
	PERC VARCHAR(10),
	MEMO VARCHAR(200),
	PHONE VARCHAR(15),
	CONTRACT_ID VARCHAR(32) NOT NULL,
	LEGAL_PERSON VARCHAR(50),
	ROOT_ADDRESS VARCHAR(50),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.PROJECT
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	SECTIONID VARCHAR(32) NOT NULL,
	DEVELOPERID VARCHAR(32),
	ADDRESS VARCHAR(200),
	BUILD_SIZE VARCHAR(32),
	BUILD_COUNT INT,
	AREA DECIMAL(18,3),
	SUM_AREA DECIMAL(18,3),
	MEMO VARCHAR(200),
	MAP_TIME TIMESTAMP,
	VERSION INT,
	CREATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT PK_PROJECT PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.PROJECT_BUILD_PROCESS
(
	ID VARCHAR(32) NOT NULL,
	PROJECT_ID VARCHAR(32),
	PROCESS_TIME TIMESTAMP,
	MONEY DECIMAL(18,3),
	MEMO VARCHAR(200),
	CONSTRAINT PK_PROJECTCREATEPROCESS PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.SECTION
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	PYCODE VARCHAR(50),
	ADDRESS VARCHAR(200),
	VERSION INT,
	CREATE_TIME TIMESTAMP NOT NULL,
	DISTRICT VARCHAR(9) NOT NULL,
	CONSTRAINT PK_SECTION PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE HOUSE_INFO.SELL_EMPLOYEE
(
	ID VARCHAR(32) NOT NULL,
	INTERMEDIARY VARCHAR(32) NOT NULL,
	ATTACH_EMLOPEE_ID VARCHAR(32) NOT NULL,
	MEMO VARCHAR(200),
	CONSTRAINT PK_IEMPLOYEE PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- 一个物业公司可能管理多个小区
CREATE TABLE HOUSE_INFO.SMSUBCOMPANY
(
	ID VARCHAR(32) NOT NULL,
	MCOMPANY VARCHAR(32),
	SECTION VARCHAR(32) NOT NULL,
	NAME VARCHAR(50),
	ADDRESS VARCHAR(100),
	MANAGER VARCHAR(50),
	PHONE VARCHAR(50),
	REGISTER_TIME TIMESTAMP,
	MEMO VARCHAR(200),
	DESTROYED BOOLEAN NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	CONSTRAINT PK_SMSUBCOMPANY PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '一个物业公司可能管理多个小区' DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE HOUSE_INFO.DEVELOPER
	ADD FOREIGN KEY (ATTACH_ID)
	REFERENCES HOUSE_INFO.ATTACH_CORPORATION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.EVALUATE_CORPORATION
	ADD FOREIGN KEY (ATTACH_ID)
	REFERENCES HOUSE_INFO.ATTACH_CORPORATION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.MCOMPANY
	ADD FOREIGN KEY (ATTACH_ID)
	REFERENCES HOUSE_INFO.ATTACH_CORPORATION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.HOUSE_SELL_COMPANY
	ADD FOREIGN KEY (ATTACH_ID)
	REFERENCES HOUSE_INFO.ATTACH_CORPORATION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.ORG_ATTACH_ACTION
	ADD FOREIGN KEY (CORPORATION_ID)
	REFERENCES HOUSE_INFO.ATTACH_CORPORATION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.MAPPING_CORPORATION
	ADD FOREIGN KEY (ATTACH_ID)
	REFERENCES HOUSE_INFO.ATTACH_CORPORATION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.DEMPLOYEE
	ADD FOREIGN KEY (ATTACH_EMPLOYEE_ID)
	REFERENCES HOUSE_INFO.ATTACH_EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.EMPLOYEE_ATTACH_ACTION
	ADD FOREIGN KEY (ATTACH_EMPLOYEE_ID)
	REFERENCES HOUSE_INFO.ATTACH_EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.SELL_EMPLOYEE
	ADD FOREIGN KEY (ATTACH_EMLOPEE_ID)
	REFERENCES HOUSE_INFO.ATTACH_EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.HOUSE
	ADD CONSTRAINT FK_HOUSE_HOUSEANDB_BUILD FOREIGN KEY (BUILDID)
	REFERENCES HOUSE_INFO.BUILD (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.BUILD_GRID_MAP
	ADD FOREIGN KEY (BUILD_ID)
	REFERENCES HOUSE_INFO.BUILD (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.GRID_ROW
	ADD FOREIGN KEY (GRID_ID)
	REFERENCES HOUSE_INFO.BUILD_GRID_MAP (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.HOUSE_GRID_TITLE
	ADD FOREIGN KEY (GRILD_ID)
	REFERENCES HOUSE_INFO.BUILD_GRID_MAP (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.HOUSE_COMMERCI_CONTRACT
	ADD FOREIGN KEY (EMPLOYEE)
	REFERENCES HOUSE_INFO.DEMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.DEMPLOYEE
	ADD CONSTRAINT FK_DEMPLOYE_REFERENCE_DEVELOPE FOREIGN KEY (DEVELOPER)
	REFERENCES HOUSE_INFO.DEVELOPER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.PROJECT
	ADD CONSTRAINT FK_PROJECT_REFERENCE_DEVELOPE FOREIGN KEY (DEVELOPERID)
	REFERENCES HOUSE_INFO.DEVELOPER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.SECTION
	ADD CONSTRAINT FK_SECTION_REFERENCE_DISTRICT FOREIGN KEY (DISTRICT)
	REFERENCES HOUSE_INFO.DISTRICT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.GRID_BLOCK
	ADD FOREIGN KEY (ROW_ID)
	REFERENCES HOUSE_INFO.GRID_ROW (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.HOUSE_CONTRACT
	ADD FOREIGN KEY (HOUSE_ID)
	REFERENCES HOUSE_INFO.HOUSE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.CONTRACT_MORTGAGE
	ADD FOREIGN KEY (ID)
	REFERENCES HOUSE_INFO.HOUSE_COMMERCI_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.NEW_HOUSE_CONTRACT_PRESALE
	ADD FOREIGN KEY (ID)
	REFERENCES HOUSE_INFO.HOUSE_COMMERCI_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.NEW_HOUSE_CONTRACT_SALE
	ADD FOREIGN KEY (ID)
	REFERENCES HOUSE_INFO.HOUSE_COMMERCI_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.POOL_OWNER
	ADD FOREIGN KEY (CONTRACT_ID)
	REFERENCES HOUSE_INFO.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.OLDHOUSECONTRACT
	ADD FOREIGN KEY (CONTRACT_ID)
	REFERENCES HOUSE_INFO.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.HOUSE_COMMERCI_CONTRACT
	ADD FOREIGN KEY (ID)
	REFERENCES HOUSE_INFO.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.SELL_EMPLOYEE
	ADD CONSTRAINT FK_IEMPLOYE_REFERENCE_INTERMED FOREIGN KEY (INTERMEDIARY)
	REFERENCES HOUSE_INFO.HOUSE_SELL_COMPANY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.SMSUBCOMPANY
	ADD CONSTRAINT FK_SMSUBCOM_REFERENCE_MCOMPANY FOREIGN KEY (MCOMPANY)
	REFERENCES HOUSE_INFO.MCOMPANY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.PROJECT_BUILD_PROCESS
	ADD CONSTRAINT FK_PROJECTC_REFERENCE_PROJECT FOREIGN KEY (PROJECT_ID)
	REFERENCES HOUSE_INFO.PROJECT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.BUILD
	ADD CONSTRAINT FK_BUILD_REFERENCE_PROJECT FOREIGN KEY (PROJECT_ID)
	REFERENCES HOUSE_INFO.PROJECT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.SMSUBCOMPANY
	ADD CONSTRAINT FK_SMSUBCOM_REFERENCE_SECTION FOREIGN KEY (SECTION)
	REFERENCES HOUSE_INFO.SECTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.PROJECT
	ADD CONSTRAINT FK_PROJECT_REFERENCE_SECTION FOREIGN KEY (SECTIONID)
	REFERENCES HOUSE_INFO.SECTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.OWNER_GROUP
	ADD CONSTRAINT FK_OWNERGRO_REFERENCE_SECTION FOREIGN KEY (SECTION)
	REFERENCES HOUSE_INFO.SECTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.POOL_BUILD
	ADD FOREIGN KEY (SECTION_ID)
	REFERENCES HOUSE_INFO.SECTION (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HOUSE_INFO.OLDHOUSECONTRACT
	ADD CONSTRAINT FK_OLDHOUSE_REFERENCE_IEMPLOYE2 FOREIGN KEY (IEMPLOYEE)
	REFERENCES HOUSE_INFO.SELL_EMPLOYEE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



