DROP FUNCTION IF EXISTS START_NUM;
DELIMITER ||
CREATE FUNCTION START_NUM(full_str TEXT)
RETURNS int
BEGIN
  DECLARE s varchar(256) DEFAULT full_str;
  IF ISNULL(s) THEN
    RETURN NULL;
  END IF;
  IF NOT s REGEXP '^.*[0-9]+.*$' THEN
    RETURN NULL;
  END IF;
  WHILE (1 <= CHARACTER_LENGTH(s)) DO
    IF s REGEXP '^[0-9]+$' THEN
      RETURN CONVERT(s,int);
    ELSEIF s REGEXP '^[^0-9]+[0-9]+.*$' THEN
      SET s = RIGHT(s,CHARACTER_LENGTH(s) - 1);
    ELSEIF (s REGEXP '^.*[0-9]+.+$') THEN
      SET s = LEFT(s,CHARACTER_LENGTH(s) - 1);
    ELSE
       RETURN NULL;
    END IF; 
  END WHILE;
  RETURN NULL;
END||
DELIMITER ;


SELECT START_NUM('9898');

SELECT START_NUM('东本1-2人人');