use HOUSE_OWNER_RECORD;

alter table HOUSE_OWNER_RECORD.HOUSE_CONTRACT
    add LEAST_PROTECTED Decimal(19,2) null;

alter table HOUSE_OWNER_RECORD.HOUSE_CONTRACT
    add MONEY_COMPLETE boolean default false not null;

alter table HOUSE_OWNER_RECORD.PROJECT
    add MONEY_COMPLETE boolean default false not null;


DROP TABLE IF EXISTS HOUSE_OWNER_RECORD.PROJECT_INIT_BUSINESS;

CREATE TABLE HOUSE_OWNER_RECORD.PROJECT_INIT_BUSINESS
(
    ID VARCHAR(32) NOT NULL,
    PROJECT VARCHAR(32) NOT NULL,
    -- 倒库导入原库的NO
    BUSINESS VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
    INIT_CARD_NUMBER VARCHAR(32),
    ACCOUNT VARCHAR(128),
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE HOUSE_OWNER_RECORD.PROJECT_INIT_BUSINESS
    ADD FOREIGN KEY (BUSINESS)
        REFERENCES HOUSE_OWNER_RECORD.OWNER_BUSINESS (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

ALTER TABLE HOUSE_OWNER_RECORD.PROJECT_INIT_BUSINESS
    ADD FOREIGN KEY (PROJECT)
        REFERENCES HOUSE_OWNER_RECORD.PROJECT (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='2.3.10' where ID='database_version';