CREATE TABLE HOUSE_OWNER_RECORD.MONEY_SAFE
(
	ID VARCHAR(32) NOT NULL,
	BANK VARCHAR(32) NOT NULL,
	ACCOUNT_NAME VARCHAR(128) NOT NULL,
	CREATE_BANK_NAME VARCHAR(512) NOT NULL,
	CARD_NUMBER VARCHAR(128) NOT NULL,
	CARD_NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



ALTER TABLE HOUSE_OWNER_RECORD.MONEY_SAFE
	ADD FOREIGN KEY (ID)
	REFERENCES HOUSE_OWNER_RECORD.PROJECT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


INSERT DB_PLAT_SYSTEM.SYSTEM_PARAM (ID, TYPE, VALUE, MEMO) values ('MONEY_SAFE_TIME','STRING','2018-01-01','商口房资金监管开始时间');
INSERT DB_PLAT_SYSTEM.REPORT (ID, NAME, DESCRIPTION, PAGE) VALUE ('86','商品房资金监管受理单','商品房资金监管受理单','/report/dgfcc/DgProjectMoneySafeTicket.xhtml');
