ALTER TABLE HOUSE_OWNER_RECORD.SALE_INFO ADD SALEAREA decimal (19,4) NULL;

ALTER TABLE DB_PLAT_SYSTEM.EMPLOYEE ADD WINDOW_NO varchar (10) NULL;

ALTER TABLE HOUSE_OWNER_RECORD.BUSINESS_EMP ADD WINDOW_NO varchar (10) NULL;
