ALTER TABLE HOUSE_OWNER_RECORD.OWNER_BUSINESS ADD IN_ROOM BOOLEAN NOT NULL;


ALTER TABLE HOUSE_OWNER_RECORD.RECORD_STORE ADD CABINET BOOLEAN NOT NULL;
ALTER TABLE HOUSE_OWNER_RECORD.RECORD_STORE ADD FRAME BOOLEAN NOT NULL;
ALTER TABLE HOUSE_OWNER_RECORD.RECORD_STORE ADD BOX BOOLEAN NOT NULL;
ALTER TABLE HOUSE_OWNER_RECORD.RECORD_STORE ADD ROOM BOOLEAN NOT NULL;