use HOUSE_OWNER_RECORD;


CREATE TABLE HOUSE_OWNER_RECORD.LEASE
(
  ID VARCHAR(32) NOT NULL,
  BUISINESS_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  LEASE_AREA DECIMAL(18,3) NOT NULL,
  SELF_RENT DECIMAL(19,4) NOT NULL,
  EVALUATE_RENT DECIMAL(19,4) NOT NULL,
  SUM_RENT DECIMAL(19,4) NOT NULL,
  START_DATE DATETIME NOT NULL,
  END_DATE DATETIME,
  SUM_MONTH INT NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



ALTER TABLE HOUSE_OWNER_RECORD.LEASE
ADD FOREIGN KEY (BUISINESS_ID)
REFERENCES HOUSE_OWNER_RECORD.BUSINESS_EMP (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE HOUSE_OWNER_RECORD.LEASE ADD TIME_AREA_TYPE varchar (20) NULL;