
CREATE TABLE HOUSE_OWNER_RECORD.RECORD_ROOM
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(200) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE HOUSE_OWNER_RECORD.RECORD_FRAME
(
	ID VARCHAR(32) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	ROOM VARCHAR(32) NOT NULL,
	VERSION BIGINT NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE HOUSE_OWNER_RECORD.RECORD_FRAME
	ADD FOREIGN KEY (ROOM)
	REFERENCES HOUSE_OWNER_RECORD.RECORD_ROOM (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE HOUSE_OWNER_RECORD.RECORD_STORE DROP IN_ROOM;

ALTER TABLE DB_PLAT_SYSTEM.BUSINESS_DEFINE MODIFY PICK_BUSINESS_DEFINE_ID VARCHAR(200);

UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='2.1.2' where ID='database_version';