
ALTER TABLE HOUSE_OWNER_RECORD.HOUSE ADD SALE_CONTRACT VARCHAR(32) NULL;
UPDATE HOUSE_AND_CONTRACT hac LEFT JOIN HOUSE h on h.ID = hac.HOUSE set h.SALE_CONTRACT = hac.CONTRACT;

DROP TABLE HOUSE_OWNER_RECORD.HOUSE_AND_CONTRACT;
ALTER TABLE HOUSE_OWNER_RECORD.HOUSE
  ADD FOREIGN KEY (SALE_CONTRACT)
REFERENCES HOUSE_OWNER_RECORD.HOUSE_CONTRACT (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE HOUSE_OWNER_RECORD.CONTRACT_SUBMIT ADD FILE_ID VARCHAR(32) NULL;

INSERT INTO SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('OldHouseContractBizId','STRING','WP56','二手房备案启动业务编号');
