CREATE TABLE HOUSE_OWNER_RECORD.GIVE_CARD
(
  ID VARCHAR(32) NOT NULL UNIQUE,
-- 倒库导入原库的NO
  BUISINESS_ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
-- 领证人
  NAME VARCHAR(50) NOT NULL COMMENT '领证人',
  ID_NO VARCHAR(100) NOT NULL,
  ID_TYPE VARCHAR(32) NOT NULL,
  PHONE VARCHAR(15),
  GIVE_TIME DATETIME,
  MEMO VARCHAR(200),
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


ALTER TABLE HOUSE_OWNER_RECORD.GIVE_CARD
ADD FOREIGN KEY (BUISINESS_ID)
REFERENCES HOUSE_OWNER_RECORD.OWNER_BUSINESS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

--update file b