ALTER TABLE HOUSE_OWNER_RECORD.CONTRACT_NUMBER ADD GROUP_NUMBER VARCHAR(32) NOT NULL;

UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='1.2.7' where ID='database_version';

UPDATE HOUSE_OWNER_RECORD.CONTRACT_NUMBER set TYPE = 'DEVELOPER';

ALTER TABLE HOUSE_OWNER_RECORD.CONTRACT_NUMBER ADD GROUP_NAME VARCHAR(100) NULL;

INSERT INTO DB_PLAT_SYSTEM.SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('contract_type','STRING','AUTO','合同发放方式,AUTO:自动;PUB:发放;COMMIT:提交;');

INSERT INTO DB_PLAT_SYSTEM.SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('contract_number_length','INTEGER','4','合同号长度');

ALTER TABLE HOUSE_OWNER_RECORD.CARD ADD CODE VARCHAR (30) NULL;
ALTER TABLE HOUSE_OWNER_RECORD.CARD ADD MEMO VARCHAR (200) NULL;