ALTER TABLE HOUSE_OWNER_RECORD.RECORD_STORE DROP IN_ROOM;

DROP TABLE HOUSE_OWNER_RECORD.RECORD_LOCAL;
DROP TABLE HOUSE_OWNER_RECORD.HOUSE_AND_RECORD;

ALTER TABLE HOUSE_OWNER_RECORD.RECORD_STORE DROP ROOM;


UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='2.1.1' where ID='database_version';