
CREATE TABLE HOUSE_OWNER_RECORD.LOCKED_HOUSE_CANCEL
(
  ID VARCHAR(32) NOT NULL,
  HOUSE_CODE VARCHAR(32) NOT NULL,
  EMP_CODE VARCHAR(32) NOT NULL,
  EMP_NAME VARCHAR(50) NOT NULL,
  CANCEL_TIME TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR(500),
  TYPE VARCHAR(32) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;