
USE HOUSE_OWNER_RECORD;



CREATE TABLE HOUSE_OWNER_RECORD.ATTACH_CORPORATION
(
	ID VARCHAR(32) NOT NULL,
	TYPE VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	PHONE VARCHAR(200) NOT NULL,
	OWNER_NAME VARCHAR(100) NOT NULL,
	OWNER_CARD VARCHAR(50),
	FAX VARCHAR(50),
	EMAIL VARCHAR(50),
	MEMO VARCHAR(200),
	POST_CODE VARCHAR(50),
	LICENSE_NUMBER VARCHAR(100) NOT NULL,
	COMPANY_CODE VARCHAR(100),
	COMPANY_TYPE VARCHAR(32),
	REGISTER_MONEY DECIMAL(19,4),
	LEVEL VARCHAR(32),
	COMPANY_CER_CODE VARCHAR(100),
	OWNER_TEL VARCHAR(100) ,
	CREDENTIALS_TYPE VARCHAR(16) NOT NULL,
	LEGAL_TYPE VARCHAR(16) NOT NULL,
	-- 倒库导入原库的NO
	BUSINESS_ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT PK_INTERMEDIARY PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


ALTER TABLE HOUSE_OWNER_RECORD.ATTACH_CORPORATION
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES HOUSE_OWNER_RECORD.OWNER_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


INSERT DB_PLAT_SYSTEM.ROLE (ID, NAME, DESCRIPTION, PRIORITY) VALUE ('corp_apply','从业机构业务受理','从业机构业务受理',40);
INSERT DB_PLAT_SYSTEM.ROLE (ID, NAME, DESCRIPTION, PRIORITY) VALUE ('corp_first_check','从业机构业务初审','从业机构业务初审',41);
INSERT DB_PLAT_SYSTEM.ROLE (ID, NAME, DESCRIPTION, PRIORITY) VALUE ('corp_last_check','从业机构业务审批','从业机构业务审批',42);

alter table HOUSE_INFO.ATTACH_CORPORATION modify OWNER_TEL varchar(100) null;

UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='2.5' where ID='database_version';