INSERT INTO DB_PLAT_SYSTEM.SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('idleGirdMapUnitSort','STRING','desc','自动分户图单元排序方式');

INSERT INTO DB_PLAT_SYSTEM.SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('moneyCalcAllowFree','BOOLEAN','true','是否允许全部减免');

INSERT INTO DB_PLAT_SYSTEM.SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('moneyCalcAllowHalf','BOOLEAN','true','是否允许半价减免');

INSERT INTO DB_PLAT_SYSTEM.SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('applyPersonTelMust','BOOLEAN','true','申请人电话必填');

