CREATE TABLE HOUSE_INFO.PERSONAL_CONTRACT_LOGON
(
	ID VARCHAR(32) NOT NULL,
	HOUSE_CODE VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	USER_KEY VARCHAR(32) NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	BUSINESS_ID VARCHAR(32) NOT NULL,
	DATE_TO DATETIME,
	ENABLE BIT(1) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


INSERT DB_PLAT_SYSTEM.FUNCTION (ID, NAME, ICON, LOCATION, BANNER, PRIORITY, MEMO, CATEGORY, NEED_CONVERSATION) VALUE ('owner.PersonalContract','个人网签备案开户','','/func/house/owner/PersonalContractLogOnList.xhtml','',102,'','DATA_MGR',0);
INSERT DB_PLAT_SYSTEM.ROLE (ID, NAME, DESCRIPTION, PRIORITY) VALUE ('owner.PersonalContractMgr','个人网签备案开户','个人网签备案开户',102);
INSERT DB_PLAT_SYSTEM.ROLE_FUNCTION (FUN_ID, ROL_ID) VALUE ('owner.PersonalContract','owner.PersonalContractMgr');