
INSERT INTO SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('HouseSourceBizId','STRING','HS1','房源审核业务ID');

ALTER TABLE HOUSE_OWNER_RECORD.SALE_SHOW_CHECK ADD SOURCE_DATA LONGTEXT NOT NULL;

ALTER TABLE HOUSE_OWNER_RECORD.BUSINESS_HOUSE DROP FOREIGN KEY F_SALE_CHECK_SHOW;
DROP INDEX F_SALE_CHECK_SHOW ON HOUSE_OWNER_RECORD.BUSINESS_HOUSE;
ALTER TABLE HOUSE_OWNER_RECORD.BUSINESS_HOUSE DROP SALE_CHECK;

DROP TABLE HOUSE_OWNER_RECORD.SALE_SHOW_CHECK;


CREATE TABLE HOUSE_OWNER_RECORD.HOUSE_SOURCE
(
  ID VARCHAR(32) NOT NULL,
  -- 倒库导入原库的NO
  BUSINESS VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
  HOUSE VARCHAR(32) NOT NULL,
  CHECKED BOOLEAN NOT NULL,
  MESSAGES VARCHAR(200),
  SOURCE_ID VARCHAR(32) NOT NULL,
  SOURCE_DATA LONGTEXT NOT NULL,
  DISPLAY LONGTEXT NOT NULL,
  SEARCH_KEY VARCHAR(1024) NOT NULL,
  ATTR_ID VARCHAR(32) NOT NULL,
  ATTR_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE HOUSE_OWNER_RECORD.HOUSE_SOURCE
  ADD FOREIGN KEY (HOUSE)
REFERENCES HOUSE_OWNER_RECORD.HOUSE (ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;

ALTER TABLE HOUSE_OWNER_RECORD.HOUSE_SOURCE
  ADD FOREIGN KEY (BUSINESS)
REFERENCES HOUSE_OWNER_RECORD.OWNER_BUSINESS (ID)
ON UPDATE RESTRICT
ON DELETE RESTRICT
;


UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='2.1.3' where ID='database_version';