CREATE TABLE HOUSE_OWNER_RECORD.MONEY_BACK_BUSINESS
(
	ID VARCHAR(32) NOT NULL,
	-- 撤消备案退款  CANCEL
	-- 未备案退款      ABORT
	-- 冲正退款         DELETE
	TYPE VARCHAR(8) NOT NULL COMMENT '撤消备案退款  CANCEL
未备案退款      ABORT
冲正退款         DELETE',
	CONTRACT VARCHAR(50),
	MONEY DECIMAL(19,2) NOT NULL,
	-- 倒库导入原库的NO
	BUSINESS VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
	DISPLAY LONGTEXT,
	SEARCH_KEY VARCHAR(1024),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;