ALTER TABLE HOUSE_OWNER_RECORD.LOCKED_HOUSE ADD BUILD_CODE VARCHAR(32) NULL;

update  HOUSE_OWNER_RECORD.LOCKED_HOUSE lh left join HOUSE_INFO.HOUSE h on h.ID = lh.HOUSE_CODE set lh.BUILD_CODE= h.BUILDID ;