CREATE TABLE HOUSE_OWNER_RECORD.REPAIR_MONEY_PAY
(
	ID VARCHAR(32) NOT NULL,
	BUSINESS VARCHAR(32) NOT NULL,
	CALC_DETAILS VARCHAR(512),
	MUST_MONEY DECIMAL(18,2) NOT NULL,
	MONEY DECIMAL(18,2) NOT NULL,
	DESCRIPTION VARCHAR(512),
	NOTICE_TIME DATETIME NOT NULL,
	EMP_CODE VARCHAR(32) NOT NULL,
	EMP_NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE HOUSE_OWNER_RECORD.REPAIR_MONEY_PAY
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES HOUSE_OWNER_RECORD.BUSINESS_HOUSE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
CREATE TABLE HOUSE_OWNER_RECORD.REPAIR_MONEY_INFO
(
	ID VARCHAR(32) NOT NULL,
	PUBLIC_AREA DECIMAL(18,3) NOT NULL,
	PRIVATE_AREA DECIMAL(18,3),
	PUBLIC_RATE DECIMAL(18,2) NOT NULL,
	PRIVATE_RATE DECIMAL(18,2),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE HOUSE_OWNER_RECORD.REPAIR_MONEY_INFO
	ADD FOREIGN KEY (ID)
	REFERENCES HOUSE_OWNER_RECORD.REPAIR_MONEY_PAY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='2.3.1' where ID='database_version';