CREATE TABLE HOUSE_OWNER_RECORD.REPAIR_MONEY_PAY
(
	ID VARCHAR(32) NOT NULL,
	BUSINESS VARCHAR(32) NOT NULL,
	CALC_DETAILS VARCHAR(512),
	MUST_MONEY DECIMAL(18,2) NOT NULL,
	MONEY DECIMAL(18,2) NOT NULL,
	DESCRIPTION VARCHAR(512),
	NOTICE_TIME DATETIME NOT NULL,
	EMP_CODE VARCHAR(32) NOT NULL,
	EMP_NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE HOUSE_OWNER_RECORD.REPAIR_MONEY_PAY
	ADD FOREIGN KEY (BUSINESS)
	REFERENCES HOUSE_OWNER_RECORD.BUSINESS_HOUSE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
CREATE TABLE HOUSE_OWNER_RECORD.REPAIR_MONEY_INFO
(
	ID VARCHAR(32) NOT NULL,
	PUBLIC_AREA DECIMAL(18,3) NOT NULL,
	PRIVATE_AREA DECIMAL(18,3),
	PUBLIC_RATE DECIMAL(18,2) NOT NULL,
	PRIVATE_RATE DECIMAL(18,2),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE HOUSE_OWNER_RECORD.REPAIR_MONEY_INFO
	ADD FOREIGN KEY (ID)
	REFERENCES HOUSE_OWNER_RECORD.REPAIR_MONEY_PAY (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

INSERT DB_PLAT_SYSTEM.WORD_CATEGORY (ID, NAME, MEMO, SYSTEM) VALUE ('repair.rate','缴费费率','',true);
INSERT DB_PLAT_SYSTEM.WORD (ID, _KEY, _VALUE, CATEGORY, DESCRIPTION, PRIORITY, ENABLE) value ('72.0','0','72','repair.rate',null,1,true);
INSERT DB_PLAT_SYSTEM.WORD (ID, _KEY, _VALUE, CATEGORY, DESCRIPTION, PRIORITY, ENABLE) value ('49.2','0','49.2','repair.rate',null,2,true);
INSERT DB_PLAT_SYSTEM.WORD (ID, _KEY, _VALUE, CATEGORY, DESCRIPTION, PRIORITY, ENABLE) value ('15.36','0','15.36','repair.rate',null,3,true);

UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='2.3.1' where ID='database_version';



CREATE TABLE HOUSE_OWNER_RECORD.OLD_SELL_CONTRACT_INFO
(
  ID VARCHAR(32) NOT NULL,
-- 倒库导入原库的NO
  BUSINESS_ID VARCHAR(32) NOT NULL COMMENT '倒库导入原库的NO',
  POO_CARDS VARCHAR(200),
  LAND_GET_MODE VARCHAR(32),
  LAND_CARD_NO VARCHAR(50),
  LEASE_MEMO VARCHAR(32),
  SALE_TYPE VARCHAR(5),
  HOUSE_SELL_COMPANY VARCHAR(100),
-- earnest
  EARNEST_DATE DATETIME COMMENT 'earnest',
  EARNEST_MONEY DECIMAL(18,3),
  PAY_TYPE VARCHAR(5),
  ALL_PAY_DATE DATETIME,
  DEBIT_DATE DATETIME,
  DEBIT_FIRST_MONEY DECIMAL(18,3),
  DEBIT_OTHER_MONEY DECIMAL(18,3),
  PAY_OTHER VARCHAR(200),
-- 买受人因自身原因未获得贷款部门批准的，双方同意按照第____种方
  DEBIT_TYPE VARCHAR(10) COMMENT '买受人因自身原因未获得贷款部门批准的，双方同意按照第____种方',
  DEBIT_OTHER VARCHAR(200),
-- 买卖双方约定按下列第      项方式支付及保管房款
  KEEPING_TYPE VARCHAR(5) COMMENT '买卖双方约定按下列第      项方式支付及保管房款',
  CONTRACT_SELL_COMPANY VARCHAR(100),
  BANK_NAME VARCHAR(100),
  BANK_NAME_NO VARCHAR(100),
-- 该房屋在交付日以前发生的水、电、
  HOUSE_OTHER_MEMO VARCHAR(100) COMMENT '该房屋在交付日以前发生的水、电、',
--  出卖人应当在______年______月______日前将该房屋交付给买受人。
  PAY_HOUSE_DATE DATETIME COMMENT ' 出卖人应当在______年______月______日前将该房屋交付给买受人。',
-- Breach
  BREACH_TYPE VARCHAR(5) COMMENT 'Breach',
  BREACH_OTTHER VARCHAR(200),
-- 2.所需税、费全部由    方缴纳
  TAX_PAY VARCHAR(10) COMMENT '2.所需税、费全部由    方缴纳',
-- 3.
  TAX_OTHER VARCHAR(200) COMMENT '3.',
-- dispute
  DISPUTE_TYPE VARCHAR(5) COMMENT 'dispute',
  OTHER_MEMO VARCHAR(200),
  PAGES VARCHAR(5),
  SHERES VARCHAR(5),
  SELLER_SHERES VARCHAR(5),
  BUYER_SHERES VARCHAR(5),
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


ALTER TABLE HOUSE_OWNER_RECORD.OLD_SELL_CONTRACT_INFO
ADD FOREIGN KEY (BUSINESS_ID)
REFERENCES HOUSE_OWNER_RECORD.OWNER_BUSINESS (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;
