ALTER TABLE HOUSE_OWNER_RECORD.LEASE ADD SELL_COMPANY_NAME varchar(100) NOT NULL;
ALTER TABLE HOUSE_OWNER_RECORD.LEASE ADD SEARCH_KEY varchar(1024) NULL;
ALTER TABLE HOUSE_OWNER_RECORD.LEASE ADD DISPLAY longtext NULL;
ALTER TABLE HOUSE_OWNER_RECORD.LEASE DROP FOREIGN KEY lease_ibfk_1;
ALTER TABLE HOUSE_OWNER_RECORD.LEASE
	ADD FOREIGN KEY (BUISINESS_ID)
	REFERENCES HOUSE_OWNER_RECORD.OWNER_BUSINESS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;
INSERT DB_PLAT_SYSTEM.BUSINESS_CATEGORY (ID, NAME, PRIORITY) VALUE ('house.money.lease','租赁备案登记',12);
ALTER TABLE HOUSE_OWNER_RECORD.LEASE ADD LEASE_NO varchar(20) NULL;
INSERT DB_PLAT_SYSTEM.REPORT (ID, NAME, DESCRIPTION, PAGE) VALUE ('85','房屋租赁调查审批表','房屋租赁调查审批表','/report/fcfcc/FcApplyLeaseHouseBook.xhtml');


UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='2.2.2' where ID='database_version';