CREATE TABLE HOUSE_INFO.PERSONAL_CONTRACT_LOGON
(
	ID VARCHAR(32) NOT NULL,
	HOUSE_CODE VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	USER_KEY VARCHAR(32) NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	BUSINESS_ID VARCHAR(32) NOT NULL,
	DATE_TO DATETIME,
	ENABLE BIT(1) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE HOUSE_INFO.PERSONAL_CONTRACT_USER
(
	IDNO VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PASSWORDWORD VARCHAR(20) NOT NULL,
	PHONE VARCHAR(13) NOT NULL,
	PRIMARY KEY (IDNO)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;
