INSERT INTO SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('BUSINESS_FILE_CHECK_TYPE','STRING','LOCAL','文件上传检测方式:FTP,LOCAL');
INSERT INTO SYSTEM_PARAM(ID,TYPE,VALUE,MEMO) VALUES('LOCAL_FILE_UPLOAD_PATH','STRING','/home/ftp/business/','本地文件系统检测目录');
