ALTER TABLE HOUSE_OWNER_RECORD.PROJECT_CHECK ADD SEARCH_KEY varchar(1024) NULL;
ALTER TABLE HOUSE_OWNER_RECORD.PROJECT_CHECK ADD DISPLAY longtext NULL;

UPDATE DB_PLAT_SYSTEM.SYSTEM_PARAM set VALUE='2.3.11' where ID='database_version';