package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import cc.coopersoft.house.sale.data.HouseSellCompany;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;

/**
 * HouseSellCompany generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_SELL_COMPANY" , catalog = "HOUSE_INFO")
public class Agencies extends HouseSellCompany implements java.io.Serializable {

	private String id;
	private int version;
	private AttachCorporation attachCorporation;
	private String name;
    private boolean destroyed;
	private Date createTime;
	private String tel;
	private String saleTel;
	private boolean control;



	public Agencies() {
	}

	public Agencies(AttachCorporation attachCorporation, Date createTime) {
		this.attachCorporation = attachCorporation;
		this.createTime = createTime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@OneToOne(fetch = FetchType.LAZY, orphanRemoval = true, cascade = CascadeType.ALL)
	@JoinColumn(name = "ATTACH_ID",nullable = true)
	public AttachCorporation getAttachCorporation() {
		return this.attachCorporation;
	}

	public void setAttachCorporation(AttachCorporation attachCorporation) {
		this.attachCorporation = attachCorporation;
	}

	@Column(name = "NAME" , nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESTROYED" ,nullable = false)
    public boolean isDestroyed() {
        return destroyed;
    }

    public void setDestroyed(boolean destroyed) {
        this.destroyed = destroyed;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", nullable = false)
	@NotNull
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "TEL",nullable = false, length = 16)
	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "SALE_TEL", length = 16)
	@Size(max = 16)
	public String getSaleTel() {
		return saleTel;
	}

	public void setSaleTel(String saleTel) {
		this.saleTel = saleTel;
	}

	@Column(name = "CONTROL", nullable = false)
	public boolean isControl() {
		return control;
	}

	public void setControl(boolean control) {
		this.control = control;
	}
}
