package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name = "CARD", catalog = "HOUSE_INFO")
public class Card implements java.io.Serializable {

	private String id;
	private String number;
	private String cardCode;
	private int type;
	private String businessCode;
	private Date printTime;
	private String memo;
	private Set<PoolOwner> poolOwners = new HashSet<PoolOwner>(0);
	private Set<HouseCard> houseCards = new HashSet<HouseCard>(0);
	private Set<ProjectSellCard> projectSellCards = new HashSet<ProjectSellCard>(
			0);

	public Card() {
	}

	public Card(String id, int type, Date printTime) {
		this.id = id;
		this.type = type;
		this.printTime = printTime;
	}
	public Card(String id, String number, String cardCode, int type,
			String businessCode, Date printTime, String memo,
			Set<PoolOwner> poolOwners, Set<HouseCard> houseCards,
			Set<ProjectSellCard> projectSellCards) {
		this.id = id;
		this.number = number;
		this.cardCode = cardCode;
		this.type = type;
		this.businessCode = businessCode;
		this.printTime = printTime;
		this.memo = memo;
		this.poolOwners = poolOwners;
		this.houseCards = houseCards;
		this.projectSellCards = projectSellCards;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NUMBER", length = 50)
	@Size(max = 50)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "CARD_CODE", length = 50)
	@Size(max = 50)
	public String getCardCode() {
		return this.cardCode;
	}

	public void setCardCode(String cardCode) {
		this.cardCode = cardCode;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "BUSINESS_CODE", length = 32)
	@Size(max = 32)
	public String getBusinessCode() {
		return this.businessCode;
	}

	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRINT_TIME", nullable = false, length = 19)
	@NotNull
	public Date getPrintTime() {
		return this.printTime;
	}

	public void setPrintTime(Date printTime) {
		this.printTime = printTime;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "card")
	public Set<PoolOwner> getPoolOwners() {
		return this.poolOwners;
	}

	public void setPoolOwners(Set<PoolOwner> poolOwners) {
		this.poolOwners = poolOwners;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "card")
	public Set<HouseCard> getHouseCards() {
		return this.houseCards;
	}

	public void setHouseCards(Set<HouseCard> houseCards) {
		this.houseCards = houseCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "card")
	public Set<ProjectSellCard> getProjectSellCards() {
		return this.projectSellCards;
	}

	public void setProjectSellCards(Set<ProjectSellCard> projectSellCards) {
		this.projectSellCards = projectSellCards;
	}

}
