package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ContractAttachOwner generated by hbm2java
 */
@Entity
@Table(name = "CONTRACT_ATTACH_OWNER", catalog = "HOUSE_INFO")
public class ContractAttachOwner implements java.io.Serializable {

	private String id;
	private HouseOwner houseOwner;
	private HouseContract houseContract;
	private BigDecimal owneScale;
	private String relation;

	public ContractAttachOwner() {
	}

	public ContractAttachOwner(String id, HouseOwner houseOwner,
			HouseContract houseContract) {
		this.id = id;
		this.houseOwner = houseOwner;
		this.houseContract = houseContract;
	}
	public ContractAttachOwner(String id, HouseOwner houseOwner,
			HouseContract houseContract, BigDecimal owneScale, String relation) {
		this.id = id;
		this.houseOwner = houseOwner;
		this.houseContract = houseContract;
		this.owneScale = owneScale;
		this.relation = relation;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OWNER_ID", nullable = false)
	@NotNull
	public HouseOwner getHouseOwner() {
		return this.houseOwner;
	}

	public void setHouseOwner(HouseOwner houseOwner) {
		this.houseOwner = houseOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTRACT_ID", nullable = false)
	@NotNull
	public HouseContract getHouseContract() {
		return this.houseContract;
	}

	public void setHouseContract(HouseContract houseContract) {
		this.houseContract = houseContract;
	}

	@Column(name = "OWNE_SCALE", scale = 4)
	public BigDecimal getOwneScale() {
		return this.owneScale;
	}

	public void setOwneScale(BigDecimal owneScale) {
		this.owneScale = owneScale;
	}

	@Column(name = "RELATION", length = 32)
	@Size(max = 32)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

}
