package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import org.hibernate.annotations.GenericGenerator;
import org.jboss.seam.international.StatusMessage;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.dgsoft.common.utils.persistence.UniqueVerify;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Developer generated by hbm2java
 */
@Entity
@Table(name = "DEVELOPER", catalog = "HOUSE_INFO")
@UniqueVerify(name = "name", severity = StatusMessage.Severity.ERROR, field = {"name"})
public class Developer implements java.io.Serializable {

    private String id;
    private int version;
    private AttachCorporation attachCorporation;
    private String name;
    private String pyCode;
    private Date createTime;
    private Set<Project> projects = new HashSet<Project>(0);
    private String description;
    private boolean destroyed;

    public Developer() {
    }

    public Developer(AttachCorporation attachCorporation) {
        destroyed = false;
        this.attachCorporation = attachCorporation;
    }

    public Developer(String id,Date createTime, boolean destroyed){
        this.id = id;
        this.createTime = createTime;
        this.destroyed = destroyed;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 32)
    @NotNull
    @Size(max = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Version
    @Column(name = "VERSION", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @OneToOne(fetch = FetchType.LAZY, cascade = {CascadeType.ALL}, orphanRemoval = true, optional = true)
    @JoinColumn(name = "ATTACH_ID", nullable = true)
    public AttachCorporation getAttachCorporation() {
        return this.attachCorporation;
    }

    public void setAttachCorporation(AttachCorporation attachCorporation) {
        this.attachCorporation = attachCorporation;
    }

    @Column(name = "NAME", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name="PYCODE",nullable = true, length = 100)
    @Size(max = 100)
    public String getPyCode() {
        return pyCode;
    }

    public void setPyCode(String pyCode) {
        this.pyCode = pyCode;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "developer")
    public Set<Project> getProjects() {
        return this.projects;
    }

    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }

    @Column(name = "DESTROYED", nullable = false)
    public boolean isDestroyed() {
        return destroyed;
    }

    public void setDestroyed(boolean destroyed) {
        this.destroyed = destroyed;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME",nullable = false)
    @NotNull
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "DESCRIPTION", length = 200)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
