package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import com.dgsoft.common.NamedEntity;
import com.dgsoft.common.utils.persistence.UniqueVerify;
import com.google.common.collect.Iterators;
import org.hibernate.annotations.GenericGenerator;
import org.jboss.seam.international.StatusMessage;

import java.util.*;
import javax.persistence.*;
import javax.swing.tree.TreeNode;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "DISTRICT", catalog = "HOUSE_INFO")
@UniqueVerify(name = "name", severity = StatusMessage.Severity.ERROR, field = {"name"})
public class District implements java.io.Serializable,TreeNode,NamedEntity {

	private String id;
	private Integer version;
	private String name;
	private String shortName;
	private Set<Section> sections = new HashSet<Section>(0);

	public District() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 9)
	@NotNull
	@Size(max = 9)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "NAME",unique = true, length = 100,nullable = false)
	@Size(max = 100)
    @NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SHORT_NAME", nullable = false, length = 10)
	@Size(max = 10)
    @NotNull
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Section> getSections() {
		return this.sections;
	}

	public void setSections(Set<Section> sections) {
		this.sections = sections;
	}


    @Transient
    public List<Section> getSectionList(){
        return new ArrayList<Section>(getSections());
    }

    @Override
    @Transient
    public TreeNode getChildAt(int childIndex) {
        return getSectionList().get(childIndex);
    }

    @Override
    @Transient
    public int getChildCount() {
        return getSections().size();
    }

    @Override
    @Transient
    public TreeNode getParent() {
        return null;
    }

    @Override
    @Transient
    public int getIndex(TreeNode node) {
        return getSectionList().indexOf(node);
    }

    @Override
    @Transient
    public boolean getAllowsChildren() {
        return true;
    }

    @Override
    @Transient
    public boolean isLeaf() {
        return getSections().isEmpty();
    }

    @Override
    @Transient
    public Enumeration children() {
        return Iterators.asEnumeration(getSections().iterator());
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (this == obj){
            return true;
        }
        if (!(obj instanceof District)) {
            return false;
        }
        if (this.getId() == null){
            return this == obj;
        }
        return getId().equals(((District) obj).getId());


    }

    @Override
    public int hashCode() {
        if (this.getId() == null){
            return super.hashCode();
        }else{
            return getId().hashCode();
        }
    }

}
