package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * EmployeeAttachAction generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_ATTACH_ACTION", catalog = "HOUSE_INFO")
public class EmployeeAttachAction implements java.io.Serializable {

	private String id;
	private AttachEmployee attachEmployee;
	private int type;
	private String context;
	private Date createTime;
	private String commitPersion;

	public EmployeeAttachAction() {
	}

	public EmployeeAttachAction(String id, AttachEmployee attachEmployee,
			int type, Date createTime) {
		this.id = id;
		this.attachEmployee = attachEmployee;
		this.type = type;
		this.createTime = createTime;
	}
	public EmployeeAttachAction(String id, AttachEmployee attachEmployee,
			int type, String context, Date createTime, String commitPersion) {
		this.id = id;
		this.attachEmployee = attachEmployee;
		this.type = type;
		this.context = context;
		this.createTime = createTime;
		this.commitPersion = commitPersion;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATTACH_EMPLOYEE_ID", nullable = false)
	@NotNull
	public AttachEmployee getAttachEmployee() {
		return this.attachEmployee;
	}

	public void setAttachEmployee(AttachEmployee attachEmployee) {
		this.attachEmployee = attachEmployee;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "CONTEXT", length = 200)
	@Size(max = 200)
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	@NotNull
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "COMMIT_PERSION", length = 50)
	@Size(max = 50)
	public String getCommitPersion() {
		return this.commitPersion;
	}

	public void setCommitPersion(String commitPersion) {
		this.commitPersion = commitPersion;
	}

}
