package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseSellCompany generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_SELL_COMPANY", catalog = "HOUSE_INFO")
public class HouseSellCompany implements java.io.Serializable {

	private String id;
	private int version;
	private AttachCorporation attachCorporation;
	private String name;
    private boolean destroyed;
	private Set<SellEmployee> sellEmployees = new HashSet<SellEmployee>(0);

	public HouseSellCompany() {
        destroyed= false;
	}

	public HouseSellCompany(AttachCorporation attachCorporation) {
        destroyed= false;
		this.attachCorporation = attachCorporation;
	}


	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATTACH_ID", nullable = false)
	@NotNull
	public AttachCorporation getAttachCorporation() {
		return this.attachCorporation;
	}

	public void setAttachCorporation(AttachCorporation attachCorporation) {
		this.attachCorporation = attachCorporation;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "houseSellCompany")
	public Set<SellEmployee> getSellEmployees() {
		return this.sellEmployees;
	}

	public void setSellEmployees(Set<SellEmployee> sellEmployees) {
		this.sellEmployees = sellEmployees;
	}

    @Column(name = "DESTROYED",nullable = false)
    public boolean isDestroyed() {
        return destroyed;
    }

    public void setDestroyed(boolean destroyed) {
        this.destroyed = destroyed;
    }

}
