package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseCardId generated by hbm2java
 */
@Embeddable
public class HouseCardId implements java.io.Serializable {

	private String cardId;
	private String houseId;

	public HouseCardId() {
	}

	public HouseCardId(String cardId, String houseId) {
		this.cardId = cardId;
		this.houseId = houseId;
	}

	@Column(name = "CARD_ID", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getCardId() {
		return this.cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	@Column(name = "HOUSE_ID", nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getHouseId() {
		return this.houseId;
	}

	public void setHouseId(String houseId) {
		this.houseId = houseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HouseCardId))
			return false;
		HouseCardId castOther = (HouseCardId) other;

		return ((this.getCardId() == castOther.getCardId()) || (this
				.getCardId() != null
				&& castOther.getCardId() != null && this.getCardId().equals(
				castOther.getCardId())))
				&& ((this.getHouseId() == castOther.getHouseId()) || (this
						.getHouseId() != null
						&& castOther.getHouseId() != null && this.getHouseId()
						.equals(castOther.getHouseId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCardId() == null ? 0 : this.getCardId().hashCode());
		result = 37 * result
				+ (getHouseId() == null ? 0 : this.getHouseId().hashCode());
		return result;
	}

}
