package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * HouseContract generated by hbm2java
 */
@Entity
@Table(name = "HOUSE_CONTRACT", catalog = "HOUSE_INFO")
public class HouseContract implements java.io.Serializable {

	private String id;
	private House house;
	private String password;
	private Date recordTime;
	private BigDecimal price;
	private int state;
	private int partCount;
	private String payType;
	private String memo;
	private Set<OldHousecontract> oldHousecontracts = new HashSet<OldHousecontract>(0);

	private Set<NewHouseContract> newHouseContracts = new HashSet<NewHouseContract>(0);

	public HouseContract() {
	}

	public HouseContract(String id, House house,
			Date recordTime, int state, int partCount) {
		this.id = id;
		this.house = house;
		this.recordTime = recordTime;
		this.state = state;
		this.partCount = partCount;
	}
	public HouseContract(String id, House house,
			String password, Date recordTime, BigDecimal price, int state,
			int partCount, String payType, String memo,
			Set<OldHousecontract> oldHousecontracts,
			Set<NewHouseContract> newHouseContracts) {
		this.id = id;
		this.house = house;
		this.password = password;
		this.recordTime = recordTime;
		this.price = price;
		this.state = state;
		this.partCount = partCount;
		this.payType = payType;
		this.memo = memo;
		this.oldHousecontracts = oldHousecontracts;
		this.newHouseContracts = newHouseContracts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HOUSE_ID", nullable = false)
	@NotNull
	public House getHouse() {
		return this.house;
	}

	public void setHouse(House house) {
		this.house = house;
	}

	@Column(name = "PASSWORD", length = 50)
	@Size(max = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORD_TIME", nullable = false, length = 19)
	@NotNull
	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	@Column(name = "PRICE", precision = 18, scale = 3)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "STATE", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "PART_COUNT", nullable = false)
	public int getPartCount() {
		return this.partCount;
	}

	public void setPartCount(int partCount) {
		this.partCount = partCount;
	}

	@Column(name = "PAY_TYPE", length = 32)
	@Size(max = 32)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "houseContract")
	public Set<OldHousecontract> getOldHousecontracts() {
		return this.oldHousecontracts;
	}

	public void setOldHousecontracts(Set<OldHousecontract> oldHousecontracts) {
		this.oldHousecontracts = oldHousecontracts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "houseContract")
	public Set<NewHouseContract> getNewHouseContracts() {
		return this.newHouseContracts;
	}

	public void setNewHouseContracts(Set<NewHouseContract> newHouseContracts) {
		this.newHouseContracts = newHouseContracts;
	}

}
