package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * LandInfo generated by hbm2java
 */
@Entity
@Table(name = "LAND_INFO", catalog = "HOUSE_INFO")
public class LandInfo implements java.io.Serializable {

	private String id;
	private String landCardNo;
	private String number;
	private String landProperty;
	private Date beginUseTime;
	private Date endUseTime;
	private BigDecimal area;
	private String landGetMode;
	private String memo;
	private Set<House> houses = new HashSet<House>(0);
	private Set<Build> builds = new HashSet<Build>(0);

	public LandInfo() {
	}

	public LandInfo(String id, Date beginUseTime, Date endUseTime) {
		this.id = id;
		this.beginUseTime = beginUseTime;
		this.endUseTime = endUseTime;
	}
	public LandInfo(String id, String landCardNo, String number,
			String landProperty, Date beginUseTime, Date endUseTime,
			BigDecimal area, String landGetMode, String memo,
			Set<House> houses, Set<Build> builds) {
		this.id = id;
		this.landCardNo = landCardNo;
		this.number = number;
		this.landProperty = landProperty;
		this.beginUseTime = beginUseTime;
		this.endUseTime = endUseTime;
		this.area = area;
		this.landGetMode = landGetMode;
		this.memo = memo;
		this.houses = houses;
		this.builds = builds;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "LAND_CARD_NO", length = 50)
	@Size(max = 50)
	public String getLandCardNo() {
		return this.landCardNo;
	}

	public void setLandCardNo(String landCardNo) {
		this.landCardNo = landCardNo;
	}

	@Column(name = "NUMBER", length = 50)
	@Size(max = 50)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "LAND_PROPERTY", length = 32)
	@Size(max = 32)
	public String getLandProperty() {
		return this.landProperty;
	}

	public void setLandProperty(String landProperty) {
		this.landProperty = landProperty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BEGIN_USE_TIME", nullable = false, length = 19)
	@NotNull
	public Date getBeginUseTime() {
		return this.beginUseTime;
	}

	public void setBeginUseTime(Date beginUseTime) {
		this.beginUseTime = beginUseTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_USE_TIME", nullable = false, length = 19)
	@NotNull
	public Date getEndUseTime() {
		return this.endUseTime;
	}

	public void setEndUseTime(Date endUseTime) {
		this.endUseTime = endUseTime;
	}

	@Column(name = "AREA", precision = 18, scale = 3)
	public BigDecimal getArea() {
		return this.area;
	}

	public void setArea(BigDecimal area) {
		this.area = area;
	}

	@Column(name = "LAND_GET_MODE", length = 32)
	@Size(max = 32)
	public String getLandGetMode() {
		return this.landGetMode;
	}

	public void setLandGetMode(String landGetMode) {
		this.landGetMode = landGetMode;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "landInfo")
	public Set<House> getHouses() {
		return this.houses;
	}

	public void setHouses(Set<House> houses) {
		this.houses = houses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "landInfo")
	public Set<Build> getBuilds() {
		return this.builds;
	}

	public void setBuilds(Set<Build> builds) {
		this.builds = builds;
	}

}
