package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * MappingCorporation generated by hbm2java
 */
@Entity
@Table(name = "MAPPING_CORPORATION", catalog = "HOUSE_INFO")
public class MappingCorporation implements java.io.Serializable {

	private String id;
	private int version;
	private AttachCorporation attachCorporation;
	private String name;
	private boolean destroyed;

	public MappingCorporation() {
        destroyed = false;
	}

	public MappingCorporation(AttachCorporation attachCorporation) {
        destroyed = false;
		this.attachCorporation = attachCorporation;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATTACH_ID", nullable = false)
	@NotNull
	public AttachCorporation getAttachCorporation() {
		return this.attachCorporation;
	}

	public void setAttachCorporation(AttachCorporation attachCorporation) {
		this.attachCorporation = attachCorporation;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

    @Column(name = "DESTROYED",nullable = false)
    public boolean isDestroyed() {
        return destroyed;
    }

    public void setDestroyed(boolean destroyed) {
        this.destroyed = destroyed;
    }

}
