package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Mcompany generated by hbm2java
 */
@Entity
@Table(name = "MCOMPANY", catalog = "HOUSE_INFO")
public class Mcompany implements java.io.Serializable {

	private String id;
	private int version;
	private AttachCorporation attachCorporation;
	private String name;
	private boolean destroyed;
	private Set<Smsubcompany> smsubcompanies = new HashSet<Smsubcompany>(0);
	private String pyCode;
	public Mcompany() {
        destroyed = false;
	}

	public Mcompany(AttachCorporation attachCorporation) {
        destroyed = false;
		this.attachCorporation = attachCorporation;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@OneToOne(fetch = FetchType.LAZY, orphanRemoval = true, cascade = CascadeType.ALL)
	@JoinColumn(name = "ATTACH_ID",nullable = true)
	public AttachCorporation getAttachCorporation() {
		return this.attachCorporation;
	}

	public void setAttachCorporation(AttachCorporation attachCorporation) {
		this.attachCorporation = attachCorporation;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name="PYCODE",nullable = true, length = 100)
	@Size(max = 100)
	public String getPyCode() {
		return pyCode;
	}

	public void setPyCode(String pyCode) {
		this.pyCode = pyCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mcompany")
	public Set<Smsubcompany> getSmsubcompanies() {
		return this.smsubcompanies;
	}

	public void setSmsubcompanies(Set<Smsubcompany> smsubcompanies) {
		this.smsubcompanies = smsubcompanies;
	}

    @Column(name = "DESTROYED",nullable = false)
    public boolean isDestroyed() {
        return destroyed;
    }

    public void setDestroyed(boolean destroyed) {
        this.destroyed = destroyed;
    }

}
