package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OwnerGroup generated by hbm2java
 */
@Entity
@Table(name = "OWNER_GROUP", catalog = "HOUSE_INFO", uniqueConstraints = @UniqueConstraint(columnNames = "NUMBER"))
public class OwnerGroup implements java.io.Serializable {

	private String id;
	private Section section;
	private String number;
	private String name;
	private String phone;
	private String address;
	private Date registerTime;
	private String manager;
	private Integer totalcount;
	private String memo;

	public OwnerGroup() {
	}

	public OwnerGroup(String id, Section section, String number, String name,
			Date registerTime) {
		this.id = id;
		this.section = section;
		this.number = number;
		this.name = name;
		this.registerTime = registerTime;
	}
	public OwnerGroup(String id, Section section, String number, String name,
			String phone, String address, Date registerTime, String manager,
			Integer totalcount, String memo) {
		this.id = id;
		this.section = section;
		this.number = number;
		this.name = name;
		this.phone = phone;
		this.address = address;
		this.registerTime = registerTime;
		this.manager = manager;
		this.totalcount = totalcount;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECTION", nullable = false)
	@NotNull
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@Column(name = "NUMBER", unique = true, nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	@NotNull
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PHONE", length = 50)
	@Size(max = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "ADDRESS", length = 200)
	@Size(max = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGISTER_TIME", nullable = false, length = 19)
	@NotNull
	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	@Column(name = "MANAGER", length = 50)
	@Size(max = 50)
	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	@Column(name = "TOTALCOUNT")
	public Integer getTotalcount() {
		return this.totalcount;
	}

	public void setTotalcount(Integer totalcount) {
		this.totalcount = totalcount;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
