package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * PoolOwner generated by hbm2java
 */
@Entity
@Table(name = "POOL_OWNER", catalog = "HOUSE_INFO")
public class PoolOwner implements java.io.Serializable {

	private String id;
	private Card card;
	private House house;
	private HouseOwner houseOwner;
	private String relation;
	private BigDecimal owneScale;

	public PoolOwner() {
	}

	public PoolOwner(String id, Card card, House house, HouseOwner houseOwner) {
		this.id = id;
		this.card = card;
		this.house = house;
		this.houseOwner = houseOwner;
	}
	public PoolOwner(String id, Card card, House house, HouseOwner houseOwner,
			String relation, BigDecimal owneScale) {
		this.id = id;
		this.card = card;
		this.house = house;
		this.houseOwner = houseOwner;
		this.relation = relation;
		this.owneScale = owneScale;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD_ID", nullable = false)
	@NotNull
	public Card getCard() {
		return this.card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HOUSE_ID", nullable = false)
	@NotNull
	public House getHouse() {
		return this.house;
	}

	public void setHouse(House house) {
		this.house = house;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OWNER_ID", nullable = false)
	@NotNull
	public HouseOwner getHouseOwner() {
		return this.houseOwner;
	}

	public void setHouseOwner(HouseOwner houseOwner) {
		this.houseOwner = houseOwner;
	}

	@Column(name = "RELATION", length = 32)
	@Size(max = 32)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	@Column(name = "OWNE_SCALE", scale = 4)
	public BigDecimal getOwneScale() {
		return this.owneScale;
	}

	public void setOwneScale(BigDecimal owneScale) {
		this.owneScale = owneScale;
	}

}
