package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ProjectBuildProcess generated by hbm2java
 */
@Entity
@Table(name = "PROJECT_BUILD_PROCESS", catalog = "HOUSE_INFO")
public class ProjectBuildProcess implements java.io.Serializable {

	private String id;
	private Project project;
	private Date processTime;
	private BigDecimal money;
	private String memo;

	public ProjectBuildProcess() {
	}

	public ProjectBuildProcess(String id, Date processTime) {
		this.id = id;
		this.processTime = processTime;
	}
	public ProjectBuildProcess(String id, Project project, Date processTime,
			BigDecimal money, String memo) {
		this.id = id;
		this.project = project;
		this.processTime = processTime;
		this.money = money;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROCESS_TIME", nullable = false, length = 19)
	@NotNull
	public Date getProcessTime() {
		return this.processTime;
	}

	public void setProcessTime(Date processTime) {
		this.processTime = processTime;
	}

	@Column(name = "MONEY", precision = 18, scale = 3)
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
