package com.dgsoft.house.model;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Smsubcompany generated by hbm2java
 */
@Entity
@Table(name = "SMSUBCOMPANY", catalog = "HOUSE_INFO")
public class Smsubcompany implements java.io.Serializable {

	private String id;
	private Section section;
	private Mcompany mcompany;
	private String name;
	private String address;
	private String manager;
	private String phone;
	private Date registerTime;
	private Boolean enable;
	private String memo;

	public Smsubcompany() {
	}

	public Smsubcompany(String id, Section section, Date registerTime) {
		this.id = id;
		this.section = section;
		this.registerTime = registerTime;
	}
	public Smsubcompany(String id, Section section, Mcompany mcompany,
			String name, String address, String manager, String phone,
			Date registerTime, Boolean enable, String memo) {
		this.id = id;
		this.section = section;
		this.mcompany = mcompany;
		this.name = name;
		this.address = address;
		this.manager = manager;
		this.phone = phone;
		this.registerTime = registerTime;
		this.enable = enable;
		this.memo = memo;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	@NotNull
	@Size(max = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECTION", nullable = false)
	@NotNull
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MCOMPANY")
	public Mcompany getMcompany() {
		return this.mcompany;
	}

	public void setMcompany(Mcompany mcompany) {
		this.mcompany = mcompany;
	}

	@Column(name = "NAME", length = 50)
	@Size(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ADDRESS", length = 100)
	@Size(max = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "MANAGER", length = 50)
	@Size(max = 50)
	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	@Column(name = "PHONE", length = 50)
	@Size(max = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REGISTER_TIME", nullable = false, length = 19)
	@NotNull
	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	@Column(name = "ENABLE")
	public Boolean getEnable() {
		return this.enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	@Column(name = "MEMO", length = 200)
	@Size(max = 200)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
